### ISSUE TITLE
Changing windows size breaks keyboard 

### ISSUE THREAD

**Issue by sunarowicz** [Genymobile/scrcpy#5388] opened 2024-10-20 17:01 UTC
When I use physical keyboard simulation (the -K switch) resizing scrcpy window or starting it with shrinked window (e.g. with --window-width=1024) breaks keyboard functionality. It starts to send the shortcuts instead of typing the text, i.e. when I press the  "f" key (without pressing the MOD key) it performs the fullscreen action instead of typing the "f" character. Interestingly it sometimes works fine after starting scrcpy in shrinked window, but breaks as soon as I resize window with mouse.

It happens with every android device I use scrcpy with. But it is not the case if I use the default SDK keyboard mode with --shortcut-mod=rctrl and --prefer-text switches. Without these it happens too.

I run scrcpy version 2.7 builded from source on Ubuntu 24.04 running on arm64 SBC. The issue was presented in the version 2.4 too. If I remember well, in some even earlier versions there was no such issue.

This problem is driving me crazy, does anyone have any ideas on how to solve it? Thx.

**Comment by sunarowicz** [comment] 2024-10-20 20:44
UPDATE: I just realized, that when I press the single SUPER key (without any other keys) the issue disappears and text is being typed into scrcpy window instead of passing scrcpy shortcuts again. Then I can use shortcuts with the combination of SUPER and other keys as one would expect. Even resizing the scrcpy window with mouse does not break the correct functionality then.

So it seems to me like under some circumstances I mentioned in my previous post the shortcut modifier key (SUPER key in my case) being activated and locked without touching by user. At least until manually being pressed by user. Really weird...

I forgot to mention that I'm using KDE Plasma.

**Comment by rom1v** [comment] 2024-10-20 21:11
Weird, I'll make some test.

Meanwhile, could you test #5322 (merged after 2.7), maybe it solves your problem.

**Comment by rom1v** [comment] 2024-10-21 10:27
I cannot reproduce on XFCE (both 2.7 and current `dev` branch). Probably an issue with SDL+KDE I would say (where a "release" key event may be lost, so SDL still thinks Alt is pressed).

**Comment by sunarowicz** [comment] 2024-10-21 17:39
Thank you for your investigation and your time, I really appreciate it! But it really doesn't seem to be issue with scrcpy as I can tell now. You can close this.

I do not see this problem anymore after my yesterdays pressing the SUPER key while scrcpy window had focus. It had to be something "hanging" in my system (maybe in terminal window I'm launching scrcpy from), not a scrcpy issue. Frankly I almost do not use the SUPER key in my real life and I have been not using scrcpy shortcuts until now neither. So trying to press the modifier key to solve this problem didn't came to my mind earlier, unfortunately...:o)

Thank you for your support!

**Closed** 2024-12-18 11:23 UTC
