### ISSUE TITLE
macOS Catalina "Aborted"

### ISSUE THREAD

**Issue by Jimmy-J** [Genymobile/scrcpy#989] opened 2019-12-06 05:40 UTC
Hello, thank you very much for developing such a good tool.I can't use it in 10.15.1 version of macOS Catalina, what is the reason?

![image](https://user-images.githubusercontent.com/18379235/70298789-c5d6b900-182d-11ea-9a84-2e78d9d1255d.png)

![image](https://user-images.githubusercontent.com/18379235/70298617-39c49180-182d-11ea-8943-8af4740d6485.png)

![image](https://user-images.githubusercontent.com/18379235/70298534-ed795180-182c-11ea-9bdd-8dccd70266b1.png)

![image](https://user-images.githubusercontent.com/18379235/70298822-ec94ef80-182d-11ea-9b12-fd91ebabd563.png)

**Comment by rom1v** [comment] 2019-12-06 06:30
Thank you for your report.

This is a duplicate of #944.

_(in the future, please copy-paste text instead of screenshots so that the content is searchable)_

**Closed by rom1v** 2019-12-06 06:30 UTC
