### ISSUE TITLE
how to send audio in pc through scrcpy in windows?

### ISSUE THREAD

**Issue by StylishBoyGaming** [Genymobile/scrcpy#504] opened 2019-04-20 17:47 UTC

**Comment by rom1v** [comment] 2019-04-20 19:30
You can't through scrcpy on Windows.

**Comment by Nayan00** [comment] 2019-10-21 11:36
But why I can't through windows?
Will there be a further update for this?

**Comment by rom1v** [comment] 2020-04-11 23:07
Duplicate of #14.

**Closed by rom1v** 2020-04-11 23:07 UTC
Labels: audio
