### ISSUE TITLE
Audio streaming to both desktop and Quest 2 headset?

### ISSUE THREAD

**Issue by CatWithAKeyboard** [Genymobile/scrcpy#4018] opened 2023-05-19 00:32 UTC
Oculus Quest 2
Arch Linux

I want the audio from my headset to be streamed to desktop along with still having audio output on my headset. Is this possible?

**Comment by rom1v** [comment] 2023-05-19 07:12
Duplicate of #3875.

**Closed by rom1v** 2023-05-19 07:12 UTC
