### ISSUE TITLE
Add package to winget

### ISSUE THREAD

**Issue by DestroyerXyz** [Genymobile/scrcpy#2413] opened 2021-06-21 13:28 UTC
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create and submit a package to Winget (Microsoft's new package manager for Windows) [community repo](https://github.com/microsoft/winget-pkgs)

**Comment by rom1v** [comment] 2021-06-21 13:32
Duplicate of #1444.

**Closed by rom1v** 2021-06-21 13:32 UTC
