### ISSUE TITLE
Arch w/ Wayland scrcpy 1.17 Android 12 Developer Preview NO VIDEO OUTPUT

### ISSUE THREAD

**Issue by randodude123** [Genymobile/scrcpy#2132] opened 2021-02-19 13:38 UTC
- [ X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
**Environment**
- Arch Gnome 3.38 w/ Wayland
- 1.17
- pacman
-  Google Pixel 4a (5G) (Android 12)

**Describe the bug**
scrcpy --window-width 1920   
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 fil...ed. 382.8 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Google Pixel 4a (5G) (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.3.4
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3067)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2147)
	... 9 more
WARN: Killing the server...

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment] 2021-02-19 13:39
Thank you for your report.

This is a duplicate of #2129.

**Closed by rom1v** 2021-02-19 13:39 UTC
