### ISSUE TITLE
unlock screen with keyboard

### ISSUE THREAD

**Issue by Pratched** [Genymobile/scrcpy#234] opened 2018-08-20 20:57 UTC
Hello, based on the issues posted here before this seems to be a simple one but if provided, I could not find any solution for this problem.

Is there a way to unlock the screen (lineageOS 14.1 on SGS4) with the keyboard without opening e.g. my lockscreen weather widget or the messenger app which is showing notifications on lockscreen?
When using `space` it usually is opening said apps. Using the mouse isnt optionally since "swiping" is working but not unlocking the screen.

Thanks in advance and thumbs up for this awesome and free tool!

**Comment by rom1v** [comment] 2018-08-21 09:33
> Using the mouse isnt optionally since "swiping" is working but *not unlocking the screen*.

It should, if you swipe fastly enough.

I don't know how to unlock with the keyboard.

**Comment by Zephyrien** [comment] 2018-08-29 12:48
Hello rom1v,
Maybe,  input keyevent 82 coule help

**Comment by Zero3K** [comment] 2020-03-01 19:44
Any news regarding this issue?

**Comment by rom1v** [comment] 2020-04-09 19:41
Closing as duplicate of #71.

**Closed by rom1v** 2020-04-09 19:41 UTC
Labels: question

**Comment by rom1v** [comment] 2020-06-04 08:36
> Maybe, input keyevent 82 coule help

Yes, so it's just `Ctrl`+`m` from scrcpy. :+1:
