### ISSUE TITLE
Scrcpy don't work with Redmi 9T

### ISSUE THREAD

**Issue by noless3011** [Genymobile/scrcpy#2569] opened 2021-08-17 15:12 UTC
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.18
 - installation method: I have tried every version
 - device model: redmi 9T
 - Android version: 10

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\Users\Admin\scoop\apps\scrcpy\1.18\scrcpy-server: 1 file pushed, 0 skipped. 58.3 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2010J19SG (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:237)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:90)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
WARN: Killing the server...
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment] 2021-08-17 15:14
Duplicate of #833.

**Closed by rom1v** 2021-08-17 15:14 UTC
