### ISSUE TITLE
Mac OS Monterey system, after a period of time will automatically crash "drawable must not be nil"

### ISSUE THREAD

**Issue by BaiMingxu** [Genymobile/scrcpy#2785] opened 2021-11-15 09:24 UTC
<img width="985" alt="截屏2021-11-15 下午5 20 31" src="https://user-images.githubusercontent.com/22886455/141755965-e6c95d90-c9f7-4195-a230-f0c120c43674.png">

**Comment by rom1v** [comment] 2021-11-15 09:31
> drawable must not be nil

Duplicate of #2698 and #2756.

**Closed by rom1v** 2021-11-15 09:31 UTC

**Comment by rom1v** [comment] 2021-11-15 09:33
It's an SDL bug: https://github.com/libsdl-org/SDL/issues/4863
