### ISSUE TITLE
32-bit scrcpy flagged as Malicious on Virus Total 25/60

### ISSUE THREAD

**Issue by wordeater** [Genymobile/scrcpy#1195] opened 2020-03-03 20:19 UTC
I downloaded the 32-bit version as a .zip file and after extracting it, my AV software immediately deleted scrcpy-noconsole.exe and scrcpy.exe.
I checked the SHA256 sum of the .zip on VirusTotal and 25 of 60 AV engines detect it as malicious.
https://www.virustotal.com/gui/file/0f4b3b063536b50a2df05dc42c760f9cc0093a9a26dbdf02d8232c74dab43480/detection

The 64-bit version doesn't trigger any AV detection at all.
https://www.virustotal.com/gui/file/57d34b6d16cfd9fe169bc37c4df58ebd256d05c1ea3febc63d9cb0a027ab47c9/detection

**Comment by rom1v** [comment] 2020-03-03 20:27
Thank you for the report.

This is a duplicate of #1102.

**Closed by rom1v** 2020-03-03 20:27 UTC

**Comment by rom1v** [comment] 2020-03-03 20:43
I removed the link to the 32 bits version from the README: c396758b4ed29cb4d4ad51e8bcdd1deecf5761d2
