### ISSUE TITLE
Green screen when starting from windows tablet mode

### ISSUE THREAD

**Issue by AnthonySimsJ** [Genymobile/scrcpy#2121] opened 2021-02-15 03:09 UTC
Running windows build, scrcpy 1.17, samsung S10

Starting scrcpy with windows in tablet mode causes a green display. Its still connected because interacting with the green screen still interacts with the phone. Starting scrcpy in non tablet mode, and then switching to tablet mode works normally, and is an adequate work around

**Comment by RndyP** [comment] 2021-02-15 16:23
FWIW I've got green screen trouble too. See my previous post. How are you starting scrcpy?? Command line? Shortcut? From your own custom app?

**Comment by rom1v** [comment] 2021-02-15 16:25
Does this problem also occur on older scrcpy versions?

**Comment by AnthonySimsJ** [comment] 2021-02-15 16:36
1.17 is the only version I've ever used. So I do not know

**Comment by AnthonySimsJ** [comment] 2021-02-15 16:41
@RndyP Green screen seems to be a common symptom of issues. I was more focused on tablet mode as a cause

@rom1v I have only used scrcpy 1.17, so I do not know. I could test it though.

**Comment by RndyP** [comment] 2021-02-15 17:04
We have 2 relate threads on this now. Yes I see green screen with maximized windows with 1.10.
@AnthonySimsJ How are you starting up scrcpy? Command line? Shortcut?

**Comment by rom1v** [comment] 2021-02-15 17:09
I'm closing as a duplicate of #2112.

**Closed by rom1v** 2021-02-15 17:09 UTC
