### ISSUE TITLE
Is Korean input typing is not working? 

### ISSUE THREAD

**Issue by seakgba** [Genymobile/scrcpy#1000] opened 2019-12-11 02:45 UTC
Hello, 
I'm using your program well in Korea.
but korean input typing is not working and
`crtl + shift + v` is not working
I'm looking for a issues and found solution (adbkeyboard.apk) install but is not working
English input typing is very well but korean input typing is working
I know korean is in ASCII 
I don't know what's wrong
Help me please
Thank you

**Comment by rom1v** [comment] 2019-12-11 06:45
> `crtl + shift + v` is not working

Did you paste manually in a text area on the device?

> I know korean is in ASCII

You mean, "not" in ASCII.

See #37.

**Comment by machel7** [comment] 2020-03-11 16:52
I have the similar problem with chinese input, when I input chinese, Warn occurs such as ''WARN: Could not inject char u+8212'', so  what can I do to cope it.

**Comment by rom1v** [comment] 2020-03-11 17:00
That's expected. Non-ASCII is not supported.

**Comment by rom1v** [comment] 2020-04-09 19:36
Closing as duplicate of #37.

**Closed by rom1v** 2020-04-09 19:36 UTC
Labels: keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:41
Please test #1426 (works on Android >= 7).

**Comment by mataiotes** [comment] 2024-02-15 09:24
working in gboard but just not working "Korean-English conversion key"

so
if you click conversion button in gboard and turn on Korean
can't type english
if you click conversion button in gboard and turn on English
can't type korean

not working conversion key
and manually click conversion in android key-window
