### ISSUE TITLE
CRITICAL: Could not create renderer: Couldn't find matching render driver

### ISSUE THREAD

**Issue by 1N3** [Genymobile/scrcpy#58] opened 2018-03-13 03:24 UTC
Getting the following error when running scrcpy on Kali 2.0 after following the install instructions and getting everything setup. I'm using an Android 6.0 Nexus 6P device..  Any ideas? 

```
# scrcpy 
358 KB/s (19038 bytes in 0.051s)
CRITICAL: Could not create renderer: Couldn't find matching render driver
ERROR: Could not open video stream
```

**Comment by rom1v** [comment] 2018-03-15 21:43
Probably a graphical driver issue on the computer.

**Comment by 1N3** [comment] 2018-03-16 15:49
I take it this won't work on a Kali 2.0 VM then?

**Comment by rom1v** [comment] 2018-03-16 19:10
No, it won't, and it's probably not a bug. :disappointed: 

So I'm closing.

**Closed by rom1v** 2018-03-16 19:10 UTC

**Comment by screenpanda** [comment] 2019-08-16 14:38
I am having similar issue starting scrcpy when I remotely login (using Mobaxterm) to an linux machine and starting scrcpy in a terminal. 
```
scrcpy
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
431 KB/s (22546 bytes in 0.051s)
CRITICAL: Could not create renderer: Couldn't find matching render driver
```

I experiemented with the modifying the index value from default -1 to 0,1,2 in the function SDL_CreateRenderer() call in screen.c source code.
The value _higher than 2_ has the following run time issue: _CRITICAL: Could not create renderer: index must be -1 or in the range of 0 - 2.
The index values _0, 1_ gives run time error _CRITICAL: Could not create renderer: GLX is not supported._ when scrcpy is executed.
The index value _2_ worked without giving any error.
```
Default:
screen->renderer = SDL_CreateRenderer(screen->window, -1,
                                          SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
Workaround:
screen->renderer = SDL_CreateRenderer(screen->window, 2,
                                          SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
```
										  
**After compiling with above modification, the scrcpy successfully emulated the android screen remotely without any issue**. 
_This was just a trail/error method, I did not go into details why this issue comes up._ in terms of SDL.

It would be great to get feedback if this workaround works on Kali2.0.

**Comment by wcypierre** [comment] 2020-03-29 19:09
For those using a Windows VM in Proxmox, even after compiling the code changes above I'm still getting the same error.

One possible way to get it working on Windows would be to use [VirtualGL](https://virtualgl.org/vgldoc/2_2_1/#hd004004) but didn't tried it

Currently settled with using Xubuntu instead

**Comment by screenpanda** [comment] 2020-04-01 17:33
I am using **Windows 10 physical** machine with **Mobxterm** installed on Windows machine. In the Mobaxterm the following setting is there, which has OpenGL acceleration as you mentioned.
![grafik](https://user-images.githubusercontent.com/54180404/78166774-9d627280-744d-11ea-8e5e-90b7d572ef66.png)

The remote login over ssh -X (X11 forwarding) the a Linux (Ubuntu machine). This worked when both Ubuntu was install on physical machine as well as a virtual machine. 

I did not test on Windows VM with Proxmox. Which tool did you use on Windows VM to login on the ubuntu machine?

**Comment by wcypierre** [comment] 2020-04-01 17:43
@screenpanda  are you asking me?

If yes, it is 
Proxmox VM -> Windows VM (Initial Solution)
Proxmox VM -> Ubuntu VM (Final Solution)

**Comment by Anry-Hu** [comment] 2020-04-11 07:32
> I am having similar issue starting scrcpy when I remotely login (using Mobaxterm) to an linux machine and starting scrcpy in a terminal.
> 
> ```
> scrcpy
> INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
> 431 KB/s (22546 bytes in 0.051s)
> CRITICAL: Could not create renderer: Couldn't find matching render driver
> ```
> 
> I experiemented with the modifying the index value from default -1 to 0,1,2 in the function SDL_CreateRenderer() call in screen.c source code.
> The value _higher than 2_ has the following run time issue: _CRITICAL: Could not create renderer: index must be -1 or in the range of 0 - 2._
> The index values _0, 1_ gives run time error _CRITICAL: Could not create renderer: GLX is not supported._ when scrcpy is executed.
> The index value _2_ worked without giving any error.
> 
> ```
> Default:
> screen->renderer = SDL_CreateRenderer(screen->window, -1,
>                                           SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
> Workaround:
> screen->renderer = SDL_CreateRenderer(screen->window, 2,
>                                           SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
> ```
> 
> **After compiling with above modification, the scrcpy successfully emulated the android screen remotely without any issue**.
> _This was just a trail/error method, I did not go into details why this issue comes up._ in terms of SDL.
> 
> It would be great to get feedback if this workaround works on Kali2.0.

I remotely login (using Mobaxterm) from windows7 to an linux machine and start scrcpy in a terminal.
![image](https://user-images.githubusercontent.com/28347656/79038140-8e2bb380-7c09-11ea-8c53-5423976a98e3.png)
Could you tell me how to fix up the bug.

**Comment by screenpanda** [comment] 2020-06-25 16:24
> 
> 
> > I am having similar issue starting scrcpy when I remotely login (using Mobaxterm) to an linux machine and starting scrcpy in a terminal.
> > ```
> > scrcpy
> > INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
> > 431 KB/s (22546 bytes in 0.051s)
> > CRITICAL: Could not create renderer: Couldn't find matching render driver
> > ```
> > 
> > 
> > I experiemented with the modifying the index value from default -1 to 0,1,2 in the function SDL_CreateRenderer() call in screen.c source code.
> > The value _higher than 2_ has the following run time issue: _CRITICAL: Could not create renderer: index must be -1 or in the range of 0 - 2._
> > The index values _0, 1_ gives run time error _CRITICAL: Could not create renderer: GLX is not supported._ when scrcpy is executed.
> > The index value _2_ worked without giving any error.
> > ```
> > Default:
> > screen->renderer = SDL_CreateRenderer(screen->window, -1,
> >                                           SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
> > Workaround:
> > screen->renderer = SDL_CreateRenderer(screen->window, 2,
> >                                           SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
> > ```
> > 
> > 
> > **After compiling with above modification, the scrcpy successfully emulated the android screen remotely without any issue**.
> > _This was just a trail/error method, I did not go into details why this issue comes up._ in terms of SDL.
> > It would be great to get feedback if this workaround works on Kali2.0.
> 
> I remotely login (using Mobaxterm) from windows7 to an linux machine and start scrcpy in a terminal.
> ![image](https://user-images.githubusercontent.com/28347656/79038140-8e2bb380-7c09-11ea-8c53-5423976a98e3.png)
> Could you tell me how to fix up the bug.

Did you modify the MobaXterm settign as shown above?

**Comment by somorastik** [comment] 2020-10-28 08:20
> > > I am having similar issue starting scrcpy when I remotely login (using Mobaxterm) to an linux machine and starting scrcpy in a terminal.
> > > ```
> > > scrcpy
> > > INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
> > > 431 KB/s (22546 bytes in 0.051s)
> > > CRITICAL: Could not create renderer: Couldn't find matching render driver
> > > ```
> > > 
> > > 
> > > I experiemented with the modifying the index value from default -1 to 0,1,2 in the function SDL_CreateRenderer() call in screen.c source code.
> > > The value _higher than 2_ has the following run time issue: _CRITICAL: Could not create renderer: index must be -1 or in the range of 0 - 2._
> > > The index values _0, 1_ gives run time error _CRITICAL: Could not create renderer: GLX is not supported._ when scrcpy is executed.
> > > The index value _2_ worked without giving any error.
> > > ```
> > > Default:
> > > screen->renderer = SDL_CreateRenderer(screen->window, -1,
> > >                                           SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
> > > Workaround:
> > > screen->renderer = SDL_CreateRenderer(screen->window, 2,
> > >                                           SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
> > > ```
> > > 
> > > 
> > > **After compiling with above modification, the scrcpy successfully emulated the android screen remotely without any issue**.
> > > _This was just a trail/error method, I did not go into details why this issue comes up._ in terms of SDL.
> > > It would be great to get feedback if this workaround works on Kali2.0.
> > 
> > 
> > I remotely login (using Mobaxterm) from windows7 to an linux machine and start scrcpy in a terminal.
> > ![image](https://user-images.githubusercontent.com/28347656/79038140-8e2bb380-7c09-11ea-8c53-5423976a98e3.png)
> > Could you tell me how to fix up the bug.
> 
> Did you modify the MobaXterm settign as shown above?

ScreenPanda can you provide the recompiled version please?

**Comment by nwrkbiz** [comment] 2020-12-17 15:25
I changed 

> screen->renderer = SDL_CreateRenderer(screen->window, -1,
>                                           SDL_RENDERER_ACCELERATED);

                                          
to

> screen->renderer = SDL_CreateRenderer(screen->window, -1,
>                                           SDL_RENDERER_SOFTWARE);

To make it work.

**Comment by rom1v** [comment] 2020-12-17 15:32
And you'll get poor quality too.

You could also just use `scrcpy --render-driver=software`.

But it's better to update or install working graphic drivers. See #111.

**Comment by nwrkbiz** [comment] 2020-12-17 15:43
> And you'll get poor quality too.
> 
> You could also just use `scrcpy --render-driver=software`.
> 
> But it's better to update or install working graphic drivers. See #111.

Aah, my bad, I should have read the help text in the first place

**Comment by screenpanda** [comment] 2021-03-16 20:42
The latest scrcpy tool version 15 , I did not see this issue and it worked without modification of the source code with default options.
The MobaXterm Configuration->OpenGL Acceleration set to "Software."
