### ISSUE TITLE
Request: on the window alone (not on device) allow to show touch indications made by the mouse

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#2437] opened 2021-06-29 20:28 UTC
- [ V] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have some flag that we can pass, that for whenever we use the mouse to simulate touches on the device, it will show like the touch indicator that we already have on Android.

**Describe alternatives you've considered**
We could use something like Carnec, which draws everywhere.

**Additional context**
I'm talking about this:

![image](https://user-images.githubusercontent.com/5357526/123862984-af251500-d931-11eb-96d1-30f6cad8b377.png)

**Comment by rom1v** [comment] 2021-06-30 00:22
Duplicate of your own issue #44 😄

**Comment by AndroidDeveloperLB** [comment] 2021-06-30 00:30
@rom1v Oh and I'm the one who created it...

**Closed** 2021-06-30 00:30 UTC
