### ISSUE TITLE
Is it possible to support Chinese input method

### ISSUE THREAD

**Issue by mybu** [Genymobile/scrcpy#778] opened 2019-09-03 03:44 UTC
Is it possible to support Chinese input method。

**Comment by lpful** [comment] 2019-09-19 15:36
@mybu You may try ARDC [https://www.cnblogs.com/we-hjb/p/9220084.html](url)

**Comment by lpful** [comment] 2019-09-22 02:42
![ARDC中文输入法](https://user-images.githubusercontent.com/50052327/65381516-ab5c6b80-dd25-11e9-83ab-c1cd4f07c3ae.gif)

**Comment by rom1v** [comment] 2019-09-30 13:05
Duplicate of #37 (and many others)

**Closed by rom1v** 2019-09-30 13:05 UTC
Labels: keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:39
Please test #1426 (works on Android >= 7).
