### ISSUE TITLE
Not working on Pixel 3 blueline Android 12 Developer beta 3

### ISSUE THREAD

**Issue by me-abhishekpal** [Genymobile/scrcpy#2293] opened 2021-05-03 18:37 UTC
**Environment**
 - OS: Windows
 - scrcpy version: scrcpy-win64-v1.17
 - installation method: windows release
 - device model: Pixel 3 Blueline
 - Android version: 12 beta 3

I am running scrcpy as usual, gives the following output:

```
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
C:\Users\mario\Downloads\scrcpy-win64-v1.17\scrcpy-server:... file pushed, 0 skipped. 50.4 MB/s (34930 bytes in 0.001s)
[server] INFO: Device: Google Pixel 3 (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
        at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3110)
        at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2193)
        ... 9 more
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2160
WARN: Device disconnected
WARN: Killing the server...
Press any key to continue . . .

```

Thanks in advance for getting the issue resolved.

**Comment by rom1v** [comment] 2021-05-03 18:54
Duplicate of #2129.

See https://github.com/Genymobile/scrcpy/issues/2129#issuecomment-826542365

**Closed** 2021-05-03 18:54 UTC
