### ISSUE TITLE
Scrcpy crash when pressing CTRL + O or turning off screen

### ISSUE THREAD

**Issue by Sberla996** [Genymobile/scrcpy#875] opened 2019-10-21 10:10 UTC
When turning off the phone screen while still using it with command CTRL + O scrcpy runs into an Exception.
I just updated my OnePlus 7 Pro to Android 10, it worked fine on Android 9, I'm on last version of scrcpy.

> INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
> C:\Users\HIDDEN: 1 file pushed. 2.7 MB/s (22546 bytes in 0.008s)
> INFO: Initial texture: 1440x3120
> [server] ERROR: Exception on thread Thread[Thread-1,5,main]
> java.lang.AssertionError: java.lang.reflect.InvocationTargetException
>         at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)
>         at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)
>         at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
>         at com.genymobile.scrcpy.Controller.control(Controller.java:73)
>         at com.genymobile.scrcpy.Server$1.run(Server.java:45)
>         at java.lang.Thread.run(Thread.java:919)
> Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)
>         ... 5 more
> Caused by: java.lang.IllegalArgumentException: displayToken must not be null
>         at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1523)
>         ... 7 more

**Comment by rom1v** [comment] 2019-10-21 10:18
Duplicate of #835. Already fixed on `dev` branch.

**Closed by rom1v** 2019-10-21 10:18 UTC
