### ISSUE TITLE
Meizu M6s display issue

### ISSUE THREAD

**Issue by Hippobotus** [Genymobile/scrcpy#1985] opened 2020-12-21 04:22 UTC
- [YES] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [YES] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: v1.14 onwards
 - installation method: Windows 64-bit zipped file
 - device model: Meizu M6s
 - Android version: Nougat 7.0

**Describe the bug**
Scrcpy cannot display the output when connected to Meizu M6s from v1.14 onwards.
For the record, version 1.13 works well

I tried the adb shell screenrecord command as suggested in other threads and it works on this phone.
Also tried these command-line options but to no avail.
```
scrcpy --render-driver=opengl
scrcpy -b2M -m1024
```

On errors, please provide the output of the console (and `adb logcat` if relevant).

These are the console outputs when running different version(s).
```v1.14\scrcpy-server:... file pushed, 0 skipped. 41.7 MB/s (33142 bytes in 0.001s)
[server] INFO: Device: Meizu Meizu M6s (Android 7.0)
INFO: Created renderer: direct3d
INFO: Renderer: direct3d
INFO: Initial texture: 720x1440
ERROR: SDL failed to get a vertex buffer for this Direct3D 9 rendering batch!
ERROR: Dropping back to a slower method.
ERROR: This might be a brief hiccup, but if performance is bad, this is probably why.
ERROR: This error will not be logged again for this renderer.
```
```
v1.15\scrcpy-server:... file pushed, 0 skipped. 44.0 MB/s (33618 bytes in 0.001s)
[server] INFO: Device: Meizu Meizu M6s (Android 7.0)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1440
```
```
v1.16\scrcpy-server:... file pushed, 0 skipped. 43.0 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: Meizu Meizu M6s (Android 7.0)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1440
```

[logcat0001.txt](https://github.com/Genymobile/scrcpy/files/5722255/logcat0001.txt)
[logcat0002.txt](https://github.com/Genymobile/scrcpy/files/5722253/logcat0002.txt)

Please find attached the logcat files. Hope these information help in figuring out a solution.

Thank you.

**Comment by rom1v** [comment] 2020-12-21 07:50
Could you follow these steps to help resolving this specific issue, please? https://github.com/Genymobile/scrcpy/issues/240#issuecomment-703829170

**Comment by Hippobotus** [comment] 2020-12-21 10:04
I tried the linked binaries and again the console window appears but not the UI window.

```v1.16\scrcpy-server:... file pushed, 0 skipped. 55.6 MB/s (33870 bytes in 0.001s)
[server] INFO: Device: Meizu Meizu M6s (Android 7.0)
[server] INFO: ### 1
[server] INFO: ### 2
INFO: Renderer: direct3d
INFO: Initial texture: 720x1440
```

[logcat0003.txt](https://github.com/Genymobile/scrcpy/files/5723642/logcat0003.txt)

Here is the logcat for your reference.

Thank you.

**Comment by rom1v** [comment] 2020-12-21 16:19
Thank you for the test.

The commit introducing the "regression" is 62c0c1321feec0a673329cb6771efeefb6dc9657. 
The problem is that I can't revert it, since it fixes other issues.

This should work for your device: <details><summary>diff</summary>

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
index c7c104e4..b723cf32 100644
--- a/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
+++ b/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java
@@ -55,17 +55,8 @@ public class ScreenEncoder implements Device.RotationListener {
 
     public void streamScreen(Device device, FileDescriptor fd) throws IOException {
         Workarounds.prepareMainLooper();
-
-        try {
-            internalStreamScreen(device, fd);
-        } catch (NullPointerException e) {
-            // Retry with workarounds enabled:
-            // <https://github.com/Genymobile/scrcpy/issues/365>
-            // <https://github.com/Genymobile/scrcpy/issues/940>
-            Ln.d("Applying workarounds to avoid NullPointerException");
-            Workarounds.fillAppInfo();
-            internalStreamScreen(device, fd);
-        }
+        Workarounds.fillAppInfo();
+        internalStreamScreen(device, fd);
     }
 
     private void internalStreamScreen(Device device, FileDescriptor fd) throws IOException {
```

</details>

If you are comfortable with editing and building, could you try removing the `Workarounds.prepareMainLooper()` call, or call only parts of `Workarounds.fillAppInfo()`?

> Here is the logcat for your reference.

Thank you, but like others with that device, the logcat is broken (it only prints the ~500 first lines).

**Comment by Hippobotus** [comment] 2020-12-22 06:14
> If you are comfortable with editing and building, could you try removing the Workarounds.prepareMainLooper() call, or call only parts of Workarounds.fillAppInfo()?

Unfortunately I am not familiar with programming. In this case, I can make a separate folder for scrcpy v1.13 and use it to connect to this Meizu phone only.


> Thank you, but like others with that device, the logcat is broken (it only prints the ~500 first lines).

Is there any way to fix the logcat?

Thank you.

**Closed** 2020-12-26 03:36 UTC

**Comment by HEZI0427** [comment] 2021-07-28 09:25
this issue not like problem on oppo device(cause NPE error): https://github.com/Genymobile/scrcpy/issues/921
Meizu device you need set Looper.prepare() and check by Looper.myLooper(), this is code work for me ( Too urgly!!!)。
``` java
-        if (Looper.getMainLooper() != null) {
-            return;
+        if (Build.BRAND.toLowerCase().contains("meizu")) {
+            if (Looper.myLooper() != null) {
+                return;
+            }
+            Looper.prepare();
+        } else {
+            if (Looper.getMainLooper() != null) {
+                return;
+            }
+            Looper.prepareMainLooper();
         }
-        Looper.prepareMainLooper();
     }
```

**Comment by rom1v** [comment] 2021-08-12 16:08
@HEZI0427 Thank you for the details.

But scrcpy just calls `Looper.prepareMainLooper();` unconditionally, where does this diff apply?

On meizu, is scrcpy stuck in `Looper.prepareMainLooper();` or somewhere else?

**Comment by rom1v** [comment] 2021-09-10 10:14
@HEZI0427 ?
