### ISSUE TITLE
Some issues with virtual display

### ISSUE THREAD

**Issue by kcd-shichen** [Genymobile/scrcpy#5538] opened 2024-11-26 01:56 UTC
## Environment

 - **OS:** [ Windows11 ]
 - **Scrcpy version:** [ 3.0 ]
 - **Installation method:** [ Windows release ]
 - **Device model:** [ Redmi Note 12T Pro ]

## Describe the bug

The new virtual display is great, but with a few bugs.

When I press ``` Alt + P ``` to turn off the screen(beacuse ``` Alt + O ```doesn't work), the virtual display becomes uncontrollable on the computer(still be displayed), while in mirror mode, I can continue to operate on the computer after turning off the screen on the phone, is this a bug?

**Comment by rom1v** [comment] 2024-11-26 06:41
Duplicate of #5530.

Please test https://github.com/Genymobile/scrcpy/issues/5530#issuecomment-2499781497

**Closed by rom1v** 2024-11-26 06:41 UTC
