### ISSUE TITLE
Make android device feel the application as second screen

### ISSUE THREAD

**Issue by MohamedElshafey** [Genymobile/scrcpy#740] opened 2019-08-21 14:34 UTC
Question: How can i make my android device feel that it's mirroring so it can feel the screen attached like Mirroring by Smart View for example, that's because i want to use [Presentation](https://developer.android.com/reference/android/app/Presentation) to show something different on the second screen, is that possible ?

**Comment by tchangeme** [comment] 2019-08-24 05:49
同样想知道是否支持

**Comment by gxj8885718** [comment] 2019-09-16 11:50
plus one!

**Comment by rom1v** [comment] 2019-09-30 12:50
IIUC, duplicate of #397?

**Comment by MohamedElshafey** [comment] 2019-10-02 12:44
@rom1v yes it's the same issue

**Closed** 2019-10-02 12:44 UTC
Labels: feature request
