### ISSUE TITLE
Switch off screen not working

### ISSUE THREAD

**Issue by srevinsaju** [Genymobile/scrcpy#611] opened 2019-06-22 08:38 UTC
For my [guiscrcPy](https://github.com/srevinsaju/guiscrcpy) project, I tried to use switch off screen option, and I get the info on terminal that is screen is switched off, but unfortunately, the screen instead of being switched off, it is rather freezing. That I can put the flag or use the shortcut, but at that moment it freezes the screen on the mobile, but screen mirroring works fine.

**Comment by rom1v** [comment] 2019-06-23 21:07
What if you just pass `-S` to scrcpy (without `guiscrcPy`)? It is the same behavior?

**Comment by srevinsaju** [comment] 2019-06-24 03:54
Yea, I did. I even used the shortcut manually. The screen freezes. but mobile display doesn't turn off. I even get the log message, device screen turned off. After device power on and off, everything resets.

**Comment by rom1v** [comment] 2019-06-25 06:59
Weird, your device seems to react to `setPowerMode()` oddly. What device is it?

When you turn screen off, what does `adb logcat` says?

**Comment by srevinsaju** [comment] 2019-06-25 11:54
The mobile is GT-N7100 (Samsung Galaxy Note 2) running a nougat custom ROM [AICP](https://github.com/AICP). The logcat is attached below. I found scrcpy giving instructions. 
[log.txt](https://github.com/Genymobile/scrcpy/files/3325085/log.txt)

**Comment by rom1v** [comment] 2019-06-25 12:17
>     SurfaceFlinger: Set power mode=0, type=0 flinger=0x40832000

Seems correct.

The problem should probably be reported on AICP. They might have more information about the issue.

**Comment by srevinsaju** [comment] 2019-06-25 12:19
I will check this with another ROM and close this issue if it works. thanks for your time.

**Comment by himie** [comment] 2019-07-10 23:30
I'm having the exact same issue with a Pixel 3 XL Running Android Q (both beta4 and beta5) the screen doesn't turn off and the scrcpy window stops sending input. Phone screen still works fine and I can still see mirroring there's just no input from scrcpy.

Works fine on my Pixel 2 with android9 pie so not sure if it's the device itself or issue caused by Q beta.

**Comment by srevinsaju** [comment] 2019-07-11 05:32
I tried on Havoc OS too on Galaxy Note 2, Pie (9.0), but still this option doesn't work

Faithfully Yours

Srevin Saju
https://srevinsaju.wixsite.com/srevinsaju

________________________________

**Comment by rom1v** [comment] 2019-07-11 07:40
> I'm having the exact same issue with a Pixel 3 XL Running Android Q (both beta4 and beta5) the screen doesn't turn off and the scrcpy window stops sending input

This is a separate issue specific to Android Q beta, which is already fixed on `master`: #586 #587.

**Comment by 4nizizio** [comment] 2019-07-14 00:42
i'm using an custom rom as well and my screen just freeze, i can use touch and scrcpy inputs as well, my phone is a J320M using lineage-14.1-20190204-UNOFFICIAL-j3xlte or just a J3 2016 with lineageOS 14.1

**Comment by Afsar-Pasha** [comment] 2019-07-23 19:50
Having same issue, but there is an option in Engineering Mode to turn off LCM which works fine, but turning off LCD doesn't work.

**Comment by rom1v** [comment] 2019-10-17 21:27
Please check on `dev` branch (after commit c33a147fd0e9fbd3a5add6f0190eea909d74c26d). See #835

**Comment by srevinsaju** [comment] 2019-10-18 17:38
Fixed

**Closed** 2019-10-18 17:38 UTC
Labels: screenoff
