### ISSUE TITLE
Audio when mic is open

### ISSUE THREAD

**Issue by KacanggSoyaa** [Genymobile/scrcpy#5551] opened 2024-11-27 18:13 UTC
Hi 
I want to ask about why when I put my earphone on my device the sound will not capture in the scrcpy. Its same when I Open my mic on my device when I were playing game.
Sorry for my bad english btw

**Comment by rom1v** [comment] 2024-11-27 18:20
Duplicate of #4084 #4087.

**Closed by rom1v** 2024-11-27 18:20 UTC
