### ISSUE TITLE
Server is missing .jar extension

### ISSUE THREAD

**Issue by mauriciofelippe** [Genymobile/scrcpy#963] opened 2019-11-29 07:52 UTC
Version 1.11 Win64 Bit is not working, i think it is because of the extension. and throw the error < scrcpy-server: 1 file pushed. 1.9 MB/s (25454 bytes in 0.013s)
Aborted >

**Comment by rom1v** [comment] 2019-11-29 08:00
Hi,

Thank you for your report.

This is a duplicate of #944.

The extension has been removed by: https://github.com/Genymobile/scrcpy/commit/3da95b52bd21ae0f4d81ee933caea63b78191deb

It has been restored only for the server-side by: 
https://github.com/Genymobile/scrcpy/commit/83ace842809034f8076296a338c017e49519f068

Binaries are available here: https://github.com/Genymobile/scrcpy/issues/944#issuecomment-557550516

**Closed by rom1v** 2019-11-29 08:00 UTC
