### ISSUE TITLE
The camera cannot be used in IQOO 11S

### ISSUE THREAD

**Issue by hionwi** [Genymobile/scrcpy#4883] opened 2024-04-23 15:57 UTC
- [ x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] Windows 11
 - scrcpy version: [e.g. 1.12.1] 2.4
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] Windows release
 - device model: IQOO 11S
 - Android version: [e.g. 10] 14

**Describe the bug**

scrcpy --video-source=camera can not used

```
[server] INFO: Device: [vivo] vivo V2304A (Android 14)
INFO: Renderer: direct3d
[server] INFO: Using camera '0'
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
        at android.os.Parcel.createException(Parcel.java:3055)
        at android.os.Parcel.readException(Parcel.java:3038)
        at android.os.Parcel.readException(Parcel.java:2980)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6593)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:8254)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3771)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2560)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:3106)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3351)
        at android.provider.Settings$Global.getStringForUser(Settings.java:17197)
        at android.provider.Settings$Global.getString(Settings.java:17171)
        at android.hardware.camera2.vivo_ext.VivoCameraUtils.sendOpenCloseCameraBroadcast(VivoCameraUtils.java:146)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:844)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1142)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1164)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:954)
        at com.genymobile.scrcpy.CameraCapture.openCamera(CameraCapture.java:241)
        at com.genymobile.scrcpy.CameraCapture.init(CameraCapture.java:86)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:55)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1042)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:184)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7766)
        at android.app.IActivityManager$Stub.onTransact$getContentProvider$(IActivityManager.java:12451)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3220)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3221)
```

**Comment by rom1v** [comment] 2024-04-23 16:27
Duplicate of #4639

**Closed by rom1v** 2024-04-23 16:27 UTC
