### ISSUE TITLE
MacOS Ctrl key not working from computer

### ISSUE THREAD

**Issue by xuancong84** [Genymobile/scrcpy#1378] opened 2020-05-11 02:07 UTC
It is great that from a connected computer, we can type text directly into Mobile phone. however, since I use Termux console, I realize that certain keys such as Ctrl/Alt are not working. 

<img width="434" alt="image" src="https://user-images.githubusercontent.com/10172392/81517951-14552a00-936f-11ea-800b-e1cdd3b1d7c9.png">

Nevertheless, the on-screen Ctrl key is working (as shown in the picture) and Home/End also working, so it has to be scrcpy issue.

**Comment by rom1v** [comment] 2020-05-11 02:11
Thank you for your report.

Yes, I need to implement a solution for this.

I'm closing as duplicate of #555.

**Closed by rom1v** 2020-05-11 02:11 UTC
