### ISSUE TITLE
Output Audio to both Phone and PC?

### ISSUE THREAD

**Issue by ixobelle** [Genymobile/scrcpy#4388] opened 2023-10-30 23:47 UTC
- [ x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

Possible to output audio on both PC and Phone?

I record my phone on OBS, and while the sound being output to the PC is great to actually record the sound, I'd love to be able to turn down my PC speakers and actually just listen to the phone itself. It can output video in both locations, I can't see how to also do audio in both places.

**Comment by rom1v** [comment] 2023-10-31 08:38
Duplicate of #3875.

**Closed by rom1v** 2023-10-31 08:38 UTC

**Comment by kaustubrrrrr** [comment] 2024-03-16 04:22
how can you say duplicate of #3875 mr, @rom1v ... you have to find solution to solve this problem as DouWan easily manages it
