### ISSUE TITLE
can't see the icones with -s

### ISSUE THREAD

**Issue by AmikadM** [Genymobile/scrcpy#3314] opened 2022-06-06 13:38 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11]
 - scrcpy version: [e.g. 1.24]
 - installation method: [Windows release]
 - device model: Xiaomi Redmi 9t
 - Android version: [11]
 - MIUI version: 12.5.11 global

when I use the -S option, I can't see the icons on the home screen (I can sill click on them blindly)
picture of my home screen 
![image](https://user-images.githubusercontent.com/77983171/172168613-25afe14e-846c-4be6-a4e2-7b55c8af11e3.png)

**Comment by rom1v** [comment] 2022-06-06 13:42
Duplicate of #1301.

**Closed by rom1v** 2022-06-06 13:42 UTC
