### ISSUE TITLE
On screen control

### ISSUE THREAD

**Issue by abph1** [Genymobile/scrcpy#1278] opened 2020-04-08 23:16 UTC
I do not get to see the physical control buttons for my Samsung Galaxy S7. I am using a second phone to remotely control the phone on which SCRCPY is running and using keyboard shortcuts is really cumbersome if not downright unmanageable. Can you please implement on-screen Back, Home, and App Switch buttons? Thanks!

**Comment by rom1v** [comment] 2020-04-08 23:48
Duplicate of #7.

**Closed by rom1v** 2020-04-08 23:48 UTC
