### ISSUE TITLE
Command lines for keyboard shortcuts

### ISSUE THREAD

**Issue by zcohn1** [Genymobile/scrcpy#1361] opened 2020-05-07 09:34 UTC
Is there somewhere I can find how to execute actions such as clipboard copying via commands in the cmd prompt, instead of via keyboard shortcuts? I would like to write a short batch file to automate the copying process, but I would need the command lines to execute.

**Comment by rom1v** [comment] 2020-05-07 09:41
No, this is currently not possible.

I'm closing as duplicate of #399 (I guess).

**Closed by rom1v** 2020-05-07 09:41 UTC
