### ISSUE TITLE
Google chrome 

### ISSUE THREAD

**Issue by lollol567681** [Genymobile/scrcpy#3231] opened 2022-04-30 19:30 UTC
I’m having an issue using scrcpy where I’m unable to use Google chrome Whilst I have ‘turn-screen-off’ function and I have to take it out in order to use google chrome but others Ik don’t have that issue

**Comment by rom1v** [comment] 2022-04-30 19:32
Duplicate of #836.

**Closed by rom1v** 2022-04-30 19:32 UTC
