### ISSUE TITLE
Use scrcpy with phone screen off

### ISSUE THREAD

**Issue by Shinkiro1** [Genymobile/scrcpy#440] opened 2019-02-28 16:11 UTC
scrcpy is awesome, much better performance than SideSync, but the one feature I miss is being able to mirror the device on my computer while the real physical phone screen is turned off.  I can't help but feel that I'm shortening the lifespan of the device by keeping the screen on all day every day.  Is there any way to do this with scrcpy, or, can the feature be added?

**Comment by rom1v** [comment] 2019-02-28 16:14
Currently, there is no technical solution.

Duplicate of https://github.com/Genymobile/scrcpy/issues/175.

**Closed by rom1v** 2019-02-28 16:14 UTC

**Comment by rom1v** [comment] 2019-05-31 21:15
Implemented on `dev` by 12a3bb25d39037931f577dc0165b3e517aad92df.
