### ISSUE TITLE
Audio is not recorded when I use bluetooth earphones

### ISSUE THREAD

**Issue by saikumar9121** [Genymobile/scrcpy#4190] opened 2023-07-25 10:47 UTC
Environment

OS: Windows
scrcpy version: 2.1.1
installation method: Windows release
device model: mi 11x
Android version: 13

While recording the phone screen without using my bluetooth earphones the recorded file includes both video and the audio. But while using bluetooth earphones in my phone the recorded file includes only video, the audio is not captured while I use bluetooth earphones with my phone. any solution

**Comment by rom1v** [comment] 2023-10-14 19:16
Duplicate of https://github.com/Genymobile/scrcpy/issues/4083

**Closed by rom1v** 2023-10-14 19:16 UTC
