### ISSUE TITLE
[FEAT] Audio only feature

### ISSUE THREAD

**Issue by Velosofy** [Genymobile/scrcpy#3945] opened 2023-04-23 18:25 UTC
- [X] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Please create a mode for audio only, no video. As video only is possible, why not Audio only?

**Describe the solution you'd like**
An audio only mode, where I can use USB/ADB to passthrough my audio coming from my phone, to the computer its plugged in.

**Describe alternatives you've considered**
I've use `sndcpy` for audio only before.

**Comment by rom1v** [comment] 2023-04-23 20:22
It's planned.

Duplicate of #3842.

**Closed by rom1v** 2023-04-23 20:22 UTC

**Comment by rom1v** [comment] 2023-05-07 11:22
Please test #3978.
