### ISSUE TITLE
Question: is there any function to disable keys to scrcpy's text input

### ISSUE THREAD

**Issue by srevinsaju** [Genymobile/scrcpy#910] opened 2019-11-05 18:17 UTC
I would like to know if I could disable keys like NumKeys to assign certain keyboard commands to specific points on the screen. This is in reference to guiscrcpy's beta branch mapper.py, for keyboard mapping. If it is not possible, I should use the Alt modifier.
Thanks in advance

_Sent from my Galaxy Note2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rom1v** [comment] 2020-05-25 19:29
Duplicate of #712.

**Closed by rom1v** 2020-05-25 19:29 UTC
Labels: question
