### ISSUE TITLE
can't type Arabic using scrcpy 

### ISSUE THREAD

**Issue by ZeinabBahaa** [Genymobile/scrcpy#2430] opened 2021-06-27 12:00 UTC
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows]
 - scrcpy version: [scrcpy v1.18]
 - installation method: [Windows release]
 - device model: Xiaomi Mi A1
 - Android version: [ 10]

**Describe the bug**
After connecting phone and controlling it by computer by scrcpy
I opened Messenger app and started writing a message
The message was in Arabic
But letters that were written were in English
I tried to change language and it didn't work 

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
G:\scrcpy\scrcpy-server: 1 file pushed...ped. 25.2 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi Mi A1 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0633
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0633
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0628
[server] WARN: Could not inject char u+064a
[server] WARN: Could not inject char u+0628
[server] WARN: Could not inject char u+0643
```

Please paste terminal output in a code block.
```
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
G:\scrcpy\scrcpy-server: 1 file pushed...ped. 25.2 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Xiaomi Mi A1 (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0633
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0633
[server] WARN: Could not inject char u+0634
[server] WARN: Could not inject char u+0628
[server] WARN: Could not inject char u+064a
[server] WARN: Could not inject char u+0628
[server] WARN: Could not inject char u+0643
```

**Comment by rom1v** [comment] 2021-06-28 06:45
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

Duplicate of #37.

**Closed by rom1v** 2021-06-28 06:45 UTC

**Comment by ahmedragab202** [comment] 2025-04-12 14:05
its been 4 years but i just started using scrcpy and i found the solution , you need to add --keyboard=uhid to your scrcpy line so the phone recognizes the keyboard as a usb/physical keyboard , and then setup your languages and add arabic , switching languages shortcut is ctrl+space and it works flowlessly 

so if you are running basic code it should be like 
scrcpy --keyboard=uhid

**Comment by MostafaAb1** [comment] 2025-04-16 20:32
> its been 4 years but i just started using scrcpy and i found the solution , you need to add --keyboard=uhid to your scrcpy line so the phone recognizes the keyboard as a usb/physical keyboard , and then setup your languages and add arabic , switching languages shortcut is ctrl+space and it works flowlessly
> 
> so if you are running basic code it should be like scrcpy --keyboard=uhid

bro you are a legend

**Comment by Hazem560** [comment] 2025-05-07 16:12
i have the same issue , and i can't solve it
any one can contact me to assist ?

**Comment by Hazem560** [comment] 2025-05-07 16:38
> i have the same issue , and i can't solve it any one can contact me to assist ?

@ahmedragab202

**Comment by ahmedragab202** [comment] 2025-08-22 17:49
> > i have the same issue , and i can't solve it any one can contact me to assist ?
> 
> [@ahmedragab202](https://github.com/ahmedragab202)

sorry i havent seen your email , contact me on telegran , discord or instagram / search for eng4r or eng4r2

**Comment by ahmedragab202** [comment] 2025-08-22 17:50
> > i have the same issue , and i can't solve it any one can contact me to assist ?
> 
> [@ahmedragab202](https://github.com/ahmedragab202)

or email me at ahmed_family2012@yahoo.com and mention scrcpy
