### ISSUE TITLE
连接后显示手机分辨率黑屏无画面

### ISSUE THREAD

**Issue by Tu-maimes** [Genymobile/scrcpy#677] opened 2019-08-01 02:01 UTC
魅族手机

**Comment by Tu-maimes** [comment] 2019-08-01 02:01
1

**Comment by Tu-maimes** [comment] 2019-08-01 02:58
1

**Comment by rom1v** [comment] 2019-08-01 07:14
In English, please.

**Comment by npes87184** [comment] 2019-08-01 07:59
Same as #240.

**Comment by Tu-maimes** [comment] 2019-08-01 08:35
D:\scrcpy\scrcpy-win64\scrcpy-server.jar: 1 file pushed. 1.1 MB/s (22470 bytes in 0.020s)
INFO: Initial texture: 1080x1920

After running, only the above contents will be displayed。Without other Windows。the phone's screen lights up as it runs。Meizu phone

**Comment by rom1v** [comment] 2019-08-01 22:46
Thank you for the translation :wink:

So I'm closing as duplicate of #240.

**Closed by rom1v** 2019-08-01 22:46 UTC
