### ISSUE TITLE
Stream phone camera

### ISSUE THREAD

**Issue by mjg** [Genymobile/scrcpy#1298] opened 2020-04-18 15:33 UTC
scrcpy is grrreat and could have one more killer feature:
stream the phones camera picture

I know there is droidcam and IP webcam and such. But: Using scrcpy and having the camera app open gives much better results (less lag) than these and is more versatile. I see two possible ways to perfect this:
- Have a camera app with "clean screen" (no UI elements) that you share directly with scrcpy as is.
- Enhance scrcpy to build in camera capture.

I know #467 sounds similar, but in fact they are complementary: #467 is about transforming the stream on the computer into a video soure (v4l or such) while this here is about having the phone's camera as the stream input. Both could work together well.

**Comment by rom1v** [comment] 2020-04-18 15:48
:+1: (but duplicate of #241)

**Closed by rom1v** 2020-04-18 15:48 UTC
