### ISSUE TITLE
Xiaomi M2101K6G (Android 12) Null

### ISSUE THREAD

**Issue by Nightly26** [Genymobile/scrcpy#3244] opened 2022-05-04 12:32 UTC
I started to connect using these parameters:

C:\Users\koczo\Desktop\scrcpy-win64-v1.23>scrcpy.exe -m 1500

The mirrored screen briefly appears and closes instantly.
These are from CMD tracelogs.

scrcpy 1.23 <https://github.com/Genymobile/scrcpy>
C:\Users\koczo\Desktop\scrcpy-win64-v1.23\scrcpy-server: 1 file pushed, 0 skipped. 28.8 MB/s (41123 bytes in 0.001s)
[server] INFO: Device: Xiaomi M2101K6G (Android 12)
INFO: Renderer: direct3d
INFO: Initial texture: 672x1496
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

**Comment by rom1v** [comment] 2022-05-04 12:33
Duplicate of #3051. This is a bug in MIUI 13.

**Closed by rom1v** 2022-05-04 12:33 UTC
