### ISSUE TITLE
Got a warning while setting up the JAR server

### ISSUE THREAD

**Issue by caiodev** [Genymobile/scrcpy#458] opened 2019-03-17 01:18 UTC
WARNING: Custom target input '.' can't be converted to File object(s).
This will become a hard error in the future.

DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.

and later

WARNING: Duplicate name in Manifest: Manifest-Version.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
mar 16, 2019 10:20:12 PM java.util.jar.Attributes read

WARNING: Duplicate name in Manifest: Built-By.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
mar 16, 2019 10:20:12 PM java.util.jar.Attributes read

WARNING: Duplicate name in Manifest: Created-By.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.

**Comment by rom1v** [comment] 2019-03-17 20:24
Thank you for your report

> DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.

Duplicate of #202. I have no good solution. See https://github.com/Genymobile/scrcpy/issues/202#issuecomment-427955805. Reference to the meson issue: https://github.com/mesonbuild/meson/issues/3824.

> WARNING: Duplicate name in Manifest: Manifest-Version.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
mar 16, 2019 10:20:12 PM java.util.jar.Attributes read

This is when _meson_ attempts to read/modify the jar file while it should not. I reported the problem here: https://github.com/mesonbuild/meson/issues/4844

**Comment by caiodev** [comment] 2019-03-18 13:05
Got it. Thanks for the quick reply @rom1v

**Closed** 2019-03-22 00:16 UTC
Labels: build
