### ISSUE TITLE
Mac. Second Display. Mouse stop working.

### ISSUE THREAD

**Issue by halxinate** [Genymobile/scrcpy#282] opened 2018-10-01 21:58 UTC
When the app is dragged to the second (external) display on the Mac Book Pro (MOS 10.13.6) all of the mouse events over any Android controls seems to stop register on the phone. Keyboard shortcuts and window control mouse events still work fine.

**Comment by sshock** [comment] 2018-10-02 04:49
I ran into this today as well.  After dragging scrcpy to a second monitor the mouse events no longer work properly.  I don't think they are completely ignored; it's more like the mouse is in the wrong place, perhaps as if the screen were invisibly rotated sideways.

**Comment by sshock** [comment] 2018-10-02 05:00
related to #245 maybe?

**Comment by halxinate** [comment] 2018-10-26 18:44
Yeah. It looks like, as on mouse taps I can also see the scrcpy window jumping a pixel up sometimes.

One more note, but could be just a wild guess. My virtual screen is ABOVE the main workspace. I.e. When I move the scrcpy screen from the laptop screen to the external display I'm crossing the top border of the former to have it appear from the bottom of the latter. Could be the missing case or something.

**Comment by halxinate** [comment] 2018-10-26 18:52
Just experimented by moving the scrcpy window into the top left corner of the secondary screen and enabled the taps and cursor tracking in dev options. It's clearly showing that there is a scaling issue as well as origin issue (I can see the trail synchronized with the mouse motions, but it's scaled and offsetted).

**Comment by rom1v** [comment] 2020-04-09 19:49
Closing as duplicate of #15.

**Closed by rom1v** 2020-04-09 19:49 UTC
Labels: hidpi, input events, macos
