### ISSUE TITLE
utf-8 is not supported

### ISSUE THREAD

**Issue by YehudaEi** [Genymobile/scrcpy#1428] opened 2020-05-25 08:09 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.13
 - installation method: Windows release 1.13
 - device model: A0001 (One Plus)
 - Android version: 9

**Describe the bug**
I can't write in Hebrew.
**As I stated above, I was already looking for the issue but the copy and paste solution didn't work for me.**
It just paste spaces.

I would love if you can fix it in the following versions

```
[server] INFO: Device: OnePlus A0001 (Android 9)
INFO: Renderer: direct3d
WARN: Trilinear filtering disabled (not an OpenGL renderer)
INFO: Initial texture: 1080x1920
[server] WARN: Could not inject char u+05d0
[server] WARN: Could not inject char u+05d1
[server] WARN: Could not inject char u+05d2
[server] WARN: Could not inject char u+05d3
[server] WARN: Could not inject char u+05d4
[server] WARN: Could not inject char u+05d5
[server] WARN: Could not inject char u+05d6
[server] WARN: Could not inject char u+05d7
[server] WARN: Could not inject char u+05d8
[server] WARN: Could not inject char u+05d9
[server] WARN: Could not inject char u+05db
[server] WARN: Could not inject char u+05dc
[server] WARN: Could not inject char u+05de
[server] WARN: Could not inject char u+05e0
[server] WARN: Could not inject char u+05e1
[server] WARN: Could not inject char u+05e2
[server] WARN: Could not inject char u+05e4
[server] WARN: Could not inject char u+05e6
[server] WARN: Could not inject char u+05e7
[server] WARN: Could not inject char u+05e8
[server] WARN: Could not inject char u+05e9
[server] WARN: Could not inject char u+05ea
```
![image](https://user-images.githubusercontent.com/32451776/82791861-2b1f7480-9e77-11ea-91a3-028de698aea1.png)

**Comment by rom1v** [comment] 2020-05-25 08:11
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
Duplicate of #37.

Also see #1426.

**Closed by rom1v** 2020-05-25 08:11 UTC
