### ISSUE TITLE
version: 1.13  When the window is maximized, click Restore cannot display the correct size

### ISSUE THREAD

**Issue by chenwc520** [Genymobile/scrcpy#1346] opened 2020-05-02 03:01 UTC
**Environment**
 - OS: win10 64
 - scrcpy version: 1.13
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: 7.0

**Describe the bug**
When the window is maximized, click Restore cannot display the correct size

**Comment by rom1v** [comment] 2020-05-02 07:01
What is your expected correct size? What is the size you get?

You specified version 1.13 in the title: is the behavior different from v1.12?

**Comment by fahadbw** [comment] 2020-05-05 21:38
Same issue

My original size 1280x720 then change the size to 800x600. If I did maximize then restore down or fullscreen then unfullscreen its back to original size 1280x720.

1.12 doent have this issue, while 1.13 does.

**Comment by rom1v** [comment] 2020-05-05 23:25
Thank you for your report.

Fixed by ead7ee4a03c9533ea7bb992a9c2df6ec757fd1f0.

Here is a build for Windows so that you can test (replace in your scrcpy v1.13 directory):

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/issue1346/1/scrcpy.exe)
  _SHA256: 3e64189d03fa26f920d31e002d3d6b751ed495ef46319dce45be3e3b2d46f28a_
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/issue1346/1/scrcpy-server)
  _SHA256: 84707914eab0a0e47f1532ee585a95ac29b5368951e7b0362610f9949bf3e685_

**Closed by rom1v** 2020-05-05 23:25 UTC
Labels: resize

**Comment by AndroidDeveloperLB** [comment] 2020-05-20 08:21
@rom1v When replacing those files, Windows warns about opening scrcpy.exe, and when trying to run  scrcpy-noconsole.exe , it doesn't do anything.
Any way to call scrcpy.exe without console, instead of using scrcpy-noconsole.exe?

:(

**Comment by rom1v** [comment] 2020-05-20 08:22
> When replacing those files, Windows warns about opening scrcpy.exe

Which warnings?

**Comment by rom1v** [comment] 2020-05-20 08:26
> Any way to call scrcpy.exe without console, instead of using scrcpy-noconsole.exe?

The "no console" thing is Windows specific, and changes the way the binary is linked:
https://github.com/Genymobile/scrcpy/blob/82446b6b0db284e9f9a125cd3e4785586f6845f3/app/meson.build#L135-L139

So it cannot be switched by a command-line argument.

**Comment by AndroidDeveloperLB** [comment] 2020-05-20 08:30
I closed the warning. It's the normal warning of running an EXE file. Here, I replaced and launched it again:

![image](https://user-images.githubusercontent.com/5357526/82423997-39434e80-9a8d-11ea-981a-9f18de7439e1.png)

I don't remember it appeared last time I extracted and launched the tool. Odd.

As for no-console, too bad. No workaround then?

**Comment by rom1v** [comment] 2020-05-20 08:57
Oh that's expected I guess when you run a new binary. Just click "Run anyway".

**Comment by AndroidDeveloperLB** [comment] 2020-05-20 09:00
Sure. No reason to stop trusting the same one that I used before :)

**Comment by hcet14** [comment] 2020-05-20 11:53
scrcpy.exe
SHA256: 3e64189d03fa26f920d31e002d3d6b751ed495ef46319dce45be3e3b2d46f28a
scrcpy-server
SHA256: 84707914eab0a0e47f1532ee585a95ac29b5368951e7b0362610f9949bf3e685

I couldn't reproduce the error. Thank you!
