### ISSUE TITLE
Touch is not sensitive

### ISSUE THREAD

**Issue by AnswerZhao** [Genymobile/scrcpy#361] opened 2018-12-01 03:49 UTC
On Mac with Android Pie, the touch is not sensitive and sometimes the click is invalid.

**Comment by AnswerZhao** [comment] 2018-12-01 04:05
I found the rule of the problem. It works fine on the Original display, but not ok on the External display.

**Comment by rom1v** [comment] 2018-12-01 06:56
Duplicate of https://github.com/Genymobile/scrcpy/issues/15: clicks do not occur at the right location due to hidpi.

This bug is maybe solved in [SDL 2.0.9](https://github.com/Genymobile/scrcpy/issues/15#issuecomment-437667745) by commit [`metal: Fix high dpi and resizing on macOS, and clean up iOS code. Fixes bug #4250.`](https://hg.libsdl.org/SDL/rev/758d4e1222a7?revcount=460), but nobody tested yet.

SDL 2.0.9 is not packaged in homebrew yet (see https://github.com/Homebrew/homebrew-core/pull/33781).

**Closed** 2018-12-01 06:57 UTC
Labels: hidpi, input events, macos
