### ISSUE TITLE
The Swedish letter å can not be entered

### ISSUE THREAD

**Issue by sherpashrapnel** [Genymobile/scrcpy#1427] opened 2020-05-25 08:08 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu Studio 20.04
 - scrcpy version: 1.12.1
 - installation method: apt
 - device model: Sony Xperia XA2 / Thinkpad T460s
 - Android version: Android 10 (LineageOS 17.1)

**Describe the bug**
The swedish alphabet has three characters that English does not have, å ä ö. I can input ä and ö but not å. When pressing the character å (right of the p-key on a Swedish keyboard) the letter å is not printed and the output in the terminal is the following:

```
[server] WARN: Could not inject char u+00e5
```

**Comment by rom1v** [comment] 2020-05-25 08:11
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work
Duplicate of #37.

Also see #1426.

**Closed by rom1v** 2020-05-25 08:11 UTC
