### ISSUE TITLE
Lagging everywhere in galaxy A70

### ISSUE THREAD

**Issue by Weldon-Percy** [Genymobile/scrcpy#1353] opened 2020-05-04 05:35 UTC
Hello there developer. 1st thank you for the amazing product, 2nd I'm experiencing hellish lagging everywhere with my galaxy A70. It's screen is broken (not sure if that's the issue), and the frame rate is maximum 11-12 fps. tried reducing resolution, bit rate, recorded screen, but to no avail. I hope you have any idea, as every other phone is smooth except that one, plus it used to work flawlessly in smart view (before breaking the screen), so not sure what's the issue.

**Comment by rom1v** [comment] 2020-05-04 08:42
Might be related to the broken screen: #1285.

How does screenrecord behave?

```
adb shell screenrecord /sdcard/file.mp4
adb pull /sdcard/file.mp4
```
?

**Comment by Weldon-Percy** [comment] 2020-05-04 10:19
well, scrcpy didn't really respond to your command "adb shell screenrecord /sdcard/file.mp4", it just kept the window empty as it was without actually recording. I tried this command from the code section of the software "scrcpy --record file.mp4", and it was recording, but the lag persists. about the section of the broken phone, restarting my phone and lowering resolution/bitrate didn't help at all. I'm afraid that all it is because of the screen, because I just discovered your software inorder NOT to repair the screen, really expensive.

**Comment by rom1v** [comment] 2020-05-04 10:21
> well, scrcpy didn't really respond to your command "adb shell screenrecord /sdcard/file.mp4", it just kept the window empty as it was without actually recording

This is not related to scrcpy, it's totally independant.

Open a terminal, and execute `adb shell screenrecord /sdcard/file.mp4`.

**Comment by Weldon-Percy** [comment] 2020-05-04 10:24
oh I see the regular cmd, but it says "access denied" and I don't know why :(

**Comment by Weldon-Percy** [comment] 2020-05-04 13:19
do you have any idea on how to bypass that and let the command happen?

**Comment by rom1v** [comment] 2020-05-04 13:23
https://stackoverflow.com/questions/33691258/permission-denied-for-adb-shell-command

**Comment by Weldon-Percy** [comment] 2020-05-04 13:25
still access is denied

**Comment by rom1v** [comment] 2020-05-04 13:28
Then I don't know. I've never encounter that issue.

**Comment by Weldon-Percy** [comment] 2020-05-04 13:32
srsly... I had high hopes when I discovered your software, guess I'm the only one here who gets left out unsolved..

**Comment by Weldon-Percy** [comment] 2020-05-04 13:47
At least tell me why access is denied. I am the admin and I didn't do anything to block such access. What other things can I do to go around it? is recording from scrcpy the same as recording from cmd? Please at least I want to know the real issue.. I'm not an expert with codes but you are, so I'm in a real need for your ideas.

**Comment by Weldon-Percy** [comment] 2020-05-04 14:34
Okay thank you for solving the access problem. now I can type in the command but nothing happens, no response. What's the matter now?

**Comment by rom1v** [comment] 2020-05-04 14:35
> At least tell me why access is denied.

I don't know. This is a problem not related to scrcpy, I don't know everything. `screenrecord` is a native program used to record your screen in a file on the device, available on Android devices. If it does not work on your device for some reason, then you need to find why.

> is recording from scrcpy the same as recording from cmd?

No, scrcpy is a separate program, it captures the screen and encode using `MediaCodec`, transmit the video stream to the computer which muxes and saves it into a file.

You encounter lag issues, so to determine why, I asked you to test with an alternative (the easiest is `screenrecord`). If `screenrecord` also lags, then the problem is on your device. If `screenrecord` does not work for some reason, and I don't have the answer, then search on stackoverflow or somewhere.

**Comment by rom1v** [comment] 2020-05-04 14:36
> Okay thank you for solving the access problem. now I can type in the command but nothing happens, no response. What's the matter now?

Ctrl+C to interrupt, then `adb pull /sdcard/file.mp4` to retrieve the file on your computer, and play it.

**Comment by Weldon-Percy** [comment] 2020-05-04 14:48
ohhh wait so that records the screen without mirroring it.. I thought I needed to wait for the mirror popup to actually start the recording.. yeahh now I see the issue, it's not from scrcpy, it's from the phone. I'm really sorry for that attitude, but I was really panicking about the lag (still kinda, but at least I know it's from the software), and I didn't understand what was going on. Do you have any idea why would the phone become laggy if the screen is broken? I'm grateful that you helped me narrow the issue

**Comment by Weldon-Percy** [comment] 2020-05-04 15:04
also, I don't know if you will understand my question right now, but does the mouse used in scrcpy act as screen touches so that the phone becomes very slow due to the damaged digitizer? or the mouse is just separated from the actual screen function of the phone? I mean, is the mouse recognized as "finger taps" or just an internal feature to navigate the phone? If you got my point..

**Comment by Weldon-Percy** [comment] 2020-05-04 15:15
maybe the mouse feature on scrcpy is what making it slow perhaps.. Is there option to disable controlling the screen? just mirroring?

**Comment by Weldon-Percy** [comment] 2020-05-04 16:51
does the screen being unresponsive cause lagging?

**Comment by rom1v** [comment] 2020-05-04 19:38
> Do you have any idea why would the phone become laggy if the screen is broken?

No, but when hardware is broken, it can impact the software :)

> it's not from scrcpy, it's from the phone.

OK, I'm closing this issue, then. Good luck.

**Closed by rom1v** 2020-05-04 19:38 UTC
