### ISSUE TITLE
Bring back old Copy / Paste system

### ISSUE THREAD

**Issue by NekoGryphou** [Genymobile/scrcpy#1771] opened 2020-09-18 13:01 UTC
The new **copy / paste** system is not ergonomic at all .
I'd much rather paste text in "letter by letter input" mode when I press `ctrl + v` rather than having to do `alt + shit + v`.
And when I do `alt + v`, it pastes the text from the clipboard which is not necessarily the one I want to put.

If i rebind the `mod `key to `ctrl `instead of `alt`, it's a real messe with **copy / paste** too.

Can you add an option to get back to the old behavior; I use this application all day long and it's getting complicated now and I'm losing time due to errors related to **copy / paste**.

Thanks you

**Comment by rom1v** [comment] 2020-09-18 13:08
> And when I do `alt + v`, it pastes the text from the clipboard which is not necessarily the one I want to put.

The content pasted by with <kbd>Alt</kbd>+<kbd>v</kbd> should be the same as the one pasted with <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd> (and the same as the one pasted with <kbd>Ctrl</kbd>+<kbd>v</kbd>).

If this is not the case, then probably `device.setClipboardText(text)` does not work on your device ROM, see #1750 (possibly because your device is rooted #1678?).

Which Android version, which Android ROM? Did you try with another device?

**Comment by NekoGryphou** [comment] 2020-09-18 13:33
I've got an Samsung Galaxy S9+ and Android 10 samsung rom.
Not rooted.

But, why did you change `ctrl + v` to `alt + v` ?

**Comment by rom1v** [comment] 2020-09-18 13:36
> But, why did you change `ctrl + v` to `alt + v` ?

To forward the <kbd>Ctrl</kbd> key to the device.

See [v1.15 highlights](https://github.com/Genymobile/scrcpy/releases/tag/v1.15) and #1598 for more details.
The new expected behavior is as described in the README: https://github.com/Genymobile/scrcpy#copy-paste

**Comment by NekoGryphou** [comment] 2020-09-18 13:38
When i hit `ctrl + v` or `alt + v`, it sync the computer clipboard to the device OR if there is something in the smartphone's clipboard, it pastes it and synchronizes after pasting the old text...

**Comment by rom1v** [comment] 2020-09-18 13:39
Oh, wait, do you use v1.16?

Because there was a bug in v1.15: https://github.com/Genymobile/scrcpy/issues/1658

**Comment by NekoGryphou** [comment] 2020-09-18 13:44
Yes, i use the v1.16 version

**Comment by rom1v** [comment] 2020-09-18 13:46
> When i hit `ctrl + v` or `alt + v`, it sync the computer clipboard to the device OR if there is something in the smartphone's clipboard, it pastes it and synchronizes after pasting the old text...

OK, so IIUC the second time, it correctly paste the expected content, right?

**Comment by NekoGryphou** [comment] 2020-09-18 14:09
Here's a video example : https://streamable.com/r1k9nc

**Comment by rom1v** [comment] 2020-09-18 14:22
OK, thank you for the video. :+1:

So it seems that `device.setClipboardText(text)` does something on the device (we see the content in the clipboard on your device), but is not pasted, neither with <kbd>Ctrl</kbd>+<kbd>v</kbd> nor <kbd>Alt</kbd>+<kbd>v</kbd> (unless the content is initially copied from the device).

You could also test `adb shell input keyevent PASTE` manually to paste, I guess you will have the same problem.

I think it's the very same issue as #1750.

I would say this is a device bug: once the content is in the clipboard (as shown above the device keyboard), injecting `PASTE` or pressing <kbd>Ctrl</kbd>+<kbd>v</kbd> should paste it.

Could you capture the logcat content when you press <kbd>Ctrl</kbd>+<kbd>v</kbd> in the scrcpy window for the first time (with a new random content, different from the previous one), please?

Start _scrcpy_ and from a new terminal, execute:
```bash
adb logcat -c  # clear
# copy some text and press Ctrl+v in the scrcpy window
adb logcat -d > logcat.txt
```

**Comment by NekoGryphou** [comment] 2020-09-18 14:32
When i do `adb shell input keyevent PASTE`,  it paste the older clipboard element, not the new one.
Github upload it's a bit buggy today, so here,s a link to the logcat.txt content : https://hastebin.com/umayuhecax.txt

**Comment by NekoGryphou** [comment] 2020-09-18 14:36
Maybe it's a bug with Google Keyboard, but before the v1.16, things work perfectly with the "letter by letter paste" (`alt + shift + v` now)

**Comment by rom1v** [comment] 2020-09-18 14:40
> When i do `adb shell input keyevent PASTE`, it paste the older clipboard element, not the new one.

OK, so it suggests a device bug (or intended restriction).

The method scrcpy uses to set the clipboard is "public" (usable by any app): [`ClipboardManager.setPrimaryClip()`](https://developer.android.com/reference/android/content/ClipboardManager#setPrimaryClip(android.content.ClipData)).

I'm interested to know if you set the text from some app using this API and try to paste with `adb shell input keyevent PASTE`. This would allow to reproduce the problem without scrcpy.

There are probably some simple "clipboard manager" apps which allows to explicitly set some text in the clipboard using this.

**Comment by NekoGryphou** [comment] 2020-09-18 14:44
I test with https://play.google.com/store/apps/details?id=devdnua.clipboard and it work when i paste the clipboard content

**Comment by rom1v** [comment] 2020-09-18 14:53
> I test with https://play.google.com/store/apps/details?id=devdnua.clipboard and it work when i paste the clipboard content 
:confused:

**Comment by rom1v** [comment] 2020-09-18 16:28
I wrote a minimal scrcpy-like sample application to get and set the clipboard.

Download [`clipboard.dex`](https://tmp.rom1v.com/scrcpy/1771/1/clipboard.dex)
_SHA256: 3c7205c58c26f4ed42feda56ce3c312b13b5ff11c980817bccdc5882f629fed2_

Then push it to the device:
```bash
adb push clipboard.dex /data/local/tmp/
```

Then, you can execute:
```bash
# get the current clipboard text
adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard get
# set the clipboard text
adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set abcdefgh
```

Please try to set the clipboard, check the result by reading the current content.
Then focus some text field on Android, and execute `adb shell input keyevent PASTE` to inject it.

What is the behavior?

<details>
<summary>source code</summary>

```java
import android.content.ClipData;
import android.os.Build;
import android.os.IBinder;
import android.os.IInterface;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class Clipboard {

    private static final String PACKAGE_NAME = "com.android.shell";
    private static final int USER_ID = 0;

    private static Method getPrimaryClipMethod;
    private static Method setPrimaryClipMethod;
    private static boolean legacySet;

    private static IInterface getService(String service, String type) {
        try {
            Method getServiceMethod = Class.forName("android.os.ServiceManager").getDeclaredMethod("getService", String.class);
            IBinder binder = (IBinder) getServiceMethod.invoke(null, service);
            Method asInterfaceMethod = Class.forName(type + "$Stub").getMethod("asInterface", IBinder.class);
            return (IInterface) asInterfaceMethod.invoke(null, binder);
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    private static IInterface getClipboardManager() {
        return getService("clipboard", "android.content.IClipboard");
    }

    private static Method getGetPrimaryClipMethod(IInterface manager) throws NoSuchMethodException {
        if (getPrimaryClipMethod == null) {
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                getPrimaryClipMethod = manager.getClass().getMethod("getPrimaryClip", String.class);
            } else {
                getPrimaryClipMethod = manager.getClass().getMethod("getPrimaryClip", String.class, int.class);
            }
        }
        return getPrimaryClipMethod;
    }

    private static Method getSetPrimaryClipMethod(IInterface manager) throws NoSuchMethodException {
        if (setPrimaryClipMethod == null) {
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                setPrimaryClipMethod = manager.getClass().getMethod("setPrimaryClip", ClipData.class, String.class);
            } else {
                setPrimaryClipMethod = manager.getClass().getMethod("setPrimaryClip", ClipData.class, String.class, int.class);
            }
        }
        return setPrimaryClipMethod;
    }

    private static ClipData getPrimaryClip(Method method, IInterface manager) throws InvocationTargetException, IllegalAccessException {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
            return (ClipData) method.invoke(manager, PACKAGE_NAME);
        }
        return (ClipData) method.invoke(manager, PACKAGE_NAME, USER_ID);
    }

    private static void setPrimaryClip(Method method, IInterface manager, ClipData clipData)
            throws InvocationTargetException, IllegalAccessException {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
            method.invoke(manager, clipData, PACKAGE_NAME);
        } else {
            method.invoke(manager, clipData, PACKAGE_NAME, USER_ID);
        }
    }

    public static CharSequence getText(IInterface manager) {
        try {
            Method method = getGetPrimaryClipMethod(manager);
            ClipData clipData = getPrimaryClip(method, manager);
            if (clipData == null || clipData.getItemCount() == 0) {
                return null;
            }
            return clipData.getItemAt(0).getText();
        } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
            System.err.println("Could not invoke method");
            return null;
        }
    }

    public static boolean setText(IInterface manager, CharSequence text) {
        try {
            Method method = getSetPrimaryClipMethod(manager);
            ClipData clipData = ClipData.newPlainText(null, text);
            setPrimaryClip(method, manager, clipData);
            return true;
        } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
            System.err.println("Could not invoke method");
            return false;
        }
    }

    private static void syntax() {
        System.err.println("Syntax: adb shell CLASSPATH=/data/local/tmp/clipboard app_process / Clipboard [options]");
        System.err.println("options:");
        System.err.println("    get");
        System.err.println("    set 'SOME TEXT'");
        System.exit(1);
    }

    private static void error() {
        syntax();
        System.exit(1);
    }

    private static CharSequence getClipboard() {
        IInterface manager = getClipboardManager();
        return getText(manager);
    }

    public static boolean setClipboard(CharSequence text) {
        IInterface manager = getClipboardManager();
        return setText(manager, text);
    }

    public static void main(String... args) throws Exception {
        if (args.length == 0) {
            error();
        }
        if ("get".equals(args[0])) {
            if (args.length != 1) {
                error();
            }
            System.out.println("get: " + getClipboard());
        } else if ("set".equals(args[0])) {
            if (args.length != 2) {
                error();
            }
            String text = args[1];
            if (setClipboard(text)) {
                System.out.println("set: " + text);
            } else {
                System.err.println("set error");
            }
        } else {
            error();
        }
    }
}
```

Compile with:
```bash
javac -source 1.7 -target 1.7 Clipboard.java -cp "$ANDROID_HOME"/platforms/android-30/android.jar
~/android/sdk/build-tools/30.0.0/dx --dex --output clipboard.dex Clipboard.class
```
</details>

**Comment by rom1v** [comment] 2020-09-20 12:35
Did you have some time to test?

**Comment by NekoGryphou** [comment] 2020-09-21 07:11
Sorry, i've been a bit busy this week-end.
I just tested your application and the clipboard doesn't work.

CMD : 
![cmd](https://i.ibb.co/hFrwCrp/Capture-d-cran-2020-09-21-090734.png)

Device after `PASTE` event :
![device](https://i.ibb.co/D5zS2pm/Smart-Select-20200921-090801-Keep-Notes.jpg)


Otherwise, can you tell me how to remove the `.dex` file from my phone ?

**Comment by rom1v** [comment] 2020-09-21 07:18
OK, thank you for the test :+1:

> Otherwise, can you tell me how to remove the .dex file from my phone ?

```
adb shell rm /data/local/tmp/clipboard.dex
```

**Comment by NekoGryphou** [comment] 2020-09-21 07:19
> adb shell rm /data/local/tmp/clipboard.dex
Thanks 👍

**Comment by NekoGryphou** [comment] 2020-09-30 11:49
Any news about a potential patch? :3

**Comment by rom1v** [comment] 2020-09-30 12:12
No, the test confirms that your device does not behave as expected. I don't have a solution for this. 😞

**Comment by NekoGryphou** [comment] 2020-10-01 08:05
oh :c

**Comment by gmiwoj** [comment] 2020-10-02 16:17
seconded.
i'm still on 1.14 because of this. copy pasta works perfectly on 1.14 and is pretty much unusable for me on 1.16

pls bring it back or at lest make it an option

**Comment by rom1v** [comment] 2020-10-02 16:34
Could you confirm that the issue only occurs with paste, not copy (if you press <kbd>Ctrl</kbd>+<kbd>i</kbd> on the device, could you paste it on the computer?

**Comment by hoanngothanh** [comment] 2020-10-05 04:04
> Could you confirm that the issue only occurs with _paste_, but that _copy_ works correctly: if you select a text then press Ctrl+c on the device (in the scrcpy window), could you paste it on the computer?

Hi rom1v
I can confirm when I copy from scrcpy window I can paste it to PC. But copy from pc then pastes to scrcpy have issue. I'm using the latest version of scrcpy

**Comment by rom1v** [comment] 2020-10-06 19:35
I've just implemented an option on a separate branch ([`legacy_paste`](https://github.com/Genymobile/scrcpy/commit/legacy_paste)):

```
scrcpy --legacy-paste
```

Could you please test it?

For windows users, take both `scrcpy.exe` and `scrcpy-server`, and replace them in your scrcpy v1.16 release.

For other platforms, take `scrcpy-server` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) only the client.

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1771/2/scrcpy.exe)
  _SHA256: 38b541d7cef76d424a72316faae02a9e8f78c021cb5d0d60721d701c43bafd13_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1771/2/scrcpy-server)
  _SHA256: 467beb2762d822766ccf76fc7bd47cd3950293d21eab041c62b0b5bd279039c1_

**Comment by rom1v** [comment] 2020-10-12 08:26
Could you please test? I'm interested in knowing if it solves your problem.

**Comment by NekoGryphou** [comment] 2020-10-12 14:34
It paste "letter by letter" now

**Comment by rom1v** [comment] 2020-10-12 14:40
Yes, that's the workaround if the device `PASTE` does not behave as expected. :+1:

**Comment by NekoGryphou** [comment] 2020-10-12 15:28
it's better than a buggy thing ^^
Thanks !

**Comment by atscripter** [comment] 2020-10-14 21:13
@rom1v Tested, working. Thank you.

**Comment by atscripter** [comment] 2020-10-14 22:51
Can we get one for scrcpy-noconsole.exe too? :)

**Comment by NekoGryphou** [comment] 2020-11-05 15:15
Any new version planned with this ?

**Comment by rom1v** [comment] 2020-11-07 14:22
`--legacy-paste` option merged in `dev`: d5f059c7cbef7d13889086670716d9f33f805dc4

**Closed by rom1v** 2020-11-07 14:22 UTC
Labels: bug, copy_paste

**Comment by XeonG** [comment] 2021-01-17 18:25
Also having this problem with pasting not working... I did try the legacy paste argument on the cmd line which works.. but its buggy it just leaves out characters, and doesn't even paste the whole clipboard from there pc.

copy works fine.. just not pasting from the pc, Samsung note9

is there any solution to this.. I'd be fine with legacy paste if it actually pasted all the characters from the clipboard.

**Comment by rom1v** [comment] 2024-09-16 13:45
This is not specific to this command, make tests with `adb shell echo`. There are two levels of shell interpretation:
 - your local shell (and it does not behave the same way on Linux or Windows)
 - the Android shell

Something like this should work:

```command
$ adb shell echo "first\\\nsecond"
first
second
$ adb shell echo "first$'\n'second"
first
second
```

**Comment by scruel** [comment] 2024-09-16 13:48
> This is not specific to this command, make tests with `adb shell echo`. There are two levels of shell interpretation:
> 
>     * your local shell (and it does not behave the same way on Linux or Windows)
> 
>     * the Android shell
> 
> 
> Something like this should work:
> 
> ```shell
> $ adb shell echo "first\\\nsecond"
> first
> second
> $ adb shell echo "first$'\n'second"
> first
> second
> ```

Thanks!
The following won't work,
```
PS > adb shell echo "first\\\nsecond"
first
second
PS > adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set "first\\\nsecond"
set: first\nsecond
```

but the following works
```
adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set "first$'\n'second"
```

**Comment by rom1v** [comment] 2024-09-16 13:51
> ```
> PS > adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set "first\\\nsecond"
> set: first\nsecond
> ```

Oh, sure, the `\n` was interpreted by `echo` (a third level of parsing).

> but the following works
> 
> ```
> adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set "first$'\n'second"
> ```

:+1: (`$'\n` is expanded by the shell before passing the value to the program)

**Comment by scruel** [comment] 2024-09-16 13:56
> > ```
> > PS > adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set "first\\\nsecond"
> > set: first\nsecond
> > ```
> 
> Oh, sure, it works with `echo` because the `\n` was interpreted by `echo` (a third level of parsing).
> 
> > but the following works
> > ```
> > adb shell CLASSPATH=/data/local/tmp/clipboard.dex app_process / Clipboard set "first$'\n'second"
> > ```
> 
> 👍 (`$'\n` is expanded by the shell before passing the value to the program)

I think we may modify the script to generate a new dex file, change:
`String text = args[1]`
to
`String text = args[1].replace('\\\n', '\n')`
