### ISSUE TITLE
Improvede detection and compatibility with Wear OS smartwatches

### ISSUE THREAD

**Issue by superbonaci** [Genymobile/scrcpy#2613] opened 2021-09-04 20:30 UTC
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

````
scrcpy -s 192.168.1.44:5555
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
C:\ProgramData\chocolatey\lib\scrcpy\tools\scrcpy-server: 1 file pushed, 0 skipped. 24.6 MB/s (37330 bytes in 0.001s)
[server] INFO: Device: Mobvoi TicWatch Pro 3 GPS (Android 9)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1811)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:180)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:78)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:61)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:255)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
ERROR: Could not retrieve device information
````

**Comment by rom1v** [comment] 2021-09-04 20:40
Most smartwatches don't have any hardware H.264 encoder, so it can't work.

**Comment by rom1v** [comment] 2021-09-04 20:41
Duplicate of #82.

**Closed by rom1v** 2021-09-04 20:41 UTC

**Comment by superbonaci** [comment] 2021-09-04 20:47
I guess you can capture screenshots every 0.2 seconds or something...
