### ISSUE TITLE
Maximized window get smaller when screen is rotated.

### ISSUE THREAD

**Issue by roshsoftco** [Genymobile/scrcpy#750] opened 2019-08-26 14:30 UTC
When the window is maximized, and if the android device rotates, the window becomes smaller and gets fixed in the top left corner of the screen.

Windows 7 Ultimate Service pack 1
Android 7.1.2
Connection: USB

![Untitled-1](https://user-images.githubusercontent.com/23375478/63698143-ddb89d00-c83b-11e9-8ba5-caed4294d0c0.jpg)

**Comment by rom1v** [comment] 2019-08-26 15:15
When you rotate, it computes the target size, then make it fit inside the display, with some margins (as it does when you start _scrcpy_), keeping its (top-left) position unchanged.

In that case, it's clearly not ideal, but I'm not sure what is the expected behavior.

**Comment by roshsoftco** [comment] 2019-08-26 18:24
My expected behaviour is that it would automatically maximize the screen once again after resizing if it's been maximized before rotating the screen.

**Comment by rom1v** [comment] 2019-08-26 18:53
Oh, it was maximized! Sorry, I missed that part :)

**Comment by rom1v** [comment] 2019-08-26 18:55
(btw, just for info, instead of maximizing, you could switch to fullscreen with Ctrl+f. I say that because I see people just maximizing while they would prefer fullscreen.)

**Comment by roshsoftco** [comment] 2019-09-09 06:25
Issue doesn't appear in fullscreen mode (`Ctrl`+`f`). Problem exists only when the window is maximized.

**Comment by rom1v** [comment] 2019-11-11 20:50
Fixed on branch `maximized.2`.

Needs more testing (help welcome), then I'll merge it into `dev`.

**Closed** 2019-11-12 18:53 UTC
Labels: bug

**Comment by vbuterin2** [comment] 2021-05-13 18:03
use lock video --lock-video-orientation=1
