### ISSUE TITLE
As of V. 3.0, Mod-O shortcut not working on Pixel 8 Pro on Android 15

### ISSUE THREAD

**Issue by Lpptrex** [Genymobile/scrcpy#5565] opened 2024-11-29 14:56 UTC
_Please read the [prerequisites] to run scrcpy._

[prerequisites]: https://github.com/Genymobile/scrcpy#prerequisites

_Also read the [FAQ] and check if your [issue][issues] already exists._

[FAQ]: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md
[issues]: https://github.com/Genymobile/scrcpy/issues

## Environment

 - **OS:** Windows 11
 - **Scrcpy version:** 3.0
 - **Installation method:** Windows release 
 - **Device model:** Pixel 8 Pro 
 - **Android version:** 15 BP11.241025.006
## Describe the bug

When using the Mod-O shortcut, the phone screen does not turn off. This happens since the update to version 3.0.

```
Please paste terminal output in a code block.
```
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.hardware.display.DisplayManagerGlobal.requestDisplayPower [int, boolean]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.DisplayManager.getRequestDisplayPowerMethod(DisplayManager.java:169)
        at com.genymobile.scrcpy.wrappers.DisplayManager.requestDisplayPower(DisplayManager.java:177)
        at com.genymobile.scrcpy.device.Device.setDisplayPower(Device.java:131)
        at com.genymobile.scrcpy.control.Controller.setDisplayPower(Controller.java:694)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:285)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:194)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:202)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by rom1v** [comment] 2024-11-29 15:03
> Android version: 15 BP11.241025.006

This is a change in non-released source code: https://github.com/Genymobile/scrcpy/issues/5530#issuecomment-2499117932

Anyway, the method to turn the screen off on Android 15 does not work as expected, and has been reverted: 3d1f036c04412e17a694e6a0b857b7f9e9217ab3.

You can try this binary which includes the fix: https://github.com/Genymobile/scrcpy/issues/5530#issuecomment-2500492821

Closing as ~duplicate of #5530.

**Closed by rom1v** 2024-11-29 15:03 UTC
