### ISSUE TITLE
Feature to mirror only a specific app and ignore other apps and overlay.

### ISSUE THREAD

**Issue by deeomnom** [Genymobile/scrcpy#2360] opened 2021-06-06 12:43 UTC
- Sir i have searched whole internet but could not find any screen recorder or mirroring app which can only mirror a specific app which i mention 
 - for e.g- i want to mirror only "com.chrome.browser" without any overlay and background apps getting caught in mirroring 
 - just like obs where what we want only shows rest is ignored.

Is this possible or can you help me find any screen recorder which does this thing.

**Comment by rom1v** [comment] 2021-06-06 13:19
Duplicate of #1887.

**Closed by rom1v** 2021-06-06 13:19 UTC
