### ISSUE TITLE
About audio copying

### ISSUE THREAD

**Issue by shadowqcom** [Genymobile/scrcpy#4777] opened 2024-03-21 17:24 UTC
**Describe the solution you'd like**
When I connect my computer, I need both the computer and the mobile phone to play audio at the same time, which means only copying the audio from the phone to the computer instead of capturing it.

**Comment by rom1v** [comment] 2024-03-21 17:44
Duplicate of #3875.

**Closed by rom1v** 2024-03-21 17:44 UTC
