### ISSUE TITLE
Cant start scrcpy error 

### ISSUE THREAD

**Issue by superh1k** [Genymobile/scrcpy#1064] opened 2020-01-06 15:46 UTC
Hi, below is paste from my cmd.
USB debugging is on.

```
λ scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
C:\Users\Dot\Downloads\scrcpy-win64-v1.12.1\scrcpy-server: 1 file pushed. 1.9 MB/s (26202 bytes in 0.013s)
INFO: Initial texture: 1080x2280
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:92)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
Press any key to continue...
```

**Comment by rom1v** [comment] 2020-01-06 15:48
Thank you for your report.

This is a duplicate of #465.

https://github.com/Genymobile/scrcpy/issues/465#issuecomment-551718851

**Closed by rom1v** 2020-01-06 15:48 UTC
