### ISSUE TITLE
shortcut to save the current frame as JPG/PNG

### ISSUE THREAD

**Issue by dedosmedia** [Genymobile/scrcpy#765] opened 2019-08-29 15:10 UTC
It would be nice to have a shortcut to save the current frame as a JPG/PNG on local computer.
Is it possible?

**Comment by srevinsaju** [comment] 2019-08-29 15:12
+1

**Comment by rom1v** [comment] 2019-08-29 15:14
Duplicate of #684

**Closed by rom1v** 2019-08-29 15:14 UTC

**Comment by dedosmedia** [comment] 2019-08-29 15:20
I know there exists  adb exec-out screencap -p > file.png


But I am starting scrcpy with --crop option, and I need just to save exactly what I watching in scrcpy window... screencap will save the entire screen.

**Comment by rom1v** [comment] 2019-08-29 15:28
> I need just to save exactly what I watching in scrcpy window

If you save what you are watching directly (a frame from the video stream), you'll get a compressed frame (with artifacts from H.264). (As a workaround, you could record the video and extract screenshots afterwards, e.g. with VLC, but it's not as convenient.)

Another possibility is to request a lossless screenshot on the device (possibly cropped). But it seems there is no acceptable technical solution for now (#684).

**Comment by dedosmedia** [comment] 2019-08-29 15:35
Thanks so much... I understand.
Thanks so much for your time and effort! What a great tool.

**Comment by vincespice** [comment] 2021-05-17 11:51
Can you help me to solve this? I'd be grateful for.
