### ISSUE TITLE
Can you support PC typing to mobile phone in Chinese?

### ISSUE THREAD

**Issue by DavidWhom** [Genymobile/scrcpy#632] opened 2019-07-04 05:01 UTC
Suddenly there was an idea. Our company's computers can't use entertainment software，however I need to chat with my family member and friends sometimes. VPN does't work on our company‘s network. Your project may help me...

**Comment by rom1v** [comment] 2019-07-04 06:12
See #37 and #557.

Note that since v1.9, you can "synchronize clipboards" from computer to device, while preserving UTF-8.

So if you select chinese characters on your computer, press `Ctrl`+`c`, go to the scrcpy window, press `Ctrl`+`Shift`+`v`, you can then "paste" on Android (long-press on a textbox, then click "paste").

**Comment by lpful** [comment] 2019-07-07 15:30
@DavidWhom You may try ARDC.https://www.cnblogs.com/we-hjb/p/9220084.html
[https://images2018.cnblogs.com/blog/37056/201806/37056-20180624121532219-527114242.gif](url)

**Comment by DavidWhom** [comment] 2019-07-08 05:47
@lpful Thankyou！it help me a lot. This app is what I've been looking for.

**Comment by pinootto** [comment] 2020-03-05 06:14
In this period of novel corona virus outbreak, almost all the students in China are taking online lessons at home. Many students use the phone all day long. This is not good for their eyes and posture. Using a computer is much better and convenient, but not all the families have a suitable computer or enough money to buy one.

In my case I installed scrcpy on a raspberry pi 3 (with USB keyboard and mouse) and connected to TV (or old monitor). Then my child can follow the online lessons on the big screen and interact with the teacher thanks to scrcpy. It works really well!

The only problem is that we cannot input chinese characters directly from the computer keyboard to the phone. I found a workaround by installing "remote keyboard" app (http://www.onyxbits.de/remotekeyboard) on the phone and typing the chinese characters inside the telnet terminal. It works, but it is not very convenient for daily use.

So I would like to ask the developers of scrcpy if they can focus their efforts in these days to solve the issue of typing chinese characters directly in scrcpy.

If you can do it, I am sure that many chinese children and their families will thank you a lot.

**Comment by lpful** [comment] 2020-03-05 07:25
@pinootto 你好，如果PC是Windows系统的话，可以试试看ARDC，https://www.cnblogs.com/we-hjb/p/9220084.html

**Comment by qqlovekerry** [comment] 2020-03-05 07:36
@pinootto Hi, I found that if the default input method is Gboard, I can input directly with my keyboard on my PC. And I am using Ubuntu 18.04 on my PC. Maybe you can have a try on raspberry pi to see whether it works.

**Comment by pinootto** [comment] 2020-03-06 02:22
> @pinootto 你好，如果PC是Windows系统的话，可以试试看ARDC，https://www.cnblogs.com/we-hjb/p/9220084.html

Thanks, but my computer is a raspberry pi with raspbian (GNU/Linux) as operating system.

**Comment by pinootto** [comment] 2020-03-06 02:30
> @pinootto Hi, I found that if the default input method is Gboard, I can input directly with my keyboard on my PC. And I am using Ubuntu 18.04 on my PC. Maybe you can have a try on raspberry pi to see whether it works.

That is a good news! Thanks.

Do you know how to install Gboard on a chinese Vivo phone, that doesn't have Google Play?

**Comment by qqlovekerry** [comment] 2020-03-06 02:56
@pinootto I think you need some specific methods to bypass the GREAT firewall. Or maybe try to get the APK file of Gboard. I think maybe you need some search work trying to find out the solution.

**Comment by pinootto** [comment] 2020-03-06 05:25
> @pinootto I think you need some specific methods to bypass the GREAT firewall. Or maybe try to get the APK file of Gboard. I think maybe you need some search work trying to find out the solution.

@qqlovekerry OK, thanks. I will try.

**Comment by npes87184** [comment] 2020-03-06 10:19
This issue has been discussed many times. There are some possible solutions here.

- [SocketIME](https://github.com/npes87184/SocketIME)
- [ADBKeyBoard](https://github.com/senzhk/ADBKeyBoard)

SocketIME has prototype now, but it needs more tuning for working reliable.

**SocketIME demo**

[![IMAGE ALT TEXT](https://img.youtube.com/vi/s9LZpAnIf4A/0.jpg)](https://youtu.be/s9LZpAnIf4A "Video Title")

If people interesting on this area. They can simply try and contribute to related repo, `scrcpy`, `SocketIME`, `ADBKeyBoard` and so on.

Thanks.

**Comment by pinootto** [comment] 2020-03-07 07:36
> > @pinootto I think you need some specific methods to bypass the GREAT firewall. Or maybe try to get the APK file of Gboard. I think maybe you need some search work trying to find out the solution.
> 
> @qqlovekerry OK, thanks. I will try.

@qqlovekerry I succeeded to install Gboard on the chinese phone. 

It works perfectly and very convenient!

No need to install/use additional software on the PC. 
Just install Gboard on the phone, select Gboard as input keyboard on the phone and then we can type chinese characters directly from the PC keyboard to the phone via scrcpy.

Thank you very much. Now my child is using scrcpy all day long for the online school.

**Comment by rom1v** [comment] 2020-04-09 19:36
Closing as duplicate of #37.

**Closed by rom1v** 2020-04-09 19:36 UTC
Labels: input events, keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:39
Please test #1426 (works on Android >= 7).
