### ISSUE TITLE
Question/request: Is there a way to keep aspect ratio when resizing the window manually ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Genymobile/scrcpy#2387] opened 2021-06-14 07:33 UTC
I've tried to search about it, but is there a way to keep the aspect ratio of the window, when I manually resize the window (meaning I exclude the single clicking for full-screen resizing, whether by keyboard or by mouse) ?
This way the window of ScrCpy will fit nicely with the content it shows (again, I'm excluding the scenario of full screen).

I mean using this:

![image](https://user-images.githubusercontent.com/5357526/121854997-8418af80-ccfb-11eb-8c8d-7f42b4a2392b.png)

I want to avoid the black parts around the content.

Maybe like some video players (I use Media Player Classic), we could use CTRL key while resizing, to force staying on original aspect ratio?
Or force it by a flag?
Or both?

**Comment by rom1v** [comment] 2021-06-14 07:39
Duplicate of #2317. See https://github.com/Genymobile/scrcpy/issues/2317#issuecomment-841692150

Note that you could remove the black borders after the resize by double-clicking on them, or <kbd>Alt</kbd>+<kbd>w</kbd>.

**Closed by rom1v** 2021-06-14 07:39 UTC

**Comment by AndroidDeveloperLB** [comment] 2021-06-14 07:46
@rom1v Useful tips. A bit hard to double tap when they are thing though.

**Comment by AndroidDeveloperLB** [comment] 2021-06-14 08:22
@rom1v BTW, using the tips I've noticed an issue: It goes to the top-left corner, instead of resizing based on the content, meaning that when I use it, the content moves to somewhere else.

Is this bug reported?

**Comment by rom1v** [comment] 2021-06-14 19:25
Indeed, it would be better if the device content stays at the same place.

I just implemented it: [`center_on_resize`](https://github.com/Genymobile/scrcpy/commits/center_on_resize)

**Comment by AndroidDeveloperLB** [comment] 2021-06-14 20:05
@rom1v Wow this was fast. Thank you!

**Comment by ballo** [comment] 2023-12-15 23:27
> Indeed, it would be better if the device content stays at the same place.
> 
> I just implemented it: [`center_on_resize`](https://github.com/Genymobile/scrcpy/commits/center_on_resize)

Any way to disable resizing?
