### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by hsyn006** [Genymobile/scrcpy#1769] opened 2020-09-17 11:15 UTC
Hi ! I want help from you about a problem about scrcpy. my problem is that when i enter pubg with panda (also when i enter normally) only a, w, s, d keys work on the keyboard. I can't use or key with panda, is there a solution to this? If so, could you please write?

**Comment by rom1v** [comment] 2020-09-17 11:29
I don't know what is panda :panda_face:

**Comment by hsyn006** [comment] 2020-09-17 11:32
> I don't know what is panda

octopus-like gamepad program, panda gamepad pro write google

**Comment by rom1v** [comment] 2020-09-17 11:37
OK Game controllers are not managed.

https://wiki.libsdl.org/CategoryJoystick

**Comment by rom1v** [comment] 2020-09-17 11:38
Duplicate of #99

**Closed by rom1v** 2020-09-17 11:38 UTC
Labels: feature request
