### ISSUE TITLE
Can't Mirror My Cameras

### ISSUE THREAD

**Issue by CodexNer** [Genymobile/scrcpy#5156] opened 2024-08-01 13:43 UTC
```
PS D:\scrcpy-win64> .\scrcpy --video-source=camera --camera-facing=back --camera-ar=16:9 --camera-high-speed --camera-fps=120
scrcpy 2.5 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: ADB device found:
INFO:     -->   (usb)  10DD1Q05DA00174                 device  V2207
D:\scrcpy-win64\scrcpy-server: 1 file pushed, 0 skipped. 34.6 MB/s (69624 bytes in 0.002s)
[server] INFO: Device: [vivo] vivo V2207 (Android 14)
INFO: Renderer: direct3d
[server] INFO: Using camera '0'
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
        at android.os.Parcel.createException(Parcel.java:3055)
        at android.os.Parcel.readException(Parcel.java:3038)
        at android.os.Parcel.readException(Parcel.java:2980)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6649)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:8317)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3771)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2560)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:3106)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3351)
        at android.provider.Settings$Global.getStringForUser(Settings.java:17224)
        at android.provider.Settings$Global.getString(Settings.java:17198)
        at android.hardware.camera2.vivo_ext.VivoCameraUtils.sendOpenCloseCameraBroadcast(VivoCameraUtils.java:172)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:873)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1171)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1193)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:983)
        at com.genymobile.scrcpy.CameraCapture.openCamera(CameraCapture.java:245)
        at com.genymobile.scrcpy.CameraCapture.init(CameraCapture.java:86)
        at com.genymobile.scrcpy.SurfaceEncoder.streamCapture(SurfaceEncoder.java:56)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:257)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:184)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7843)
        at android.app.IActivityManager$Stub.onTransact$getContentProvider$(IActivityManager.java:12683)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3244)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3266)
```

**Comment by rom1v** [comment] 2024-08-01 14:30
Does it work with `--no-audio` by any chance? (https://github.com/Genymobile/scrcpy/issues/4639#issuecomment-1966027858)

Is your device rooted (it should not)?

**Comment by CodexNer** [comment] 2024-08-01 22:43
I don't think so? I never rooted my windows or even the device itself. But screen mirroring works perfectly fine except the camera mirror

**Comment by BlackCat2024-01** [comment] 2024-08-13 08:34
VIVO Y27S The same problem. Who can help me?

`C:\scrcpy>scrcpy --video-source=camera
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: ADB device found:
INFO:     -->   (usb)  10ADC816JB0015J                 device  V2322
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 129.8 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [vivo] vivo V2322 (Android 13)
INFO: Renderer: direct3d
[server] INFO: Using camera '0'
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer error
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
        at android.os.Parcel.createException(Parcel.java:3009)
        at android.os.Parcel.readException(Parcel.java:2992)
        at android.os.Parcel.readException(Parcel.java:2934)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6154)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7719)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3510)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2542)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2955)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3182)
        at android.provider.Settings$Global.getStringForUser(Settings.java:16184)
        at android.provider.Settings$Global.getString(Settings.java:16158)
        at android.hardware.camera2.vivo_ext.VivoCameraUtils.sendStartPreviewBroadCast(VivoCameraUtils.java:213)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:774)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1039)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1060)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:875)
        at com.genymobile.scrcpy.CameraCapture.openCamera(CameraCapture.java:241)
        at com.genymobile.scrcpy.CameraCapture.init(CameraCapture.java:86)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:55)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:174)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7432)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2854)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3166)
        at android.os.Binder.execTransactInternal(Binder.java:1346)`

**Comment by rom1v** [comment] 2024-08-13 08:41
Maybe try to disable audio: https://github.com/Genymobile/scrcpy/issues/4639#issuecomment-1966027858

> scrcpy 2.4

(also try the latest version, 2.6.1 currently, but I'm not sure it will change anything to your problem)

**Comment by BlackCat2024-01** [comment] 2024-08-13 08:49
> Попробуйте отключить звук

C:\scrcpy>scrcpy  --no-audio --video-source=camera

**Comment by BlackCat2024-01** [comment] 2024-08-13 08:54
> (также попробуйте последнюю версию, 2.6.1 на данный момент, но я не уверен, что это как-то решит вашу проблему)

C:\Users\Nickolay\Desktop\scrcpy-win64-v2.6.1\scrcpy-win64-v2.6.1>scrcpy --no-audio --video-source=camera
scrcpy 2.6.1 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: ADB device found:
INFO:     -->   (usb)  10ADC816JB0015J                 device  V2322
C:\Users\Nickolay\Desktop\scrcpy-win64-v2.6.1\scrcpy-win64-v2.6.1\scrcpy-server: 1 file pushed, 0 skipped. 69.3 MB/s (71112 bytes in 0.001s)
[server] INFO: Device: [vivo] vivo V2322 (Android 13)
INFO: Renderer: direct3d
[server] INFO: Using camera '0'
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer error
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.SecurityException: Given calling package android does not match caller's uid 2000
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
        at android.os.Parcel.createException(Parcel.java:3009)
        at android.os.Parcel.readException(Parcel.java:2992)
        at android.os.Parcel.readException(Parcel.java:2934)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6154)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7719)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3510)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:2542)
        at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2955)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3182)
        at android.provider.Settings$Global.getStringForUser(Settings.java:16184)
        at android.provider.Settings$Global.getString(Settings.java:16158)
        at android.hardware.camera2.vivo_ext.VivoCameraUtils.sendStartPreviewBroadCast(VivoCameraUtils.java:213)
        at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:774)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1039)
        at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:1060)
        at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:875)
        at com.genymobile.scrcpy.video.CameraCapture.openCamera(CameraCapture.java:248)
        at com.genymobile.scrcpy.video.CameraCapture.init(CameraCapture.java:89)
        at com.genymobile.scrcpy.video.SurfaceEncoder.streamCapture(SurfaceEncoder.java:67)
        at com.genymobile.scrcpy.video.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-video-SurfaceEncoder(SurfaceEncoder.java:268)
        at com.genymobile.scrcpy.video.SurfaceEncoder$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:174)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7432)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2854)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3166)
        at android.os.Binder.execTransactInternal(Binder.java:1346)

**Comment by rom1v** [comment] 2024-08-13 08:57
Duplicate of #4512 (also a Vivo device).

**Closed by rom1v** 2024-08-13 08:57 UTC

**Comment by BlackCat2024-01** [comment] 2024-08-13 09:07
adb pull /system/framework/framework.jar

[Uploading framework.zip…]()

**Comment by rom1v** [comment] 2024-08-13 11:22
Thank you for the `framework.jar`.

AFAIK, there's nothing I can do for this device, they added a call to Vivo-specific code, which fails (throws an exception) when called from the shell user.

**Comment by BlackCat2024-01** [comment] 2024-08-13 11:39
> Спасибо за `framework.jar`.
> 
> Насколько мне известно, я ничего не могу сделать для этого устройства. Они добавили вызов специфичного для Vivo кода, который дает сбой (выдает исключение) при вызове из оболочки пользователя.

Is this smartphone not compatible with this feature?

**Comment by rom1v** [comment] 2024-08-13 12:18
Yes, sort of (but only at the software level, not hardware).
