### ISSUE TITLE
Mouse inputs are off

### ISSUE THREAD

**Issue by jonathanlinford** [Genymobile/scrcpy#172] opened 2018-06-12 21:05 UTC
When I use the scrcpy window on my external monitors, the inputs are offset to the bottom right. It works as intended when using my laptop screen (Macbook on High Sierra) but when I use my monitors it doesn't work. This happens across devices (I use a pixel 2 XL). I think it might have to do with working properly on a non-primary display.

https://d.pr/v/D01lxk

**Comment by rom1v** [comment] 2018-06-12 21:08
Thank you for your report.

This is a duplicate of https://github.com/Genymobile/scrcpy/issues/15. I think this is an SDL problem, and have no good solution :disappointed:

**Closed by rom1v** 2018-06-12 21:08 UTC
