### ISSUE TITLE
Support screen recording

### ISSUE THREAD

**Issue by sergeyfitis** [Genymobile/scrcpy#116] opened 2018-04-06 19:25 UTC
Feature request: Support screen recording

**Comment by meiser79** [comment] 2018-04-10 19:03
duplicate of #21

**Closed** 2018-04-10 19:59 UTC
Labels: feature request

**Comment by rom1v** [comment] 2018-11-11 22:43
This is implemented in v1.5:

    scrcpy --record file.mp4

:tada:

**Comment by Noob567** [comment] 2018-11-23 12:14
And how to stop screen recording?

**Comment by rom1v** [comment] 2018-11-23 13:15
@Noob567 It stops when you close _scrcpy_.

**Comment by KeronCyst** [comment] 2018-12-26 07:47
Also, is it possible for non-microphone audio recording to be added?

**Comment by lae** [comment] 2019-02-02 14:19
@KeronCyst you can do this in bash.

    scrcpy --record $(date +%s).mp4

There's also the `audio` branch but I haven't been able to get it working myself.

**Comment by KeronCyst** [comment] 2019-02-03 05:58
Sorry, by "bash" do you mean I can just enter that exactly as you put?
