### ISSUE TITLE
Using Scrcpy as a virtual display you can stream to.

### ISSUE THREAD

**Issue by oakniiv** [Genymobile/scrcpy#1286] opened 2020-04-13 10:43 UTC
First of all, incredible piece of software, really incredible, thank you for this.

It would be great if you guys took Scrcpy a step further and we were able to use Scrcpy as a "SmartView" (On android) display. Basically if we could use Scrcpy as a Virtual TV inside Ubuntu and stream content to it from Youtube app on android or stream a slideshow from gallery but still be able to go back to home screen and use our phones while the content is streaming.

Thanks again.

**Comment by rom1v** [comment] 2020-04-13 11:22
> First of all, incredible piece of software, really incredible, thank you for this.

Thank you :wink:

> It would be great if you guys took Scrcpy a step further and we were able to use Scrcpy as a "SmartView" (On android) display. Basically if we could use Scrcpy as a Virtual TV inside Ubuntu and stream content to it from Youtube app on android or stream a slideshow from gallery but still be able to go back to home screen and use our phones while the content is streaming.

Yes, that would be great.

Technically, maybe it's possible to use an Android application using a `Presentation`, and use the new `--display` option on `dev` branch (#1238). If someone is interested to work on a PoC, please go ahead. I currently have no time to investigate, so contributions are welcome :wink:

(I'm closing as duplicate of #740 and #886.)

**Closed by rom1v** 2020-04-13 11:22 UTC
