### ISSUE TITLE
Support multi screen

### ISSUE THREAD

**Issue by 1step2hell** [Genymobile/scrcpy#526] opened 2019-05-08 08:28 UTC
I'm working in Mac OS with multi screen: rmbp + Dell display.
scrcpy(v1.3) works well on the default display of rmbp, but there isn't preview  on Dell display.

FYI: 
1. It can receive and act the click event in window, just showing black screen only.
2. This doesn't happen if multi screen working in mirror mode, it happens while multi screen display side by side. 

How could I do to make it works well in second display? 
Thanks!

**Comment by rom1v** [comment] 2019-05-10 08:29
Thank you for your report.

My first thought is that this is a bug in [libSDL](https://libsdl.org/) (like #15), because _scrcpy_ itself does not handle multi-screen, only SDL does.

Which version of SDL do you use?

**Comment by roopepal** [comment] 2019-05-10 18:52
Same here: only shows black when I move the window to the external display, and it again starts showing the preview correctly when I move the window back to the rMBP display. 

`sdl2-config --version` says 2.0.9.

**Comment by rom1v** [comment] 2019-05-10 19:10
What if you start _scrcpy_ on the secondary display directly?

**Comment by roopepal** [comment] 2019-05-10 19:29
It always starts on the primary display (how do I even start it on the secondary display?), but if I set the external monitor as my primary display it works fine on that and similarly fails when I move the window to the rMBP display. In other words, it works correctly on the display is starts on, and preview positioning fails when moved to the other display.

**Comment by 1step2hell** [comment] 2019-05-11 02:02
@rom1v sdl2-config --version 2.0.8

**Comment by catinred2** [comment] 2019-05-28 16:02
same problem here. BUT:
1.  scrcpy window shows alright in my secondary display
2. the window does not respond mouse event while keyboard event works fine

**Comment by rom1v** [comment] 2019-05-28 16:05
@catinred2 If you are on MacOS, see #15.

**Comment by catinred2** [comment] 2019-05-29 07:01
> @catinred2 If you are on MacOS, see #15.

yes that is the case

**Comment by rom1v** [comment] 2020-04-11 23:10
(closing as duplicate of #15)

**Closed by rom1v** 2020-04-11 23:10 UTC
Labels: multiscreen

**Comment by carstenhag** [comment] 2020-05-19 08:05
@1step2hell and others: If you can, please test #1408 so that this issue gets fixed.
