### ISSUE TITLE
free(): invalid pointer when trying to record screen

### ISSUE THREAD

**Issue by Maik93** [Genymobile/scrcpy#720] opened 2019-08-13 11:48 UTC
Hi, beautiful tool!
I've found a bug that I can't relate to any current issue: when I try to record my Android screen, I've got segmentation fault.

I've tried several versions of `scrcpy -r file.mkv`, including with `-b1M` and `-m600` and with .mp4 output file, the result is allways:
```sh
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server....shed. 2.3 MB/s (22546 bytes in 0.009s)
INFO: Recording started to matroska file: file.mkv
INFO: Initial texture: 1080x2280
free(): invalid pointer
[1]    6813 abort (core dumped)  scrcpy -r file.mkv
```

Any idea what's going on?
Thank you in advice

**Comment by rom1v** [comment] 2019-08-13 11:52
Hi,

Thank you for your report.

I'm closing as duplicate of #707.

I will investigate as soon as I have time.

Could you please paste the result of:

    scrcpy -v

(to get the version of the dependencies)?

**Closed by rom1v** 2019-08-13 11:52 UTC

**Comment by rom1v** [comment] 2019-08-13 17:45
Fixed on `master` by a9c8fa305d2313bed70b2d1d756083f40e065352.

**Comment by Maik93** [comment] 2019-08-14 14:18
Thank you!
I don't know if it's too late but here's the result of `-v`:
```
scrcpy 1.10

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100
```

How long does it take to this commit to be integrated in the snap store (Ubuntu software center)?

**Comment by rom1v** [comment] 2019-08-14 14:21
@sisco311 is it possible to update without a new release? Is it expected that the snap package uses an old FFmpeg here?
