### ISSUE TITLE
Poco M3 Can't Mirror Using SCRCPY 

### ISSUE THREAD

**Issue by Blacklite01** [Genymobile/scrcpy#2205] opened 2021-03-18 03:36 UTC
![161319639_736529457047093_758813269913747024_n](https://user-images.githubusercontent.com/78941471/111569679-23ea9e00-87de-11eb-899d-7d77bbd09883.png)

**Comment by rom1v** [comment] 2021-03-18 07:51
Duplicate of #2096.

**Closed by rom1v** 2021-03-18 07:51 UTC
