### ISSUE TITLE
Modify/Add Feature from "Audio Forwarding" to "Audio Mirroring"

### ISSUE THREAD

**Issue by myrexious** [Genymobile/scrcpy#4264] opened 2023-08-28 19:36 UTC
It seems latency is quite harsh for games (especially for rhythm games). If we use Audio Forwarding, there will be latency or glitches. But if we don't use Audio Forwarding, sound recording will only come from the Android device which makes streaming not possible.

An option to forward the audio without blocking the Android audio output would be great. This app could "Mirror" the audio so the audio is present both on the Android device and on the PC. I was thinking of Discord's screen share where the user's device output is still there while Discord receives the audio and video packets.

Additional question:
- Is there any plan to upgrade this project from JDK 11 to newer versions? might try this solution myself for learning (no promises)

**Comment by rom1v** [comment] 2023-08-28 20:37
See #3875

**Comment by rom1v** [comment] 2024-07-16 19:47
Please test #5102.

Closing as duplicate of #3875.

**Closed by rom1v** 2024-07-16 19:47 UTC
