### ISSUE TITLE
Please add screenshot hotkey feature 

### ISSUE THREAD

**Issue by adahbingee** [Genymobile/scrcpy#1588] opened 2020-07-12 18:29 UTC
- [*] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

hotkey for screenshoot e.g `CTRL`+`SHIFT`+`s`

best quality lossless screenshot, and save at directory by incremental naming e.g. `%04d.png`

```shell
adb shell screencap -p /sdcard/screen.png
adb  pull /sdcard/screen.png ./
```

**Comment by teunissenstefan** [comment] 2020-07-18 22:36
Using the "screencap" method, apps can detect if a screenshot has been taken. If this feature gets implemented I hope that a method will be used that apps cannot detect. Like exporting a frame of the video stream for example.

**Comment by rom1v** [comment] 2020-07-19 07:58
Duplicate of #684.

**Closed by rom1v** 2020-07-19 07:58 UTC
