### ISSUE TITLE
Android support 

### ISSUE THREAD

**Issue by xAffan** [Genymobile/scrcpy#3142] opened 2022-03-24 01:09 UTC
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I have an android device with a broken screen, the only way to use it is to connect it to a PC, which is highly inconvenient.

**Describe the solution you'd like**
scrcpy on android. I want to be able to run scrcpy on android (and potentially connect using wireless adb or reverse otg) in order to control my other broken android from my fine android.

**Describe alternatives you've considered**
AirDroid, TeamViewer and other proprietary apps. They all suck as they work over their own servers, slowing down connection.

**Additional context**
A simple android app to run scrcpy on android :3

**Comment by rom1v** [comment] 2022-03-24 06:22
Duplicate of #100.

**Closed by rom1v** 2022-03-24 06:22 UTC
