### ISSUE TITLE
Could not copy text from device to computer

### ISSUE THREAD

**Issue by qingmiaodi521** [Genymobile/scrcpy#1833] opened 2020-10-14 09:47 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows
 - scrcpy version: [e.g. 1.16.1]
 - installation method: whole package
 - device model:
 - Android version: android 10

**Describe the bug**
I cannot copy text from device to computer
1. copy text in device, or use mod+c/ctrl c
2. paste in computer by using ctrl+v, not work.

```
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:49)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:64)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:212)
        at com.genymobile.scrcpy.Device$2.dispatchPrimaryClipChanged(Device.java:95)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:82)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:352)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(libmapleservices.so:6324436)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(libmapleservices.so:6343820)
        at android.content.IClipboard$Stub.onTransact(libmapleframework.so:1597744)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(libmapleservices.so:3137716)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5521104)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:49)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:64)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:212)
        at com.genymobile.scrcpy.Device$2.dispatchPrimaryClipChanged(Device.java:95)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:82)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:352)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(libmapleservices.so:6324436)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(libmapleservices.so:6343820)
        at android.content.IClipboard$Stub.onTransact(libmapleframework.so:1597744)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(libmapleservices.so:3137716)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5521104)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:49)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:64)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:212)
        at com.genymobile.scrcpy.Device$2.dispatchPrimaryClipChanged(Device.java:95)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:82)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:352)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(libmapleservices.so:6324436)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(libmapleservices.so:6343820)
        at android.content.IClipboard$Stub.onTransact(libmapleframework.so:1597744)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(libmapleservices.so:3137716)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5521104)

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getPrimaryClip(ClipboardManager.java:49)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:64)
        at com.genymobile.scrcpy.Device.getClipboardText(Device.java:212)
        at com.genymobile.scrcpy.Device$2.dispatchPrimaryClipChanged(Device.java:95)
        at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:82)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)
Caused by: java.lang.SecurityException: Calling uid 0 does not own package com.android.shell
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:352)
        ... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.clipboard.ClipboardService.addActiveOwnerLocked(libmapleservices.so:6324436)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.getPrimaryClip(libmapleservices.so:6343820)
        at android.content.IClipboard$Stub.onTransact(libmapleframework.so:1597744)
        at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(libmapleservices.so:3137716)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5521104)
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment] 2020-10-14 10:11
Duplicate of #1606. Your device is rooted?

**Closed by rom1v** 2020-10-14 10:11 UTC

**Comment by qingmiaodi521** [comment] 2020-10-15 00:52
> Duplicate of #1606. Your device is rooted?

Yes. It's Huawei Phone.
