### ISSUE TITLE
Meizu M971Q configure error

### ISSUE THREAD

**Issue by likezjuisee** [Genymobile/scrcpy#890] opened 2019-10-28 10:30 UTC
![image](https://user-images.githubusercontent.com/12730220/67671500-0a5e7180-f9b1-11e9-93cf-39e04b3576ce.png)

**Comment by BigandBang** [comment] 2019-11-12 12:10
题主，你解决了吗？我也是魅族手机，也是同样的问题。但是用其他手机，完全不会出现这个情况。

**Comment by rom1v** [comment] 2019-11-13 11:39
Hi.

Thank you for your report (but, please, copy-paste text instead of screenshot, so that we can search and find it).

This is a duplicate of #158.

We're working on a workaround for this device: #888.

**Closed by rom1v** 2019-11-13 11:39 UTC

**Comment by rom1v** [comment] 2019-11-13 15:29
Could you please replace [`scrcpy-server.jar`](https://tmp.rom1v.com/scrcpy/issue365/1/scrcpy-server.jar) in your scrcpy v1.10 and test again?
_SHA256: b34c8ce7f8f60e6d6ef42c3b0975c6b7650755f2d50205a2e950f996e2091bbc_
