### ISSUE TITLE
Is there a landscape mode?

### ISSUE THREAD

**Issue by kr898** [Genymobile/scrcpy#284] opened 2018-10-02 13:03 UTC
As title

**Comment by rom1v** [comment] 2018-10-02 13:18
No.

By "landscape mode", do you mean force the orientation on the device?

    # disable auto rotation
    adb shell settings put system accelerometer_rotation 0
    # use custom rotation (0=portrait, 1=landscape)
    adb shell settings put system user_rotation 1

Or do you mean a client rotation without touching the device (https://github.com/Genymobile/scrcpy/issues/218)?

**Comment by kr898** [comment] 2018-10-02 13:28
Client rotation without touching the device. (as the device is already on landscape mode)

**Comment by rom1v** [comment] 2018-10-02 13:31
OK, so I'm closing as duplicate of #218.

**Closed by rom1v** 2018-10-02 13:31 UTC
Labels: feature request, rotation

**Comment by rom1v** [comment] 2020-02-27 20:33
Implemented on `dev` (#1151)
