### ISSUE TITLE
-Sw and mod+o not working

### ISSUE THREAD

**Issue by LYAVONIY** [Genymobile/scrcpy#4248] opened 2023-08-21 10:45 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 11 last version
 - scrcpy version: 2.1.1
 - installation method: Windows release
 - device model: google pixel 7
 - Android version: 14 beta last version

**Describe the bug**
only alt+o not working, every other shortcuts works fine, same with -Sw
on v2 everything was good, but now its not working on v2 also

when i press ALT+O:

scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)        *******************            device  Pixel_7
C:\Users\disha\OneDrive\Рабочий стол\Проек...file pushed, 0 skipped. 145.6 MB/s (56995 bytes in 0.000s)
[server] INFO: Device: [Google] google Pixel 7 (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

**Comment by rom1v** [comment] 2023-08-21 11:05
Duplicate of https://github.com/Genymobile/scrcpy/issues/3784

To be investigated (once the source code of Android 14 is released).

**Closed by rom1v** 2023-08-21 11:05 UTC
