### ISSUE TITLE
Pasting: Ctrl+V works but not Shift+Insert

### ISSUE THREAD

**Issue by KeronCyst** [Genymobile/scrcpy#271] opened 2018-09-21 17:12 UTC
The "v" key on a certain device that I have is busted and hard to press (I am using a typing shortcut to access "v" through another key"), so I can't paste because Shift+Insert doesn't seem to do anything. Could scrcpy be configured to do this? That'd be sweet.

**Comment by rom1v** [comment] 2018-09-21 19:40
No, shortcuts are hardcoded. I'm closing as duplicate of https://github.com/Genymobile/scrcpy/issues/149.

**Closed by rom1v** 2018-09-21 19:40 UTC
