### ISSUE TITLE
After my Meizu 20 upgraded to Android 14, there is an error with the command (+shift) + o shortcut function

### ISSUE THREAD

**Issue by wade1998** [Genymobile/scrcpy#4616] opened 2024-01-26 02:30 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: macOS
 - scrcpy version: 2.3.1
 - installation method: brew
 - device model: Meizu 20
 - Android version: 14

**Describe the bug**

When I successfully mirror the device and attempt to use the shortcut command(+shift)+o to toggle the screen on and off, the connection is disrupted. At this point, the terminal displays the following error message:

```
Native registration unable to find class 'com/android/server/DeviceControlService'; aborting...
```
Similarly, when I attempt to mirror it directly by running the parameter '-S' to turn off the screen, the mirrored screen flashes briefly and then disconnects, with the same error message reported as above.

**Comment by rom1v** [comment] 2024-01-26 06:45
Duplicate of #4544.

Currently no solution for Meizu phones.

**Closed by rom1v** 2024-01-26 06:45 UTC

**Comment by jay-dragon** [comment] 2024-01-30 07:52
我也一样，20pro升级到flyme10.5之后就不行了。
