### ISSUE TITLE
NullPointerException when using scrcpy with Hisense TV on Android 11

### ISSUE THREAD

**Issue by fangxiaofelix** [Genymobile/scrcpy#5061] opened 2024-07-05 07:48 UTC
**Environment:**
- Device: Hisense TV
- Android version: 11
- scrcpy version: 2.5
- Command: `scrcpy --no-audio -m 1024`

**Error Log:**
[server] INFO: Device: [Skyworth] Skyworth 8R145_A5D (Android 11) 
[server] ERROR: Exception on thread Thread[video,5,main] 
java.lang.NullPointerException: Attempt to invoke virtual method ‘java.lang.Object android.content.Context.getSystemService(java.lang.String)’ on a null object reference at android.media.MediaCodec.getCurProcessName(MediaCodec.java:2430) at android.media.MediaCodec.setSkyMediaStatus(MediaCodec.java:2443) at android.media.MediaCodec.<init>(MediaCodec.java:1915) at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1893) at com.genymobile.scrcpy.SurfaceEncoder.createMediaCodec(SurfaceEncoder.java:207) at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:52) at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253) at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4) at java.lang.Thread.run(Thread.java:923) INFO: Renderer: direct3d
ERROR: Demuxer ‘video’: stream disabled due to connection error 
ERROR: Demuxer error

**Comment by rom1v** [comment] 2024-07-05 07:53
Duplicate of #4922 for Skyworth devices.

**Closed by rom1v** 2024-07-05 07:53 UTC
