### ISSUE TITLE
I can not input not english text via pc keyboard on windows 7x64 - scrcpy v1.1

### ISSUE THREAD

**Issue by svladimirs** [Genymobile/scrcpy#113] opened 2018-04-04 02:00 UTC
First: Thank you for this program!
Second: See the top of issue. I changed language from english to russian in windows and tried input russian text. English text scrcpy accept and input into android, but not russian.

**Comment by rom1v** [comment] 2018-04-04 06:08
Thank you for the report.

This is a duplicate of https://github.com/Genymobile/scrcpy/issues/37.

**Closed by rom1v** 2018-04-04 06:08 UTC
