### ISSUE TITLE
Unicode support.

### ISSUE THREAD

**Issue by axhan** [Genymobile/scrcpy#214] opened 2018-07-29 01:39 UTC
Related to #193. At first glance, scrcpy is THE application that would finally make touchscreen pocket computers (i.e. smartphones) anything other than annoying toys to slowly mistype on for me. However: The method you use for sending text input from computer to android gadget makes use of ADBs builtin string injection primitives, which seem to be limited to UTF-7. Hence, language use when typing is limited to ASCII, which means it's in practise really only usable for English, not much else. Especially not Swedish, since the letter "å" cannot be worked around in the code by using a combination of a diacritical dead key with "a". 

I realize adding support for Unicode input would almost certainly necessitate pushing some kind of injector app onto the Android thingy. Some kind of... fake keyboard app. I know too little of Android to speculate. So you may not want to implement it. It would be **great** if you did, though.

_Moreover, I consider that whoever made the design decision in Android to limit "adb shell input text" to UTF-7 should be crucified. But that's neither here nor there... :-)_

**Comment by guanzhangrtk** [comment] 2019-01-24 10:38
Any update regarding this? It would be great if we can copy & paste Asian text via scrcpy as well. Great work BTW!

**Comment by rom1v** [comment] 2020-04-09 19:36
Closing as duplicate of #37.

**Closed by rom1v** 2020-04-09 19:36 UTC
Labels: keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:39
Please test #1426 (works on Android >= 7).
