### ISSUE TITLE
Can you support screenshots?

### ISSUE THREAD

**Issue by molixiaoxiao** [Genymobile/scrcpy#3553] opened 2022-10-26 10:01 UTC
Like `adb shell screencap -p > screen.png`. Hope to support one-click screenshots. Thanks!

**Comment by rom1v** [comment] 2022-10-26 10:08
Duplicate of #684. Also see #2040.

**Closed by rom1v** 2022-10-26 10:08 UTC

**Comment by molixiaoxiao** [comment] 2022-10-27 03:08
I see. But I can't found the relevant screenshot command for scrcpy. Likes `adb shell screencap -p > screen.png`. Thanks!

**Comment by molixiaoxiao** [comment] 2022-10-27 03:09
> Duplicate of #684. Also see #2040.

I see. But I can't found the relevant screenshot command for scrcpy. Likes adb shell screencap -p > screen.png. Thanks!
