### ISSUE TITLE
MIC PROBLEM WHILE GAMING

### ISSUE THREAD

**Issue by Rahulraj2003** [Genymobile/scrcpy#5136] opened 2024-07-26 05:28 UTC
**Is your feature request related to a problem? Please describe.**
WHILE MIRRORING I NEED TO TALK WITH MY FRIENDS RIGHT! SO WHEN I OPEN MIC MY PHONE MIC IS TURING ON AND ALL PHONE AUDIO IS HEARING IN PHONE SPEAKER 

I HAVE CONNECTED HEADSET TO THE PC TO HEAR PHONE AUDIO THROUGH THAT!

**Describe the solution you'd like**
CAN YOU DO THAT>>.

**Describe alternatives you've considered**

**Additional context**

**Comment by rom1v** [comment] 2024-07-26 09:18
Duplicate of #4084 #4087.

**Closed by rom1v** 2024-07-26 09:18 UTC
