### ISSUE TITLE
scrcpy always copies server binary to device?

### ISSUE THREAD

**Issue by thatsysadmin** [Genymobile/scrcpy#5157] opened 2024-08-01 20:00 UTC
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
From what I can tell, scrcpy will always copy and remove the server binary that it pushes to the android device and removes it when it's done. While probably insignificant, this might take a toll on NAND durability on Android's side.

**Describe the solution you'd like**
Wouldn't it be more efficient to just copy once, and if the binary exists on Android's side, just execute it in place instead of writing the binary every time? 

If we're worried about the binary being modified between sessions, why not checksum the binary on the Android device and copy a known good one if the checksums don't match up? A mechanism like this should also be able to handle updates as well.

**Describe alternatives you've considered**
While `--no-cleanup` seems to work as intended, sessions afterward still copy the server binary.

**Additional context**
None.

**Comment by rom1v** [comment] 2024-08-01 20:52
Duplicate of #1722.

**Closed by rom1v** 2024-08-01 20:52 UTC
