### ISSUE TITLE
scrcpy- server without extension causing error

### ISSUE THREAD

**Issue by runz0rd** [Genymobile/scrcpy#969] opened 2019-11-30 12:08 UTC
Seems like scrcpy-server without an extension is causing a problem on my phone:
```
11-30 11:31:35.097 30191 30191 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<     
11-30 11:31:35.201 30191 30191 W app_process: Failed to determine odex file name: Dex location /data/local/tmp/scrcpy-
server has no extension.                                                                                              
11-30 11:31:35.202 30191 30191 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 3019
1 (main), pid 30191 (main)
```
Switched back to version 1.10, working perfectly

**Comment by rom1v** [comment] 2019-11-30 12:11
Thank you for your report.

This is a duplicate of #944. See this thread for new binaries.

**Closed by rom1v** 2019-11-30 12:11 UTC
