### ISSUE TITLE
Multi Touch Input

### ISSUE THREAD

**Issue by il-Grigio** [Genymobile/scrcpy#4382] opened 2023-10-27 15:42 UTC
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

My problem is that I would like to use scrcpy to play a few games on my PC, but some of them require multiple touch inputs at once, and the PC handles only one mouse, I would like, if possible, to remap come keyboard keys to a touch or an action in a specific screen coordinate.

**Comment by rom1v** [comment] 2023-10-27 23:08
Keyboard mapping: duplicate of #712 

(Note that if your computer supports touch input, multitouch is correctly forwarded to the device.)

**Closed by rom1v** 2023-10-27 23:08 UTC

**Comment by eaphone** [comment] 2025-02-07 08:21
hi, rom1v. it seems multitouch is not work with mouse uhid mode. i assume that mouse uhid is simulating a mouse device to the device, so the touch event is not situatable. is that possible also simulating multitouch device to support multitouch event? it is useful for only control mode
