### ISSUE TITLE
Push file failed

### ISSUE THREAD

**Issue by mofazhe** [Genymobile/scrcpy#3423] opened 2022-08-06 06:12 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: pixel 3
 - Android version: 11

**Describe the bug**
push file failed
such as file path: C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt

Here is the output of the console: 
```
2022-08-06 14:00:53.464 - logger[INFO] - scrcpy_base_thread.py[44](run) - ScrcpyThread: INFO: Request to push C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt
2022-08-06 14:00:53.469 - logger[INFO] - scrcpy_base_thread.py[44](run) - ScrcpyThread: INFO: Pushing C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt...
2022-08-06 14:00:53.498 - logger[INFO] - scrcpy_base_thread.py[44](run) - ScrcpyThread: C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt: 1 file pushed, 0 skipped. 0.2 MB/s (46 bytes in 0.000s)
2022-08-06 14:00:53.502 - logger[INFO] - scrcpy_base_thread.py[44](run) - ScrcpyThread: adb: error: failed to copy 'C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt' to '/sdcard/Download/.': remote couldn't create file: Is a directory
2022-08-06 14:00:53.517 - logger[INFO] - scrcpy_base_thread.py[44](run) - ScrcpyThread: ERROR: "adb push" returned with value 1
2022-08-06 14:00:53.517 - logger[INFO] - scrcpy_base_thread.py[44](run) - ScrcpyThread: ERROR: Failed to push C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt to /sdcard/Download/
```

I think that executing adb push command needs to set the target file name, which will help to be compatible with Chinese path files with spaces.
for example: 
```
adb push "C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt" "/sdcard/Download/哈 哈哈.txt"
```
top commond should be used instead of bottom commond
```
adb push "C:\Home\Downloads\LANDrop\哦 哦\哈 哈哈.txt" /sdcard/Download/
```

**Comment by rom1v** [comment] 2022-08-06 13:30
Thank you for your report. This is a duplicate of #2184.

This is an `adb` bug, and IMO it should be fixed there. Moreover, apparently, always passing the filename as a workaround does not always work: https://github.com/Genymobile/scrcpy/issues/2184#issuecomment-794851513

**Closed by rom1v** 2022-08-06 13:30 UTC
