### ISSUE TITLE
Copying and Pasting from PC to Android

### ISSUE THREAD

**Issue by 9812ga98sd** [Genymobile/scrcpy#509] opened 2019-04-25 09:51 UTC
Before upgrading to 1.6 and then 1.8 (i think) I used to be able to copy and paste from my PC to phones easily. I would copy text from my PC and then paste and all the text  would be pasted.

eg. 

12312323
123123312
123132132
123123

However now when I copy and paste it only pastes 1 line and stops at the carriage return. 

eg
12312323

This is a new issue as it was working well before. I have tried multiple ways to resolve the issue, select all etcetc, but to no avail. I have had to email text to my phone to get it there. 

Do you have the older versions available (for PC) so I can test if they work correctly? Again this was working correctly but after upgrading it stopped working. 

I am using multiple devices with android and they all exhibit the same, new, behaviour

**Comment by rom1v** [comment] 2019-04-25 11:24
I just tested, it works here.

Where do you paste it on your device? Is it in a multirows text view?

> Do you have the older versions available (for PC) so I can test if they work correctly?

All versions are available in [releases](https://github.com/Genymobile/scrcpy/releases).

**Comment by 9812ga98sd** [comment] 2019-04-25 15:30
Windows 10
1. Open notepad.
2. Type:

asdasdasd
asd
asd
as
da
sda

3. Open scrpy to phone. 
4. Open gmail on phone.
5. Create New email.
6. Switch to notepad on PC, copy text
7. Switch to phone, paste text. It pastes what was copied from the phone and not from the PC.

I have tried it now on 2 phone.

I will try the older versions and update you.

**Comment by 9812ga98sd** [comment] 2019-04-25 15:48
v1.8 
1. Copy text from PC.
2. Click paste in the phone it pastes from the phone clipboard.
3. Type Ctrl + V on my PC keyboard pastes only the first line from the Clip Board
asdasdasdasd
ad
as
s
dda

only  asdasdasdasd is pasted. Same for V1.3, Same for V1.5.

So CTRL + V pastes but stops at the CR/LF 


V.13
1. Copy text from PC.
2. Click paste in the phone it pastes from the phone clipboard.
3. Type Ctrl + V on my PC keyboard pastes only the first line from the Clip Board

**Comment by rom1v** [comment] 2019-04-25 15:50
Oh, maybe it's related to CR (`\r`) then, because it works on Linux. In that case we'll need to replace `\r\n` by `\n`.

I'll try to test on Windows.

**Comment by 9812ga98sd** [comment] 2019-04-25 15:51
I tested turning Windows 10 clipboard history on and off and it made no difference. I will try and on unix.

**Comment by 9812ga98sd** [comment] 2019-04-25 15:58
Have now tested on another computer connected to amazon fire device.  Windows 10, same behaviour. Only First line is pasted.
This is very odd as when I first started using scrcpy is pasted the full text. 
using cygwin and vi on windows 10.
Copied text from VI:

sdasda
sd
ad
a
das
dad
s
ads

only sdasda is pasted. This may suggest it is not a CR/LF issue.... Though it is still going through the windows clipboard.

**Comment by lpful** [comment] 2019-04-27 15:15
![ARDC](https://user-images.githubusercontent.com/50052327/56851458-228dff00-6942-11e9-96d4-cb1819e25725.gif)
You may try ARDC, [https://files.cnblogs.com/files/we-hjb/ARDC%28B1413%29.7z](https://files.cnblogs.com/files/we-hjb/ARDC%28B1413%29.7z)

**Comment by garbb** [comment] 2019-05-17 18:26
Scrcpy 1.8 x64, windows 7, I have the same issue
It does appear to be an issue with `/r`
![2019-05-17_11-23-30](https://user-images.githubusercontent.com/4453789/57948412-6ebfc580-7896-11e9-9ffd-dc1f7d2352ff.gif)

**Comment by rom1v** [comment] 2019-05-17 18:40
Thank you for your test :+1:

This confirms the cause of the a bug.

Basically, the easiest solution is to continue even if a char fails, i.e. not returning here:
https://github.com/Genymobile/scrcpy/blob/v1.8/server/src/main/java/com/genymobile/scrcpy/EventController.java#L102

In that case, I don't know what to return (was it a success or a failure if some of the chars fail?). I would say return true if at least one worked.

Anyway, these boolean return values are never used (but it's weird to not return a success status).

If someone want to try to fix and open a PR, please go ahead. Otherwise, I'll do it later.

**Comment by 9812ga98sd** [comment] 2019-05-17 19:40
Great :-=) I'm glad it wasn't just me and we found the cause. I use this a lot to copy notes from my PC to phone so its useful.

**Comment by npes87184** [comment] 2019-05-18 00:10
I will check it and open a PR today.

**Comment by rom1v** [comment] 2019-05-20 07:06
Fixed by #542.

**Closed by rom1v** 2019-05-20 07:06 UTC
Labels: bug, copy_paste, good first issue, input events

**Comment by 9812ga98sd** [comment] 2019-05-20 10:25
I am new to Git hub, how do I apply the fix? Is it rolled into the new downloads or will a new revision be released?

**Comment by npes87184** [comment] 2019-05-20 12:33
@9812ga98sd 

Wait for new version to be released, you can grab release file [here](https://github.com/Genymobile/scrcpy/releases).
Or build the server by yourself, you can refer to [BUILD.md](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md) for more information.

Thanks.

**Comment by Splarkszter** [comment] 2023-03-27 03:44
Doesn't work even with 2.0 installed.

Linux Mint ---> Samsung Android 10

**Comment by mora145** [comment] 2023-03-30 19:02
Hey, having the same issue. Last version of scrcpy and Android 9.

**Comment by bolovanos** [comment] 2023-04-13 10:27
Hi there - copying from win 11 64bit 22H2, to A9 does not work for scrcpy 64bit 2.0 / 1.25. Vice versa does.

**Comment by rom1v** [comment] 2023-04-13 10:30
This is device-specific: d5f059c7cbef7d13889086670716d9f33f805dc4

If your device does not behave as expected, you can use `--legacy-paste`.
