### ISSUE TITLE
Capture the camera

### ISSUE THREAD

**Issue by haampie** [Genymobile/scrcpy#409] opened 2019-01-24 13:19 UTC
Since #232 was closed, let me open an issue here.

In an application with a smart glass I'm looking for a way to have both the camera and ui displayed on another screen. What is required to get that working? (Not an android expert)

**Comment by metaa** [comment] 2019-01-24 14:32
Without knowing too much about how the scrcpy server works inside Android, I'd believe it would require a helper app that needs to be given access to the camera by the user.

**Comment by rom1v** [comment] 2019-01-24 15:08
> I'd believe it would require a helper app that needs to be given access to the camera by the user.

I think we can get access directly from the scrcpy server "app".

Probably by using [android.hardware.camera2](https://developer.android.com/reference/android/hardware/camera2/package-summary) and write to the [input surface provided by the codec].

**Comment by haampie** [comment] 2019-01-24 15:13
Yes, exactly, that was my thinking as well after some Googling. But unfortunately I'm not sure how to set it all up (yet).

**Comment by haampie** [comment] 2019-01-24 15:41
Maybe it does not make sense to use `scrcpy` at all for this task.

A simpler solution is to use an existing rstp streaming app over wifi.

Thanks for the project tho! Very helpful, also when accessing a device that has a poor UI like smart glasses.

**Comment by rom1v** [comment] 2020-04-09 20:18
> Maybe it does not make sense to use scrcpy at all for this task.

An option to mirror the camera instead of the device would be great!

Closing as duplicate of #241.

**Closed by rom1v** 2020-04-09 20:18 UTC
Labels: camera, feature request
