### ISSUE TITLE
Wrong icon in the taskbar on Windows

### ISSUE THREAD

**Issue by BraveHL** [Genymobile/scrcpy#2815] opened 2021-11-22 01:55 UTC
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version: [e.g. 1.12.1]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model:
 - Android version: [e.g. 10]

**Describe the bug**

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
```

Please do not post screenshots of your terminal, just post the content as text instead.

After scrcyp runs, scrcy.exe displays a bad icon on the taskbar, and the user cannot modify it. I hope you can change it into the icon icon in the software package as soon as possible. In addition, it is recommended that you launch windows Microsoft Store as soon as possible. Now Microsoft application store supports developers to upload Win32 programs.

![V%W6FZC29A@I{~QQERB)F3T](https://user-images.githubusercontent.com/22335503/142789724-8ab4bcb2-9fd5-4435-814c-061b9867df26.png)

**Comment by rom1v** [comment] 2021-11-22 18:13
I could not reproduce. The expected icon is in the taskbar for me.

Anyway, scrcpy just set the icon to SDL, to either it is a SDL bug or a window manager (Windows) bug (Window managers typically cache icons, and don't always update them correctly when they change).

**Comment by BraveHL** [comment] 2021-11-23 01:31
> I could not reproduce. The expected icon is in the taskbar for me.
> 
> Anyway, scrcpy just set the icon to SDL, to either it is a SDL bug or a window manager (Windows) bug (Window managers typically cache icons, and don't always update them correctly when they change).

![image](https://user-images.githubusercontent.com/22335503/142958910-f75c793a-f2f6-4ad6-b929-fa0d717eb148.png)
The icon of scrcpy.exe itself is abnormal, and there is no cache or error

**Comment by BraveHL** [comment] 2021-11-23 01:32
![image](https://user-images.githubusercontent.com/22335503/142959103-ab066368-34ec-46fb-9ffc-e0ec101cbd7f.png)

**Comment by BraveHL** [comment] 2021-11-23 01:41
What I hope is that in the next version, you can change the icon of scrcpy.exe to a more beautiful icon instead of the bad looking icon now

**Comment by rom1v** [comment] 2021-11-23 06:26
Like I said in my [comment](https://github.com/Genymobile/scrcpy/issues/2815#issuecomment-975792234), it works for me:
![windows_scrcpy](https://user-images.githubusercontent.com/543275/142979355-fbc45625-841f-4ff8-a3aa-da2b20e71635.png)

And if it does not work, it's either SDL or Windows, scrcpy just pass the icon to SDL.

**Comment by BraveHL** [comment] 2021-11-23 07:19
> 

I don't quite understand what you said. Can you tell me the specific operation steps? It's best to have screenshots. Thank you

**Comment by rom1v** [comment] 2021-11-23 07:29
Nothing to do, it's a bug in your Windows or its interaction with SDL, nothing scrcpy can fix.

**Comment by BraveHL** [comment] 2021-11-23 08:06
> Nothing to do, it's a bug in your Windows or its interaction with SDL, nothing scrcpy can fix.

I downloaded the compressed package of the software, decompressed it, and then directly ran scrcpy.exe without installing. Is this related to this problem?

**Comment by BraveHL** [comment] 2021-11-23 08:17
> Nothing to do, it's a bug in your Windows or its interaction with SDL, nothing scrcpy can fix.

I have changed more than three computers and have this problem. I don't think it's a rare problem

**Comment by Dhyfer1** [comment] 2021-12-01 13:52
@rom1v  I have the same problem. In my case I am using Windows 11 and scrcpy shows the icon correctly, but when scrcpy is open and I click on its icon to pin it to the taskbar, the icon changes by itself to the one shown in the first image of this issue.

**Comment by rom1v** [comment] 2021-12-01 14:17
I have no idea why. Could you try to replace the `icon.png` with a smaller image (128x128, without transparency), just to test?

There are many posts about "windows wrong icon in taskbar" on the Internet: https://www.google.com/search?q=windows+wrong+icon+in+taskbar

If you find out why, please explain :)

**Comment by BraveHL** [comment] 2021-12-07 07:51
> I have no idea why. Could you try to replace the `icon.png` with a smaller image (128x128, without transparency), just to test?
> 
> There are many posts about "windows wrong icon in taskbar" on the Internet: https://www.google.com/search?q=windows+wrong+icon+in+taskbar
> 
> If you find out why, please explain :)

You can add a shortcut in the next version of the compressed package. The shortcut uses the ICO icon converted from PNG to open the software with the shortcut. This may solve these problems from another angle. Now I just create a shortcut and modify its icon, but it's too unfriendly to users

![QRBV 8PARWQVEMXCK G`HG](https://user-images.githubusercontent.com/22335503/144988358-11e3d5d5-6998-4af0-9fc1-60ae2526912d.png)

**Comment by BraveHL** [comment] 2021-12-07 08:04
> I have no idea why. Could you try to replace the `icon.png` with a smaller image (128x128, without transparency), just to test?
> 
> There are many posts about "windows wrong icon in taskbar" on the Internet: https://www.google.com/search?q=windows+wrong+icon+in+taskbar
> 
> If you find out why, please explain :)

In addition, it is not only on the taskbar that the icon displays an exception, but the icon of exe software in the compressed package looks abnormal

**Comment by rom1v** [comment] 2021-12-07 08:11
@BraveHL The exe itself does not have any icon. A separate png icon is loaded.

**Comment by rom1v** [comment] 2021-12-07 08:13
@BraveHL The exe itself does not have any icon. A separate png icon is loaded.

If someone wants to contribute to also set an icon to the .exe: https://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable

**Comment by BraveHL** [comment] 2021-12-07 08:29
> 

I can send the ICO file and you can change it. I won't develop this kind of software. This is the ICO format file converted by icon.png
[icon.zip](https://github.com/Genymobile/scrcpy/files/7666756/icon.zip)

**Comment by BraveHL** [comment] 2021-12-07 08:29
> @BraveHL The exe itself does not have any icon. A separate png icon is loaded.
> 
> If someone wants to contribute to also set an icon to the .exe: https://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable

I can send the ICO file and you can change it. I won't develop this kind of software. This is the ICO format file converted by icon.png
[icon.zip](https://github.com/Genymobile/scrcpy/files/7666765/icon.zip)

**Comment by rom1v** [comment] 2021-12-09 22:19
Please try these binaries:
 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2815/1/scrcpy.exe) _sha256:7f327eb0f3c7a8650a21e469d5fe664b0a0b4a393d7d3f40707bc737877ab700_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2815/1/scrcpy-server) _sha256:7e24086399ce9a8e04c98075481ce7eff33ba600f378d5c0bc9a1003036f3468_

**Comment by rom1v** [comment] 2021-12-10 18:52
Thank you for your feedback.

So it seems the initial issue is also fixed by cfcbc2ac218612b2e9d2322ceb98ec99d7cd9381. :tada:

**Closed by rom1v** 2021-12-10 18:52 UTC
