### ISSUE TITLE
Remote support

### ISSUE THREAD

**Issue by gadgadskiy** [Genymobile/scrcpy#89] opened 2018-03-22 14:23 UTC
Hi!
Do you support any remote abilities to use scrcpy?
For example I have PC with connected android device and and another PC in the same local network. Can I view this device via scrcpy from another PC?

**Comment by rom1v** [comment] 2018-03-22 14:24
Duplicate of https://github.com/Genymobile/scrcpy/issues/5.

See https://www.genymotion.com/blog/open-source-project-scrcpy-now-works-wirelessly/.

**Closed by rom1v** 2018-03-22 14:24 UTC
