### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by goamn** [Genymobile/scrcpy#293] opened 2018-10-12 00:38 UTC
Hi, I was wondering if it's possible to add Arabic language support?

**Comment by rom1v** [comment] 2018-10-12 07:46
If someone wants to add internationalization support, why not. Will be difficult to keep translations up-to-date through.

Related: https://github.com/Genymobile/scrcpy/issues/160

**Comment by goamn** [comment] 2018-10-12 14:07
Oh sorry I meant support for the keyboard via typing on the computer keyboard.

**Comment by rom1v** [comment] 2018-10-12 14:11
@goamn OK, thank you for the clarification.

Then, this is a duplicate of https://github.com/Genymobile/scrcpy/issues/37. I'm closing this one.

**Closed** 2018-10-12 14:33 UTC
Labels: input events

**Comment by mhd1433** [comment] 2023-09-06 01:54
Hello, is it possible to add the Arabic language to the keyboard?

**Comment by mhd1433** [comment] 2023-09-06 01:54
Hello, is it possible to add the Arabic language to the keyboard?
