### ISSUE TITLE
java.lang.reflect.InvocationTargetException on Android 12 preview.

### ISSUE THREAD

**Issue by ssangjin** [Genymobile/scrcpy#2179] opened 2021-03-08 06:41 UTC
I ran scrcpy on Pixel5(Android 12 preview installed) and I got exception below.
Android 12 Buildno : SPP1.210122.022

$ scrcpy 
2021-03-08 15:38:53.221 scrcpy[85124:20049204] INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.17_1/share/scrcpy/scrcpy-server: 1 file pushed. 7.0 MB/s (34930 bytes in 0.005s)
[server] INFO: Device: Google Pixel 5 (Android 11)
2021-03-08 15:38:53.457 scrcpy[85124:20049204] INFO: Renderer: metal
2021-03-08 15:38:53.459 scrcpy[85124:20049204] INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3067)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2147)
	... 9 more

**Comment by rom1v** [comment] 2021-03-08 06:46
Duplicate of #2129.

**Closed by rom1v** 2021-03-08 06:46 UTC

**Comment by oEduardBarbosa** [comment] 2022-09-03 17:01
conseguiu resolver?
