### ISSUE TITLE
Do you have any plans to support Android Wear OS?

### ISSUE THREAD

**Issue by wangmoo** [Genymobile/scrcpy#2092] opened 2021-02-05 06:20 UTC
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi~
First of all, I would like to thank you for releasing a good program for free.
 I want to request something.
It is the same as the title.
When I tried it, the log was as below.

2021-02-05 15:14:26.430 9256-9270/? E/ACodec: Unable to instantiate a encoder for type 'video/avc' with err 0xfffffffe.
2021-02-05 15:14:26.430 9256-9270/? E/ACodec: signalError(omxError 0xfffffffe, internalError -2)
2021-02-05 15:14:26.430 9256-9269/? E/MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
2021-02-05 15:14:26.435 9256-9256/? E/AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
    java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1786)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1752)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:154)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:72)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
2021-02-05 15:14:26.435 9256-9256/? E/scrcpy: Exception on thread Thread[main,5,main]
    java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1786)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1752)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:154)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:72)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
        at com.genymobile.scrcpy.Server.main(Server.java:225)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)

Is it possible?

P.S I'm sorry. I can't speak english very well.

**Comment by rom1v** [comment] 2021-02-05 06:26
Your device does not have any H.264 encoder, so it can't work.

Duplicate of #82.

**Closed by rom1v** 2021-02-05 06:26 UTC
