### ISSUE TITLE
SDL_WINDOW_ALWAYS_ON_TOP undeclared error

### ISSUE THREAD

**Issue by JayasankarV** [Genymobile/scrcpy#432] opened 2019-02-16 08:41 UTC
While executing ninja command, though build is successful, it stops by giving this error.

`[2/4] Compiling C object 'app/a172ced@@scrcpy@exe/src_screen.c.o'.
FAILED: cc -Iapp/a172ced@@scrcpy@exe -Iapp -I../app -I../app/src -I/usr/include/x86_64-linux-gnu -I/usr/include/SDL2 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O3 -D_REENTRANT  -MD -MQ 'app/a172ced@@scrcpy@exe/src_screen.c.o' -MF 'app/a172ced@@scrcpy@exe/src_screen.c.o.d' -o 'app/a172ced@@scrcpy@exe/src_screen.c.o' -c ../app/src/screen.c
../app/src/screen.c: In function ‘screen_init_rendering’:
../app/src/screen.c:159:25: error: ‘SDL_WINDOW_ALWAYS_ON_TOP’ undeclared (first use in this function)
         window_flags |= SDL_WINDOW_ALWAYS_ON_TOP;
`

**Comment by rom1v** [comment] 2019-02-16 08:56
Thank you for your report. It is available only since SDL 2.0.5: https://wiki.libsdl.org/SDL_WindowFlags

So we need to use ifdefs to disable the feature completely if SDL <= 2.0.5.

**Comment by rom1v** [comment] 2019-02-16 09:19
It's weird though, because you compile for Windows, libSDL should be up to date (either in MSYS2 or when you cross-compile from Linux).

Do you compile from [MSYS2](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#in-msys2)?

**Comment by JayasankarV** [comment] 2019-02-16 09:21
No.  I use an Ubuntu machine, 16.04. I followed the steps for that only.

**Comment by rom1v** [comment] 2019-02-16 09:23
Oh, ok, sorry, `scrcpy@exe` was misleading, I thought it was on Windows :smile: 

Then it's ok. :wink:

What is the output of `apt-get show libsdl2-2.0-0`?

**Comment by JayasankarV** [comment] 2019-02-16 09:25
Am not able to get any output!

**Comment by rom1v** [comment] 2019-02-16 09:26
Sorry, `apt-cache show libsdl2-2.0-0`.

**Comment by JayasankarV** [comment] 2019-02-16 09:29
Got it. There is a lot of information. Shall i paste it here?
Or are you looking at some specific information?

**Comment by JayasankarV** [comment] 2019-02-16 09:34
![screenshot from 2019-02-16 15-00-11](https://user-images.githubusercontent.com/40686500/52897537-cdc06080-31fb-11e9-8830-6cd3aee38054.png)

**Comment by JayasankarV** [comment] 2019-02-16 09:48
If there was only one SDL flag used, i would have commented it out. But i can find few others as well. That's why made an issue. Anyways, i will try removing it. :blush:

**Comment by JayasankarV** [comment] 2019-02-16 10:01
Commenting out worked actually. 'ninja install' command is failing with a file not found exception. But am able to use without installing.
Thank you for the quick support. :smiley:

**Comment by rom1v** [comment] 2019-02-16 14:24
Fixed on `master`.

**Closed by rom1v** 2019-02-16 14:24 UTC
Labels: bug, build

**Comment by npes87184** [comment] 2019-02-18 02:53
Thank you for your quick fixing for this regression.
