### ISSUE TITLE
Problems with stream sidequest on meta quest 2

### ISSUE THREAD

**Issue by dlsasster** [Genymobile/scrcpy#5258] opened 2024-09-02 14:54 UTC
When I start streaming, the sound from the headset appears on the pg, but when I put on my headset, there is no sound there and if you click on the menu, then there are some unexpected sounds, hisses, like that

**Comment by rom1v** [comment] 2024-09-02 14:56
Duplicate of #4083.

**Closed by rom1v** 2024-09-02 14:56 UTC
