### ISSUE TITLE
Not working when installed from winget

### ISSUE THREAD

**Issue by MominRaza** [Genymobile/scrcpy#4956] opened 2024-05-30 05:33 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 2.4
 - installation method: winget
 - device model: Dell Precision 7680
 - Android version: 14

**Describe the bug**
I installed scrcpy from winget, on running `scrcpy` cmmand it is showing `SDL2.dll`, `avcodec-60.dll`, `avformat-60.dll` and `avutil-58.dll` not found error.

```
PS C:\Users\jahmad4> winget install Genymobile.scrcpy
Found scrcpy [Genymobile.scrcpy] Version 2.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "scrcpy"
Successfully installed
PS C:\Users\jahmad4> scrcpy
```

![image](https://github.com/Genymobile/scrcpy/assets/42776853/f189622b-69a9-47ad-aee5-e896472efafd)
![image](https://github.com/Genymobile/scrcpy/assets/42776853/c624d352-cc5f-4454-8f63-88d499b0572f)
![image](https://github.com/Genymobile/scrcpy/assets/42776853/b5d183ec-9c9d-489f-bda0-05e39356d967)
![image](https://github.com/Genymobile/scrcpy/assets/42776853/bb39d23d-6c3e-4411-aed8-45db8b550b38)

**Comment by rom1v** [comment] 2024-05-30 06:23
Duplicate of:
 - https://github.com/Genymobile/scrcpy/issues/4027
 - https://github.com/Genymobile/scrcpy/issues/4389

I will remove the suggestion to install scrcpy from winget.

**Closed by rom1v** 2024-05-30 06:23 UTC

**Comment by rom1v** [comment] 2024-05-30 11:56
@MominRaza The issue was already reported. Follow links in https://github.com/Genymobile/scrcpy/issues/4389#issuecomment-1977887150
