### ISSUE TITLE
ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: 找不到元素。

### ISSUE THREAD

**Issue by ayw** [Genymobile/scrcpy#3907] opened 2023-04-10 05:38 UTC
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10 x86/x64
 - scrcpy version: 2.0
 - installation method:  Windows release
 - device model: telpo m1
 - Android version: 11

**Describe the bug**
run scrcpy error 

```
[server] INFO: Device: QUALCOMM M1 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 720x1440
ERROR: Could not open audio device: WASAPI can't find requested audio endpoint: 找不到元素。
ERROR: Demuxer error
WARN: Killing the server...
```

**Comment by rom1v** [comment] 2023-04-10 08:20
See https://github.com/Genymobile/scrcpy/issues/3856#issuecomment-1482911664.

Duplicate of #3825.

**Closed by rom1v** 2023-04-10 08:20 UTC
