### ISSUE TITLE
Scrcpy open and close in few sec 

### ISSUE THREAD

**Issue by harsh2501** [Genymobile/scrcpy#1884] opened 2020-11-05 03:19 UTC
- [ yes ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [yes ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows.]
 - scrcpy version: [1.16]
 - installation method: [scoop.]
 - device model:redmi note 7 pro
 - Android version: [ 10]

**Describe the bug**
When I run scrcpy by giving the command scrcpy it open and close in 5-6sec and I am unable to control my device form my pc. 

No error is displayed and and logcat  not empty it fill won't very large Statment that I can't past here the comment box is not accepting that much large statment (and `adb logcat` if relevant).

```
Microsoft Windows [Version 10.0.17763.107]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Prity> scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
1051 KB/s (33622 bytes in 0.031s)
[server] INFO: Device: Xiaomi Redmi Note 7 Pro (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
```

Please do not post screenshots of your terminal, just post the content as text instead.

**Comment by rom1v** [comment] 2020-11-05 07:11
Duplicate of #1872.

**Closed by rom1v** 2020-11-05 07:11 UTC
