### ISSUE TITLE
Blurry icons when window resized

### ISSUE THREAD

**Issue by telegramcore** [Genymobile/scrcpy#197] opened 2018-07-14 19:08 UTC
hi romain! How can I change the resolution?

**Comment by rom1v** [comment] 2018-07-14 20:38
scrcpy -m1024

https://github.com/Genymobile/scrcpy/blob/master/README.md#run

**Comment by RedMoonOTInetwork** [comment] 2018-07-14 21:02
Thanks

**Comment by RedMoonOTInetwork** [comment] 2018-07-16 16:40
![cattura 000277](https://user-images.githubusercontent.com/37411589/42771389-554814fe-8927-11e8-8ec4-1928e644856b.png)


the notification icons in the status bar are blurry :c how can i to fix it?

**Comment by rom1v** [comment] 2018-07-16 16:43
If you decrease the resolution/definition, that's expected I guess. Does it happen without changing definition?

**Comment by RedMoonOTInetwork** [comment] 2018-07-16 16:50
no

**Comment by RedMoonOTInetwork** [comment] 2018-07-16 16:51
how do I get it back by default?

**Comment by RedMoonOTInetwork** [comment] 2018-07-17 21:30
Ah and anyway the icons have checked and are blurred in the status bar even without making changes

**Comment by RedMoonOTInetwork** [comment] 2018-07-17 21:48
Tomorrow i try thanks

**Comment by RedMoonOTInetwork** [comment] 2018-07-18 14:56
Ok i tried: I'm not blurry if I give that command but it increases the size of the screen too much and I'm forced to reduce the window, so they appear again like [here](https://github.com/Genymobile/scrcpy/issues/197#issuecomment-405309398)

**Comment by gladiatorgiftson** [comment] 2020-03-02 07:21
I think i found what happening this but i am not sure 
![Screenshot (25)](https://user-images.githubusercontent.com/42843422/75653749-31d98980-5c84-11ea-8e73-cec156d563cd.png)

windows setting the resolution to default computer screen resolution

**Comment by rom1v** [comment] 2020-04-09 19:34
Duplicate of #40.

**Closed by rom1v** 2020-04-09 19:34 UTC
Labels: quality, question
