### ISSUE TITLE
Multiple keyboards

### ISSUE THREAD

**Issue by UnixRonin** [Genymobile/scrcpy#930] opened 2019-11-17 18:02 UTC
I've been using this for a while now and it works fantastically.  There's just one shortcoming I've noticed that is probably only an issue because of some of the ways I use it.

I use language learning apps on my phone.  I'm studying several languages including Russian.  To this end, I have two keyboards connected to my desktop, one configured for US English with some keymap changes that allow me to also use it for Norsk and Islenska, and the other configured with a Russian keymap.

Now, this works fine in typical desktop applications, web pages, etc.  But when I type in a language app on the phone, via scrcpy, on the Russian keyboard, nothing happens.  It seems scrcpy is not aware of the second keyboard.

Does this seem like something that could be readily fixed?

**Comment by rom1v** [comment] 2019-11-17 20:15
> It seems scrcpy is not aware of the second keyboard.

If you type Russian (non-ASCII) characters, it is "expected" not to work: see https://github.com/Genymobile/scrcpy/issues/37 (even without multiple keyboards)

**Comment by UnixRonin** [comment] 2019-11-17 21:37
Aaaaah.  Oh, well....

**Comment by rom1v** [comment] 2020-04-09 19:36
Closing as duplicate of #37.

**Closed by rom1v** 2020-04-09 19:36 UTC
Labels: keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:40
Please test #1426 (works on Android >= 7).
