### ISSUE TITLE
Virtual Display Rotation Listener Problem

### ISSUE THREAD

**Issue by mengyanshou** [Genymobile/scrcpy#5428] opened 2024-10-31 13:53 UTC
## Environment

 - **OS:** [Any]
 - **Scrcpy version:** [dev ref]
 - **Installation method:** [git clone and compile]
 - **Device model:**
 - **Android version:** []

## Describe the bug

i notice this code in ScreenCapture.java
```java
    @Override
    public void init() {
        if (displayId == 0) {
            rotationWatcher = new IRotationWatcher.Stub() {
                @Override
                public void onRotationChanged(int rotation) {
                    Ln.i("Display rotated, request reset");
                    requestReset();
                }
            };
            Ln.i("registerRotationWatcher display " + displayId);
            ServiceManager.getWindowManager().registerRotationWatcher(rotationWatcher, displayId);
        }
    }
```
when create Virtual Display use this flag
```java
VIRTUAL_DISPLAY_FLAG_ROTATES_WITH_CONTENT
```
and launch some video player, the display can be rotated actually
but scrcpy screen cannot change render size when virtual display rotated 
then i comment out this part of the code

```java
    @Override
    public void init() {
            rotationWatcher = new IRotationWatcher.Stub() {
                @Override
                public void onRotationChanged(int rotation) {
                    Ln.i("Display rotated, request reset");
                    requestReset();
                }
            };
            Ln.i("registerRotationWatcher display " + displayId);
            ServiceManager.getWindowManager().registerRotationWatcher(rotationWatcher, displayId);
        }
```
every thing work fine~

i think maybe this is a little problem, can i pull a pr to resolve this?
I need to make sure it doesn't cause other problems~

**Comment by rom1v** [comment] 2024-10-31 14:01
In #5370, a new virtual display could not be rotated.

If you can make it work, sure, please open a new PR :sunglasses: 

Please base your work on #5415 (which I will merge soon).

**Comment by mengyanshou** [comment] 2024-10-31 16:40
I tested three devices: the Xiaomi 14, Meizu 21, and OPPO foldable screen. After creating a virtual display on each, I opened a video player, and all of them were able to rotate normally. The rotationWatcher also received callbacks as expected.

**Comment by rom1v** [comment] 2024-10-31 17:01
> Why can't the virtual display be rotated?

Currently, if you run `scrcpy --new-display` on `dev` in portrait mode, then start an app which requires a landscape mode, then the virtual display is not rotated.

> i notice this code in ScreenCapture.java

But `ScreenCapture` is not used when `--new-display` is passed.

What did you test exactly? And what changes did you make so that it works?

**Comment by eiyooooo** [comment] 2024-10-31 17:26
> Currently, if you run `scrcpy --new-display` on `dev` in portrait mode, then start an app which requires a landscape mode, then the virtual display is not rotated.

This may be related to some incorrectly set flags.

> > i notice this code in ScreenCapture.java

This issue is not specifically linked to `scrcpy --new-display`. If any other virtual display that supports rotation is rotated, scrcpy currently does not recognize this rotation.

**Comment by rom1v** [comment] 2024-10-31 19:30
> This may be related to some incorrectly set flags.

Not only, we must listen to display changed / rotation events for the virtual display, and restart the encoding. But when I tried, it didn't work correctly (I could not receive the rotation or "display changed" events from virtual displays).

Now (with #5415 merged), a rotation watcher is only added for early versions of Android 14. I think it should be ok to apply that change anyway:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/video/ScreenCapture.java b/server/src/main/java/com/genymobile/scrcpy/video/ScreenCapture.java
index e9ab8d263..a4440b739 100644
--- a/server/src/main/java/com/genymobile/scrcpy/video/ScreenCapture.java
+++ b/server/src/main/java/com/genymobile/scrcpy/video/ScreenCapture.java
@@ -240,7 +240,6 @@ public class ScreenCapture extends SurfaceCapture {
     }
 
     private void registerDisplayListenerFallbacks() {
-        if (displayId == 0) {
             rotationWatcher = new IRotationWatcher.Stub() {
                 @Override
                 public void onRotationChanged(int rotation) {
@@ -251,7 +250,6 @@ public class ScreenCapture extends SurfaceCapture {
                 }
             };
             ServiceManager.getWindowManager().registerRotationWatcher(rotationWatcher, displayId);
-        }
 
         // Build.VERSION.SDK_INT >= AndroidVersions.API_29_ANDROID_10 (but implied by == API_34_ANDROID 14)
         displayFoldListener = new IDisplayFoldListener.Stub() {
```

(but in practice, I never receive events for virtual displays, and I don't have any device with a secondary non-virtual display)

**Comment by rom1v** [comment] 2024-10-31 21:05
In fact, in `NewDisplayCapture`, I can register a DisplayListener on the virtual display (so it will work for all devices except on Android 14_r1 to 14_r29).

I'll check again for a rotation watcher on the new codebase.

**Comment by rom1v** [comment] 2024-11-01 09:30
> a rotation watcher is only added for early versions of Android 14. I think it should be ok to apply that change anyway

I added the `if (displayId == 0) {}` in 874eaec487369f7fcaa9ed8c5f85569659565d4f, without good reasons. I'll remove it.

**Comment by rom1v** [comment] 2024-11-02 20:28
On current `dev` branch (currently `f08a6d86c5d84aa48c1c197d8f92f322768515cb`), a virtual display may not be rotated.

To observe it, run:

```
scrcpy --new-display=450x800
```

Then run an app which requires a landscape mode (or rotate any app using <kbd>MOD</kbd>+<kbd>r</kbd>): the new display window remains in portrait mode, with the content in landscape mode.

So far, everything works as expected (nothing has been done to handle rotation yet).


---

When the virtual display size changes, we can be notified via a `DisplayListener`.

In that case, we want to restart the encoding with `MediaCodec`, but keep the existing virtual display (not create a new one, like for screen capture, the current state would be lost).

I created a quick&dirty branch ([`newdisplay_resize`](https://github.com/Genymobile/scrcpy/commits/newdisplay_resize/)), where:
 - the encoding is reset on display changed
 - the virtual display is created only the first time (when `virtualDisplay == null`)
 - its output surface (the `MediaCodec` input surface) is updated every time a new encoding session is started

The problem is that it does not work correctly at all. The virtual display and media codec dimensions are correct, but the content is rotated and offset. I might have missed something.

@mengyanshou @eiyooooo @yume-chan if you have any idea to make virtual display rotation work, your help is welcome :)

---

Note that if you create a virtual display with `scrcpy --new-display`, keep the instance open, and mirror this display with a separate scrcpy instance (check the display id in the logs, or in `scrcpy --list-displays`):

```
scrcpy --display-id=ID_OF_THE_VIRTUAL_DISPLAY
```

then rotation works correctly (a new virtual display mirroring the source virtual display is created each time by `ScreenCapture`).

**Comment by yume-chan** [comment] 2024-11-03 10:30
I guess because the Surface is meant to be displayed on a physical screen, it's not rotated by system with the content. Only mirroring virtual displays are automatically rotated.

I also found that no matter whether the display changed event is used, touch inputs are not sent to the correct coordinates after rotation.

So I guess we may need to create another virtual display to mirror it (like you specified `--display-id=`) or do the rotation ourselves (which I don't know how to do it effectively)

**Comment by rom1v** [comment] 2024-11-03 11:11
> So I guess we may need to create another virtual display to mirror it

If we do this, we need a dummy surface for the source virtual display. Indeed, if we pass `null`, the mirrored virtual display is black:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
index 8f507fdf0..0b4e0e566 100644
--- a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
+++ b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
@@ -98,7 +98,7 @@ public class NewDisplayCapture extends SurfaceCapture {
                 }
             }
             virtualDisplay = ServiceManager.getDisplayManager()
-                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, surface, flags);
+                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, null, flags);
             virtualDisplayId = virtualDisplay.getDisplay().getDisplayId();
             Ln.i("New display: " + size.getWidth() + "x" + size.getHeight() + "/" + dpi + " (id=" + virtualDisplayId + ")");
         } catch (Exception e) {
```

So I tried:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
index 8f507fdf0..1f8d20699 100644
--- a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
+++ b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
@@ -9,6 +9,7 @@ import com.genymobile.scrcpy.util.Ln;
 import com.genymobile.scrcpy.wrappers.ServiceManager;
 
 import android.graphics.Rect;
+import android.graphics.SurfaceTexture;
 import android.hardware.display.DisplayManager;
 import android.hardware.display.VirtualDisplay;
 import android.os.Build;
@@ -97,8 +98,10 @@ public class NewDisplayCapture extends SurfaceCapture {
                              | VIRTUAL_DISPLAY_FLAG_DEVICE_DISPLAY_GROUP;
                 }
             }
+
+            Surface dummy = new Surface(new SurfaceTexture(0));
             virtualDisplay = ServiceManager.getDisplayManager()
-                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, surface, flags);
+                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, dummy, flags);
             virtualDisplayId = virtualDisplay.getDisplay().getDisplayId();
             Ln.i("New display: " + size.getWidth() + "x" + size.getHeight() + "/" + dpi + " (id=" + virtualDisplayId + ")");
         } catch (Exception e) {
```

With this change, if I run a first instance with `scrcpy --new-display`, and a second instance with `scrcpy --display-id=XXX`, then rotation works.

However, on my pixel 8, a virtual display created by `--new-display` is not impacted by the physical screen power (when I press POWER physically on the device), which is good. But a "mirroring" virtual display (when I launch using `--display-id=XXX`) is impacted: if I press POWER, then the virtual display also turns off, which is annoying.

On other devices, the physical screen power impacts both virtual displays created by `--new-display` and `--display-id` anyway…

**Comment by yume-chan** [comment] 2024-11-03 13:04
> On other devices, the physical screen power impacts both virtual displays created by `--new-display` and `--display-id` anyway…

On Android 13+, the `VIRTUAL_DISPLAY_FLAG_ALWAYS_UNLOCKED` flag should allow the virtual display to not be affected by device lockscreen.

https://github.com/Genymobile/scrcpy/blob/f08a6d86c5d84aa48c1c197d8f92f322768515cb/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java#L93

But on my Xiaomi Mi 11 running Android 13, inputs don't work when device is locked. I can't remember if it's the case when I was initially working on this feature.

---

After reading https://source.android.com/docs/core/graphics/arch-st#continuous_capture and https://developer.android.com/media/media3/transformer, OpenGL seems to be the best option to draw virtual display's Surface into MediaCodec's Surface with transformation.

**Comment by rom1v** [comment] 2024-11-03 15:07
> OpenGL seems to be the best option to draw virtual display's Surface into MediaCodec's Surface with transformation.

I opened a new issue with a (non-working) prototype: #5444.

**Comment by mengyanshou** [comment] 2024-11-05 15:21
> > So I guess we may need to create another virtual display to mirror it
> 
> If we do this, we need a dummy surface for the source virtual display. Indeed, if we pass `null`, the mirrored virtual display is black:
> 
> ```diff
> diff --git a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
> index 8f507fdf0..0b4e0e566 100644
> --- a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
> +++ b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
> @@ -98,7 +98,7 @@ public class NewDisplayCapture extends SurfaceCapture {
>                  }
>              }
>              virtualDisplay = ServiceManager.getDisplayManager()
> -                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, surface, flags);
> +                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, null, flags);
>              virtualDisplayId = virtualDisplay.getDisplay().getDisplayId();
>              Ln.i("New display: " + size.getWidth() + "x" + size.getHeight() + "/" + dpi + " (id=" + virtualDisplayId + ")");
>          } catch (Exception e) {
> ```
> 
> So I tried:
> 
> ```diff
> diff --git a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
> index 8f507fdf0..1f8d20699 100644
> --- a/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
> +++ b/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java
> @@ -9,6 +9,7 @@ import com.genymobile.scrcpy.util.Ln;
>  import com.genymobile.scrcpy.wrappers.ServiceManager;
>  
>  import android.graphics.Rect;
> +import android.graphics.SurfaceTexture;
>  import android.hardware.display.DisplayManager;
>  import android.hardware.display.VirtualDisplay;
>  import android.os.Build;
> @@ -97,8 +98,10 @@ public class NewDisplayCapture extends SurfaceCapture {
>                               | VIRTUAL_DISPLAY_FLAG_DEVICE_DISPLAY_GROUP;
>                  }
>              }
> +
> +            Surface dummy = new Surface(new SurfaceTexture(0));
>              virtualDisplay = ServiceManager.getDisplayManager()
> -                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, surface, flags);
> +                    .createNewVirtualDisplay("scrcpy", size.getWidth(), size.getHeight(), dpi, dummy, flags);
>              virtualDisplayId = virtualDisplay.getDisplay().getDisplayId();
>              Ln.i("New display: " + size.getWidth() + "x" + size.getHeight() + "/" + dpi + " (id=" + virtualDisplayId + ")");
>          } catch (Exception e) {
> ```
> 
> With this change, if I run a first instance with `scrcpy --new-display`, and a second instance with `scrcpy --display-id=XXX`, then rotation works.
> 
> However, on my pixel 8, a virtual display created by `--new-display` is not impacted by the physical screen power (when I press POWER physically on the device), which is good. But a "mirroring" virtual display (when I launch using `--display-id=XXX`) is impacted: if I press POWER, then the virtual display also turns off, which is annoying.
> 
> On other devices, the physical screen power impacts both virtual displays created by `--new-display` and `--display-id` anyway…

I have a small idea. I noticed that when using `scrcpy --new-display`, the `scrcpy-server` has implementations related to `NewDisplayCapture` and quite a bit of code supporting `new-display`.

What if we fully utilize the code for `scrcpy --display-id` to support `--new-display`?

1. If `scrcpy` receives the `--new-display` parameter, it creates a virtual display. At this point, we don't need to hold the `VirtualDisplay` instance, just its display ID.

2. Next, we use the created display ID to follow the logic of `scrcpy --display-id`. This should make screen rotation functional.

However, could this cause other issues? This is just a small idea of mine.

**Comment by rom1v** [comment] 2024-11-05 15:26
@mengyanshou That was the idea in https://github.com/Genymobile/scrcpy/issues/5428#issuecomment-2453387517 (I just played with 2 scrcpy instances for testing the idea). But I don't really link the idea of creating a display on a dummy Surface and mirroring that Surface (and as mentioned in the comment, there might be other impacts, like when pressing the POWER button).

**Comment by rom1v** [comment] 2024-11-11 09:14
Please test #5455.

**Comment by rom1v** [comment] 2024-11-15 21:02
Please test the new version in #5455.

**Comment by mengyanshou** [comment] 2024-11-16 20:40
> Please test the new version in #5455.

Roger that. I'll test and reply when I'm free

**Comment by Meoshiat** [comment] 2024-11-17 02:29
fuck you bitch

**Closed** 2024-11-24 17:34 UTC

**Comment by mengyanshou** [comment] 2024-11-25 00:42
Test passed. Thanks again for your contribution.
