### ISSUE TITLE
Segmentation fault！！！

### ISSUE THREAD

**Issue by GBwuka** [Genymobile/scrcpy#717] opened 2019-08-12 09:30 UTC
when I use scrcpy it will happen Segmentation fault，but two weeks ago it runs normal，i don't know if it will only happen on v1.10.  
error information below:
![image](https://user-images.githubusercontent.com/1592742/62856221-e59a1c80-bd26-11e9-89da-dd1caa503e69.png)

**Comment by rom1v** [comment] 2019-08-12 09:50
Hi,

Thank you for your report.

I'm closing as duplicate of #707.

I will investigate as soon as I have time.

Could you please paste the result of:

    scrcpy -v

(to get the version of the dependencies)?

What is you distrib/version?

**Closed by rom1v** 2019-08-12 09:50 UTC

**Comment by GBwuka** [comment] 2019-08-12 10:01
![image](https://user-images.githubusercontent.com/1592742/62857822-31e75b80-bd2b-11e9-8ffd-6114ece4fa3c.png)

**Comment by rom1v** [comment] 2019-08-13 17:45
Fixed on `master` by a9c8fa305d2313bed70b2d1d756083f40e065352.
