### ISSUE TITLE
Audio stopping from smartphone while using scrcpy

### ISSUE THREAD

**Issue by nvn152** [Genymobile/scrcpy#4954] opened 2024-05-29 03:23 UTC
**Environment**
 - OS: Arch Linux (Wayland)
 - scrcpy version: 2.4
 - installation method: yay
 - Android version: 14

**Describe the bug**
With sndcpy, we used to get audio from both the smartphone and the PC. However, with scrcpy, audio is only coming from one of them. Is there a way to make scrcpy output audio from both devices at the same time?

**Comment by rom1v** [comment] 2024-05-29 06:44
Sndcpy and scrcpy use different mechanisms to capture audio:
 - sndcpy uses the [playback capture API](https://developer.android.com/guide/topics/media/playback-capture) introduced in Android 10,
 - scrcpy uses an `AudioRecord` with "remote submix" as source (#3757)

There are two major drawbacks to the playback capture API used in sndcpy:
 - it lets Android apps decide if they can be captured or not (in practice, many apps are not captured),
 - it requires a real app (an APK) to be installed on the device (a real Android Context is necessary), that's the main reason why it's not implemented in scrcpy.

But as you noticed, unfortunately, we cannot keep audio on the device with the mechanism usedby scrcpy: #3875.

Also see https://github.com/Genymobile/scrcpy/issues/4884#issuecomment-2076869578

**Comment by Matrosya** [comment] 2024-06-04 06:15
I wanted to use this application as a video capture card. Since I output the sound and video to a computer with a large buffer, I need the sound from the phone so that I can play games without sound delay. It's unfortunate that there is no solution yet.

**Comment by rom1v** [comment] 2024-07-16 19:45
Duplicate of #3875. Please test #5102.

**Closed by rom1v** 2024-07-16 19:45 UTC
