### ISSUE TITLE
Left Click won't work inside chrome and other browser

### ISSUE THREAD

**Issue by yasinULLAH** [Genymobile/scrcpy#3686] opened 2023-01-21 11:30 UTC
Dear Sir,
         The mouse Left click won't work when we open scrcpy with this command "--forward-all-clicks", inside chrome and other browser like kiwi etc. That is I can't click on any link inside google chrome's google search links and inside other website links please fix this issue. Left click is working in other areas of browser's but can't click any href links

**Comment by rom1v** [comment] 2023-01-21 14:36
Thank you for your report.

This is a duplicate of #3635.

**Closed by rom1v** 2023-01-21 14:36 UTC
