### ISSUE TITLE
scrcpy freezes after a while

### ISSUE THREAD

**Issue by T3hFyrefly** [Genymobile/scrcpy#459] opened 2019-03-18 04:53 UTC
So I updated Scrcpy to version 1.8, then for some reason the video would stop working, it would just freeze, it won't respond to inputs. When I restart it, it would just hang on "INFO: Initial texture: 1920x1080" even if I kill adb.exe in Task Manager, only way to get it to start working again is to restart my PC, but it will break again after a few minuets. I tried to revert back to 1.5 which is what I was using before, but it now also does it for some reason. Version 1.7 and 1.6 also do it for some reason as well. Even tried using the 32 bit build instead. I've tried lowing the resolution and bit rate with -m800 -b1M but it doesn't appear to make any difference. Not sure what the command is to make a log file, if that would help. I'm on Windows 10 64bit.

**Comment by rom1v** [comment] 2019-03-18 07:16
I guess it's a driver issue.

Just in case, try with SDL 2.0.8 instead of 2.0.9: https://github.com/Genymobile/scrcpy/issues/425#issuecomment-470936377.

**Comment by T3hFyrefly** [comment] 2019-03-19 17:27
I started using version 1.3 and it works fine. Trying to using 1.5 or above will just freeze. So it does appear to be an issue with SDL 2.0.9. I tried to replace the SDL2.dll in 1.8 with the one from version 1.3 it gave an initialization error at first, but after a restart 1.8 seems to run fine with the SDL2.dll from 1.3

**Comment by rom1v** [comment] 2019-03-19 17:29
OK :+1:

(so I'm closing as duplicate of #425)

**Closed by rom1v** 2019-03-19 17:29 UTC
Labels: sdl
