### ISSUE TITLE
Add games section

### ISSUE THREAD

**Issue by ElNoperi** [Genymobile/scrcpy#4067] opened 2023-06-07 14:08 UTC
You could add buttons to map and use the app as an emulator to play mobile games from your computer.

**Comment by rom1v** [comment] 2023-06-07 14:19
Duplicate of #712.

**Closed by rom1v** 2023-06-07 14:19 UTC

**Comment by ElNoperi** [comment] 2023-06-08 01:08
So I would have to adapt it manually So I would have to adapt it manually, the command in scrcpy does not exist as such

**Comment by ElNoperi** [comment] 2023-06-08 01:09
So I would have to adapt it manually, the command in scrcpy does not exist as such
