### ISSUE TITLE
recorded file not playable if command prompt window closed

### ISSUE THREAD

**Issue by manivannan184** [Genymobile/scrcpy#853] opened 2019-10-11 02:33 UTC
Version 1.10

Prepare a batch script with following command or run the command 
`scrcpy-noconsole.exe -s 41be5e3a -r %filename%.mp4 -t`

Recording window opens and file gets updated.

Now there are two ways to stop.

1. Close the Video window.
**File gets saved properly.**

2. Close the CMD window (parent window).
**File does not gets saved properly, gets corrupted and not playable.**

**Comment by manivannan184** [comment] 2019-10-11 04:50
instead of .mp4, i tried .mkv - this time file saved properly.
So issue is with .mp4 format only

**Comment by rom1v** [comment] 2019-10-11 05:13
See #818.

> instead of .mp4, i tried .mkv - this time file saved properly.

It's also "broken", just less than mp4 because mp4 records its header at the end.

The problem is rather Windows, which does not allow to execute clean up code on closing the console.

**Comment by rom1v** [comment] 2020-05-08 13:00
I implemented a fix for Ctrl+C on Windows: https://github.com/Genymobile/scrcpy/issues/818#issuecomment-625803875

**Closed by rom1v** 2020-05-08 13:00 UTC
Labels: record
