### ISSUE TITLE
Computer can't control mobile screen

### ISSUE THREAD

**Issue by Ripple-Peng** [Genymobile/scrcpy#874] opened 2019-10-21 08:00 UTC
After the Xiaomi mobile phone system is upgraded to miui11, the computer cannot control the mobile phone screen. When the system was miui10, it did not have this problem and returned a error.

environment:
```
Mobile phone：redmi k20pro
System version：MIUI 11.0.2.0
Android version：10
```

error:
```
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
        at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1606)
        ... 7 more
```

**Comment by rom1v** [comment] 2019-10-21 08:02
Duplicate of #835. Already fixed on `dev` branch.

**Closed by rom1v** 2019-10-21 08:02 UTC
