### ISSUE TITLE
Android Emulator Controller

### ISSUE THREAD

**Issue by Baloch-Rasheed** [Genymobile/scrcpy#5356] opened 2024-10-08 20:30 UTC
**Feature Definition**
I don't know I think if you guys add any mechanism where we can use our mouse and keyboard on gamming too. like a customized mode for gamming people can choose keys to place on the mirror which trigger a touch event. and you guys probably know what function does mouse do. So it'll be a cool feature for gamers who can't afford a powerful PC for gamming but can still enjoy the games on mobile. and yes this it just a dummy idea. and thanks for all for this tool which I found very helpful.

**Comment by rom1v** [comment] 2024-10-08 20:32
Duplicate of #712.

**Closed by rom1v** 2024-10-08 20:32 UTC
