### ISSUE TITLE
ERROR: Could not execute "adb push"

### ISSUE THREAD

**Issue by Lyuxy** [Genymobile/scrcpy#278] opened 2018-09-30 01:54 UTC
Got this issue with win10.

can get my device by `adb devices`

**Comment by rom1v** [comment] 2018-09-30 08:48
Could you provide more information: what is the command you executed? from which directory? on which platform? what is the whole output?

**Comment by Lyuxy** [comment] 2018-10-01 02:44
I executed "scrcpy" at my scrcpy's directory:   “.\scrcpy-win64”
output：ERROR: Could not execute "adb push" 
execute  “adb devices” can find my device.”
on win10

**Comment by Lyuxy** [comment] 2018-10-01 02:44
> Could you provide more information: what is the command you executed? from which directory? on which platform? what is the whole output?
I executed "scrcpy" at my scrcpy's directory: “.\scrcpy-win64”
output：ERROR: Could not execute "adb push"
execute “adb devices” can find my device.”
on win10

**Comment by npes87184** [comment] 2018-10-04 03:55
@Lyuxy 

Can you test it again in [scrcpy 1.4](https://github.com/Genymobile/scrcpy/releases/tag/v1.4)?
In scrcpy 1.4, it will detect whether adb is missing or not (see #236, #254 ).

If the adb is missing when we execute scrcpy, it will show on console.

Thanks.

**Comment by Plandercozeron** [comment] 2018-10-12 13:09
Hello. I'm having 'Could not execute adb push' issue too with 1.4 on Windows 7 x64
1) I have `C:\adb` directory in my PATH
2) I've unpacked scrcpy's zip-package at `C:\adb`
3) Called `scrcpy` from command line and get this error:
```
ERROR: Failed to execute adb
ERROR: Could not execute "adb push"
Press any key to continue...
```
But if i unpack archive somewhere else, call command line from that directory and use `scrcpy` then everythiong works fine.
Tried to put contents of scrcpy to my user direcotry from where command line is beeing called if i use PATH, but it won't work - same error.

**Comment by rom1v** [comment] 2018-10-12 13:20
>3. Called `scrcpy` from command line and get this error:

What if you call `adb devices` instead?

The release of `scrcpy`already includes `adb`, you don't need to extract it to some `adb` directory (it might conflict).

> Tried to put contents of scrcpy to my user direcotry *from where command line is beeing called if i use PATH*, but it won't work - same error.

Sorry, I didn't get that part. Could you explain with a concrete example, please?

**Comment by Plandercozeron** [comment] 2018-10-12 13:33
#### Case when doesn't work
1) Have empty directory A which is in PATH
2) Extract scrcpy into A
3) Launch CMD by just `Win + R` -> `cmd` so CMD starts from current user directory 
4) Call `scrcpy` - doesn't work
5) Call `adb devices` - works

#### Case when works
1) Extract scrcpy into directory B
2) Launch CMD from directory B
3) Call `scrcpy` - works

**Comment by rom1v** [comment] 2018-10-12 13:44
OK, I get it.

The problem is that `scrcpy` pushes the `scrcpy-server.jar` that it finds in `.` (your current directory). If you start `scrcpy` from `PATH`, it expects `scrcpy-server.jar` to be in `.`, i.e. the current directory, the one from where you call (the Windows version is "portable", it [overrides](https://github.com/Genymobile/scrcpy/blob/v1.4/Makefile.CrossWindows#L60) the [server path](https://github.com/Genymobile/scrcpy/blob/v1.4/app/src/server.c#L24-L30)).

If you want your `scrcpy-server.jar` to be in a directory other than `.` (the current), you need to give its fullpath in the env variable `SCRCPY_SERVER_PATH`.

**Comment by Plandercozeron** [comment] 2018-10-12 18:49
Yes, that helped. Put `scrcpy-server.jar` in my user directory . Thought scrcpy couldn't find `adb.exe` at first. Very useful

**Comment by Lyuxy** [comment] 2018-10-26 09:09
@rom1v @npes87184 it still happen in v1.4 

ERROR: Failed to execute adb
ERROR: Could not execute "adb push"

**Comment by rom1v** [comment] 2018-10-26 09:16
@Lyuxy Please provide:
 - the current directory path from where you execute scrcpy
 - the content of that directory
 - the content of your PATH variable
 - the result of `adb devices`

**Comment by rom1v** [comment] 2018-10-26 09:31
You have `adb` accessible both from your PATH and the current directory. I don't know which one is chosen.

What is the result of:

    .\adb devices
    .\adb --version

and

    %ANDROID_HOME%platform-tools\adb devices
    %ANDROID_HOME%platform-tools\adb --version

?

What if you remove `adb.exe` from the scrcpy directory?

**Comment by Lyuxy** [comment] 2018-10-26 09:57
All same with these steps—— output ：version 1.0.32  and  find my android device.
After remove 'adb.exe' from the scrcpy directory ，excute 'scrcpy' ，output the same errors。

**Comment by rom1v** [comment] 2018-10-26 10:05
> version 1.0.32

This is not expected. The `adb.exe` included in scrcpy is 1.0.40 IIRC (I have currently no Windows to check, but it may not be 1.0.32).

**Comment by Lyuxy** [comment] 2018-10-30 06:32
i download scrcpy again. now excute “adb version”in scrcpy's file path，output “v1.0.40”，but it doesn‘t work，i still can't use it.

**Comment by cotfas** [comment] 2019-05-11 21:34
Hello,

I use the 1.8 version, and I get the same error on mac, tried with adb over usb and wifi and it is the same issue. The adb devices it is showing the phone connected for both cases. How can I fix it? I`ve tried also with compiling the project..

Thank you

**Comment by rom1v** [comment] 2019-05-11 21:51
What if you manually execute:

    adb push scrcpy-server.jar /data/local/tmp

(adapt the path of `scrcpy-server`)

**Comment by cotfas** [comment] 2019-05-12 09:09
The same issue:

cotfas:scrcpy work$ 
cotfas:scrcpy work$ 
cotfas:scrcpy work$ adb devices
List of devices attached
9889db394248483045	device

cotfas:scrcpy work$ adb push /usr/local/share/scrcpy/scrcpy-server.jar /data/local/tmp
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 0.4 MB/s (19850 bytes in 0.047s)
cotfas:scrcpy work$ scrcpy
exec: Permission denied
2019-05-12 12:08:41.901 scrcpy[90214:1912846] ERROR: Failed to execute adb
2019-05-12 12:08:41.901 scrcpy[90214:1912846] ERROR: Could not execute "adb push"
cotfas:scrcpy work$ 


I`ve also posted the issue here:

https://github.com/Genymobile/scrcpy/issues/530

**Comment by vflame** [comment] 2019-05-18 04:43
On windows, setting SCRCPY_SERVER_PATH copies the scrcpy binaries to /data/local/tmp/scrcpy-server.jar/*.*

**Comment by rom1v** [comment] 2019-05-18 07:03
Which value do you assign to `SCRCPY_SERVER_PATH` exactly?

**Comment by vflame** [comment] 2019-05-18 07:15
Path to the scrcpy-server.jar (e.g. "C:\scrcpy-win64")

**Comment by rom1v** [comment] 2019-05-18 07:25
You need to pass its full path: `C:\scrcpy-win64\scrcpy-server.jar`.

**Comment by rom1v** [comment] 2019-06-24 11:23
v1.9 fixes the problem by searching in the same directory as the binary on Windows, so I'm closing.

**Closed by rom1v** 2019-06-24 11:23 UTC
Labels: adb

**Comment by wangym1551** [comment] 2020-08-14 07:21
i have this problem too  ERROR:could not execute "adb push"，and i solved it like this
1、Delete adb in PATH
2、run the scrcpy.exe as administrator

**Comment by ghyujkilop** [comment] 2020-10-15 05:25
> 
> 
> i have this problem too ERROR:could not execute "adb push"，and i solved it like this
> 1、Delete adb in PATH
> 2、run the scrcpy.exe as administrator

Yes! This worked! Thank you! <3

**Comment by SHITIJHALDER** [comment] 2021-08-23 07:13
> What if you manually execute:
> 
> ```
> adb push scrcpy-server.jar /data/local/tmp
> ```
> 
> (adapt the path of `scrcpy-server`)

Same problem!

**Comment by jericepon** [comment] 2022-01-26 03:10
I encountered the same issue. I tried to run it on cmd and it works.

**Comment by chentao753951** [comment] 2022-12-29 09:48
I the same issue.  Update to the latest version and the problem is solved
