### ISSUE TITLE
NVIDIA Shield issue

### ISSUE THREAD

**Issue by AceHack** [Genymobile/scrcpy#993] opened 2019-12-09 06:23 UTC
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.createPackageContext(java.lang.String, int)' on a null object reference
        at android.media.MediaCodec.isSupported(MediaCodec.java:1794)
        at android.media.MediaCodec.checkAppForAutoFrc(MediaCodec.java:1831)
        at android.media.MediaCodec.configureCodecParams(MediaCodec.java:1980)
        at android.media.MediaCodec.<init>(MediaCodec.java:2011)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1944)
        at com.genymobile.scrcpy.ScreenEncoder.createCodec(ScreenEncoder.java:138)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:63)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:146)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
INFO: Initial texture: 1920x1080
WARN: Device disconnected

**Comment by rom1v** [comment] 2019-12-09 06:30
Thank you for your report.

This is a duplicate of #940. It is fixed on `dev` branch.

**Closed by rom1v** 2019-12-09 06:30 UTC
