### ISSUE TITLE
1.21 shows green screen when executed with -f option

### ISSUE THREAD

**Issue by jsyoo3722** [Genymobile/scrcpy#2839] opened 2021-11-30 07:28 UTC
OS: Windows 11 x64
scrcpy build 1.21
using Samsung Tab S7FE Wifi (SM-T733), Android 11

This is when executed with no other flags. 
It pops up the screen and mirrors just fine.
![33333333](https://user-images.githubusercontent.com/58194688/144004035-bdc3f018-1671-4130-ae46-82d052e55fb9.png)

This is when executed with -f
It pops up only the green screen.
This did not happen with scrcpy 1.18.
![444444444](https://user-images.githubusercontent.com/58194688/144004155-5f546c96-95d3-4b4a-af9d-1adf37f3c539.png)

For your info, the wireless connection showed the same results.
no fullscreen
![1111111111111](https://user-images.githubusercontent.com/58194688/144003280-a7f7cc44-1e0f-45d1-a295-508942f401c7.png)

fullscreen
![2222222222](https://user-images.githubusercontent.com/58194688/144003656-19d476a5-9b6d-431a-985d-fbba70e696cf.png)

**Comment by jsyoo3722** [comment] 2021-11-30 07:37
I tested with several other older versions, and the same thing happens with the following versions:
1.19
1.20
1.21

1.18 is the version that does not have the issue.
This version still works fine with -f option.

**Comment by rom1v** [comment] 2021-11-30 07:41
Thank you for your report.

This is a duplicate of #2682. This is a bug in SDL (not scrcpy). See the thread.

**Closed by rom1v** 2021-11-30 07:41 UTC

**Comment by jsyoo3722** [comment] 2021-11-30 08:13
> Thank you for your report.
> 
> This is a duplicate of #2682. This is a bug in SDL (not scrcpy). See the thread.

Thank you so much. Replacing the SDL2.dll with that from 1.18 zip solved the issue.
I'll remind myself to search before reporting.
