### ISSUE TITLE
Can I bind some action? 

### ISSUE THREAD

**Issue by sluzhynskyi** [Genymobile/scrcpy#1539] opened 2020-06-23 11:57 UTC
I'm really like this project, great job. It would be great if you can add feature like Key-Binding, 
For example how I see the solution: </br>
configuration file with additional commands ```"Ctrl+W": "adb shell input swipe 72 1100 72 1200" ```

**Comment by rom1v** [comment] 2020-06-23 12:00
> I'm really like this project, great job.

Thank you :)

> Can I bind some action?

No, for now it's not possible.

I'm closing as duplicate of #712.

**Closed by rom1v** 2020-06-23 12:00 UTC
