### ISSUE TITLE
command   scrcpy    report  this error

### ISSUE THREAD

**Issue by cwgsmart** [Genymobile/scrcpy#851] opened 2019-10-09 01:52 UTC
2019-10-09 09:47:07.105 scrcpy[736:8320] INFO: Initial texture: 1080x2336
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
	at com.genymobile.scrcpy.Server.main(Server.java:133)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

**Comment by rom1v** [comment] 2019-10-09 08:03
Duplicate of #309

**Closed by rom1v** 2019-10-09 08:03 UTC
