### ISSUE TITLE
Audio forwarding can still work when open mic on Gaming (Pubg mobile)

### ISSUE THREAD

**Issue by arfiand11** [Genymobile/scrcpy#4911] opened 2024-05-09 09:01 UTC
I used scrcpy 2.4 version, it is working fine while playing game, but the issue is existing when I play with my friends, I can still open mic but the audio forwarding is not mirrored.

I will very happy if you can solve the problem.

Thank you verymuch

**Comment by rom1v** [comment] 2024-05-09 09:19
Duplicate of #4084 #4087.

**Closed by rom1v** 2024-05-09 09:19 UTC
