### ISSUE TITLE
build error: build-wrapper.sh not found

### ISSUE THREAD

**Issue by yxtj** [Genymobile/scrcpy#206] opened 2018-07-22 13:35 UTC
I got this error message if building without given scrcpy-sever.jar. They occur when running 'ninja'.
I am using Ubuntu 18.04.
I checked the similar issue on https://github.com/Genymobile/scrcpy/issues/115. It does not work either for me.

 I hide my username with <xxxx>.
-------------
[20/31] Generating scrcpy-server with a custom command.
FAILED: server/scrcpy-server.jar 
/home/<xxxx>/Softwares/scrcpy/server/./scripts/build-wrapper.sh ../server/. server/scrcpy-server.jar debug
/bin/sh: 1: /home/<xxxx>/Softwares/scrcpy/server/./scripts/build-wrapper.sh: not found
[28/31] Compiling C object 'app/scrcpy@exe/src_tinyxpm.c.o'.
ninja: build stopped: subcommand failed.

-------------
FYI, this is the log of running 'meson y'. I hide my username with <xxxx>.

The Meson build system
Version: 0.45.1
Source dir: /home/<xxxx>/Softwares/scrcpy
Build dir: /home/<xxxx>/Softwares/scrcpy/y
Build type: native build
Project name: scrcpy
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libavformat found: YES 57.83.100
Native dependency libavcodec found: YES 57.107.100
Native dependency libavutil found: YES 55.78.100
Native dependency sdl2 found: YES 2.0.8
Configuring config.h using configuration
Program ./scripts/build-wrapper.sh found: YES (/home/<xxxx>/Softwares/scrcpy/server/./scripts/build-wrapper.sh)
Build targets in project: 6
Found ninja-1.8.2 at /usr/bin/ninja

**Comment by rom1v** [comment] 2018-07-22 13:37
> /bin/sh: 1: /home/tzhou/Softwares/scrcpy/server/./scripts/build-wrapper.sh: not found

What is the result of:

    ls -l /home/tzhou/Softwares/scrcpy/server/./scripts/build-wrapper.sh

?

**Comment by rom1v** [comment] 2018-09-24 12:37
I'm closing as duplicate of https://github.com/Genymobile/scrcpy/issues/115 (that I let open because the problem is not solved).

**Closed by rom1v** 2018-09-24 12:37 UTC
Labels: build
