### ISSUE TITLE
Problem with Turkish characters

### ISSUE THREAD

**Issue by kofte** [Genymobile/scrcpy#656] opened 2019-07-21 01:13 UTC
When I try to type ş Ş, ğ Ğ, lowercase ı I, and uppercase i İ, software does not recognise those and gives an error in terminal like "[server] WARN: Could not inject char u+0131"
Also, pressing "ı" does give the error but pressing Shift + "ı" does not. But pressing Shift + i gives "[server] WARN: Could not inject char u+0130" but then writes uppercase "ı I" (uppercse "i" in other languages)

**Comment by kofte** [comment] 2019-07-21 01:29
![example](https://user-images.githubusercontent.com/906680/61585883-1a73e300-ab70-11e9-9886-696b0a1800d6.gif)

**Comment by npes87184** [comment] 2019-07-21 06:28
There are some problem about char injection. See #431.

Please use `ctrl` + `shift` + `v` to paste char from PC's clipboard into device's as workaround now.

**Comment by rom1v** [comment] 2019-07-21 07:00
Text injection on Android only supports ASCII.

https://blog.rom1v.com/2018/03/introducing-scrcpy/#inject-text

**Comment by czarls** [comment] 2020-01-10 12:46
There is also an issue with polish characters, only few of them are supported.
Missing are:
`u+0119
u+0105
u+0142
`

**Comment by rom1v** [comment] 2020-04-09 19:36
Closing as duplicate of #37.

**Closed by rom1v** 2020-04-09 19:36 UTC
Labels: input events, keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:39
Please test #1426 (works on Android >= 7).
