### ISSUE TITLE
can we open multiwindows, give each app a indepe window in computer

### ISSUE THREAD

**Issue by zihaoxingstudy1** [Genymobile/scrcpy#1374] opened 2020-05-09 12:50 UTC
PC have the bigger screen, i hope we can open multiwindows and give each app a inpendent windows in our computer.

**Comment by rom1v** [comment] 2020-05-09 13:13
Duplicate of #372 

I have no technical solution for this currently.

**Closed** 2020-05-09 13:13 UTC
