### ISSUE TITLE
Copy from device to computer clipboard (Ctrl + C)

### ISSUE THREAD

**Issue by mttmllns** [Genymobile/scrcpy#246] opened 2018-08-27 22:41 UTC
I was looking for a quick way to get some copied text from my device onto my computer.  Tried Ctrl + C and it didn't work.  Any reason for this?  Would be pretty useful for a lot of my workflow.

I'm on a Pixel with the latest scrcpy 1.3.  Tried Ctrl + C with text in a textbox, selected text in a textbox, and long-pressed and copied selected text in a textbox.

**Comment by rom1v** [comment] 2018-08-28 06:45
This is a duplicate of https://github.com/Genymobile/scrcpy/issues/145 (so I'm closing this one).

> Tried Ctrl + C and it didn't work. Any reason for this?

Mainly because it has the same implications as https://github.com/Genymobile/scrcpy/issues/8#issuecomment-371819839.

**Comment by esauvisky** [comment] 2018-08-29 01:06
I know this is not a solution at all, and it's barely relevant. But in some cases, like mine in which I needed to automate some workflows, my workaround was to use a service that allows you to interact with the android clipboard system via adb, called [clipper](https://github.com/majido/clipper).

Depending on your workflow this might help you. And who knows, maybe there's something on that old, old repo that could be helpful for implementing this feature on scrcpy.

**Closed** 2018-09-06 17:18 UTC
Labels: feature request

**Comment by rom1v** [comment] 2019-05-30 21:02
Implemented on `dev` branch. See https://github.com/Genymobile/scrcpy/issues/145#issuecomment-497484917.
