### ISSUE TITLE
Error with camera source on Oppo device (scrcpy v2.2)

### ISSUE THREAD

**Issue by elblogbruno** [Genymobile/scrcpy#4405] opened 2023-11-05 11:04 UTC
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...] Windows 10
 - scrcpy version: [e.g. 1.12.1] 2.2
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...] Windows release
 - device model: Oppo Find X3 Neo 5G
 - Android version: [e.g. 10] Android 13

**Describe the bug**
When trying to run the v2.2 version using the new camera feature, scrcpy crashes with the following error:

```
scrcpy --video-source=camera --camera-id=0 --camera-fps=20
scrcpy v2.2 <https://github.com/Genymobile/scrcpy>
INFO: Camera video source: control disabled
INFO: Camera video source: microphone audio source selected
INFO: ADB device found:
INFO:     -->   (usb)              c33fafdf            device  CPH2207
D:\Desktop\Proyectos\Software en Uso\scrcpy-win64-v2.2\scrcpy-server: 1 file pushed, 0 skipped. 67.7 MB/s (64363 bytes in 0.001s)
[server] INFO: Device: [OPPO] OPPO CPH2207 (Android 13)
[server] INFO: Using camera '0'
[server] ERROR: Exception on thread Thread[camera,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference
        at android.hardware.camera2.OplusCamera2StatisticsManager.addInfo(OplusCamera2StatisticsManager.java:69)
        at android.hardware.camera2.impl.CameraDeviceImplExtImpl.extendsetInfo(CameraDeviceImplExtImpl.java:47)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:190)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.os.HandlerThread.run(HandlerThread.java:67)
INFO: Renderer: direct3d
INFO: Texture: 4096x3072
```
I have tried running all types of commands.

What could it be? I don't know if it does affect other oppo devices

Thanks

**Comment by rom1v** [comment] 2023-11-05 11:21
Duplicate of #4392 (please test the provided binary :wink:)

**Closed by rom1v** 2023-11-05 11:21 UTC

**Comment by elblogbruno** [comment] 2023-11-05 11:55
sorry for that! thanks
