### ISSUE TITLE
Turkish special characters 

### ISSUE THREAD

**Issue by alperenbabagil** [Genymobile/scrcpy#856] opened 2019-10-11 08:37 UTC
Turkish ı,ş,ğ,I,Ş,Ğ characters cannot be entered with computer keyboard

**Comment by dani763f** [comment] 2019-10-27 18:21
+1 Danish special characters (æøå) also doesn't work (at least on the snap version of the app).

**Comment by rom1v** [comment] 2019-11-19 23:07
Duplicate of #37.

**Closed by rom1v** 2019-11-19 23:07 UTC
Labels: keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:40
Please test #1426 (works on Android >= 7).
