### ISSUE TITLE
Chrome hang while use turned off screen

### ISSUE THREAD

**Issue by Gnonymous7** [Genymobile/scrcpy#1030] opened 2019-12-20 01:42 UTC
Using scrcpy with screen off attrib, made chrome 100% unresponsive. When i turn the phone on, and use it on my pc again. it works just fine.

**Comment by rom1v** [comment] 2019-12-20 07:43
Thank you for your report.

This is a duplicate of #836. This is probably due to an "optimization" in Chrome not to render when the screen is off.

**Closed by rom1v** 2019-12-20 07:43 UTC
Labels: screenoff
