### ISSUE TITLE
MIC AND AUDIO

### ISSUE THREAD

**Issue by LAXMINARAYAN24** [Genymobile/scrcpy#5239] opened 2024-08-27 13:22 UTC
I am using srcpy for boosting my volume on headphone through connecting it to pc and then phone . But when i play bgmi and turn on the mic and speaker its audio turn off in the headphone it comes from mobile .

**Comment by rom1v** [comment] 2024-08-27 13:23
Duplicate of #4084 #4087.

**Closed by rom1v** 2024-08-27 13:23 UTC

**Comment by TamikGuk** [comment] 2024-09-09 21:19
maybe there is some kind of program for combining sound or the like.
