### ISSUE TITLE
[Feature Request] Paste device clipboard (ASCII) to computer

### ISSUE THREAD

**Issue by pundoo** [Genymobile/scrcpy#253] opened 2018-09-06 09:54 UTC
Would this be possible to implement?

**Comment by rom1v** [comment] 2018-09-06 17:19
This is a duplicate of https://github.com/Genymobile/scrcpy/issues/145 (so I'm closing this one).

> Would this be possible to implement?

It has the same implications as https://github.com/Genymobile/scrcpy/issues/8#issuecomment-371819839.

**Closed by rom1v** 2018-09-06 17:19 UTC

**Comment by rom1v** [comment] 2019-05-30 21:02
Implemented on `dev` branch. See https://github.com/Genymobile/scrcpy/issues/145#issuecomment-497484917.
