### ISSUE TITLE
Can not scrcpy on poco m3. always device disconnected.

### ISSUE THREAD

**Issue by YohanesArifin** [Genymobile/scrcpy#2309] opened 2021-05-12 18:11 UTC
- [ v ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ v ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 10]
 - scrcpy version: [e.g. 1.17]
 - installation method: [e.g. manual build, apt, snap, brew, Windows release...]
 - device model: POCO M3 
 - Android version: [10]

**Describe the bug**
always can not connect, device disconnected

On errors, please provide the output of the console (and `adb logcat` if relevant).

```
Please paste terminal output in a code block.
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
D:\SCRCPY\scrcpy-server: 1 file pushed, 0 skipped. 76.9 MB/s (34930 bytes in 0.000s)
[server] INFO: Device: Xiaomi M2010J19CG (Android 10)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2336
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2024)
        at android.media.MediaCodec.configure(MediaCodec.java:1952)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:232)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:89)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
        at com.genymobile.scrcpy.Server.main(Server.java:252)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
WARN: Killing the server...
Press any key to continue . . .

Thats it

Please help

**Comment by rom1v** [comment] 2021-05-12 19:13
Duplicate of #545 #833.

A priori a device encoder issue.

Does it work with screenrecord: `adb shell screenrecord /sdcard/file.mp4`?
Does it work with another [encoder](https://github.com/Genymobile/scrcpy#encoder)?

**Closed by rom1v** 2021-05-12 19:13 UTC

**Comment by balvinderz** [comment] 2021-06-04 05:48
@YohanesArifin   This command works
` scrcpy --encoder c2.android.avc.encoder`
