### ISSUE TITLE
add a shortcut to manually rotate the scrcpy screen

### ISSUE THREAD

**Issue by zerobikappa** [Genymobile/scrcpy#806] opened 2019-09-15 15:02 UTC
I found such many issues related to screen rotation in this project. most of them could be solved if `scrcpy` has a shortcut to manually rotate the scrcpy screen(no the screen of device).

may I know if it is possible to add a shortcut or option to manually set the screen rotation?

**Comment by rom1v** [comment] 2019-09-15 15:12
Duplicate of #218.

**Closed by rom1v** 2019-09-15 15:12 UTC
