### ISSUE TITLE
memleak

### ISSUE THREAD

**Issue by aezaekill** [Genymobile/scrcpy#66] opened 2018-03-13 15:49 UTC
Hi.
It seems like memory usage is constantly increasing. After using scrcpy for serveral minutes (8 Minutes to be exact) it uses 1.6 GB of RAM. After 9 Minutes it already uses 1.8 GB of RAM.

I am running it on Windows 10 if this makes any difference.

Regards.

**Comment by rom1v** [comment] 2018-03-13 15:51
Thank you for your report.

Duplicate of https://github.com/Genymobile/scrcpy/issues/26. It is fixed on `master`, and will be available in the next release.

**Closed by rom1v** 2018-03-13 15:51 UTC
