### ISSUE TITLE
Android 14 --turn-screen-off

### ISSUE THREAD

**Issue by allasca** [Genymobile/scrcpy#4351] opened 2023-10-12 18:28 UTC
**Environment**
 - OS: Windows 11
 - scrcpy version: scrcpy-win64-v2.1.1
 - installation method: Windows release
 - device model: Google Pixel 6a
 - Android version: 14

**Describe the bug**
when using
```
scrcpy --video-bit-rate=16M --video-codec=h265 --max-fps=30 --select-usb --stay-awake --turn-screen-off
```
screen on the device not turning off, even with ctrl+o
```
C:\scrcpy-win64-v2.1.1\scrcpy-server: 1 file pushed, 0 skipped. 85.7 MB/s (56995 bytes in 0.001s)
[server] INFO: Device: [Google] google Pixel 6a (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids
```

**Comment by rom1v** [comment] 2023-10-12 19:01
Thank you for your report.

Closing as duplicate of #3927.

**Closed by rom1v** 2023-10-12 19:01 UTC
