### ISSUE TITLE
on OSX, srcpy screen not auto-refill when moving on multiple monitor system.

### ISSUE THREAD

**Issue by sonvirgo** [Genymobile/scrcpy#492] opened 2019-04-09 14:34 UTC
Setup on my  macOS/Windows 10 with dual monitor, primary 15.6" FHD 1920x1080, external 32" QHD 2560x1440:
In Windows 10, when moving srcpy window between monitors, the window size is automatically adjusted, and the content is fitted.
In macOS,   when moving srcpy window between monitors, he window size is automatically adjusted too, the content is not fitted, it will be cut the upper haft or the lower part.

**Comment by sonvirgo** [comment] 2019-04-10 06:27
> Probably related to hidpi, this is the same cause as #15.

Thank you for the excellence utility.
The problem is exact [scaling problem ](https://github.com/Genymobile/scrcpy/pull/245#issuecomment-422499221)

**Comment by rom1v** [comment] 2020-04-11 23:03
(Closing as duplicate of #15 then)

**Closed by rom1v** 2020-04-11 23:03 UTC
Labels: hidpi, macos
