### ISSUE TITLE
lock_video_orientation does not work in Android 14

### ISSUE THREAD

**Issue by sbfkcel** [Genymobile/scrcpy#5399] opened 2024-10-23 07:47 UTC
Will the fix be abandoned?

**Comment by rom1v** [comment] 2024-10-23 07:51
Need to be implemented in a different way. See https://github.com/Genymobile/scrcpy/pull/4658#issuecomment-1936558849

Closing as duplicate of #4011.

**Closed by rom1v** 2024-10-23 07:51 UTC
