### ISSUE TITLE
Illegal Argumennt Exception?

### ISSUE THREAD

**Issue by TheRealJimboBob** [Genymobile/scrcpy#2993] opened 2022-02-01 03:18 UTC
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 84.4 MB/s (40955 bytes in 0.000s)
[server] INFO: Device: OnePlus DE2118 (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2128)
        at android.media.MediaCodec.configure(MediaCodec.java:2044)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:274)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)dn
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
WARN: Killing the server...

Windows 11
Android Version 11
Phone: 1+

**Comment by rom1v** [comment] 2022-02-01 06:31
Plezse try #2990.

**Comment by scresante** [comment] 2022-02-18 07:31
Hello. 
I have tried building the server from source from the dev branch (and ran into an interesting error with "Unsupported class file major version 61" but fixed that by using jdk11-openjdk on archlinux and compiled the server successfully).
I also tried using the pre-built server mentioned in #2990 . 
I still get a similar error to the one above. It is slightly different, here is my error output:
`scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 151.1 MB/s (96899 bytes in 0.001s)
[server] INFO: Device: motorola moto g stylus 5G (Android 11)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.3.6
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2400
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:278)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:96)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
`

**Comment by scresante** [comment] 2022-02-19 04:29
The workaround mentioned in #3033 
`scrcpy -m1920` 
Works for me.

**Comment by rom1v** [comment] 2022-02-19 06:52
Then #2990 should work.

> /usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 151.1 MB/s (96899 bytes in 0.001s)

It didn't uqe the one you built. How did you build and run?

**Comment by scresante** [comment] 2022-02-20 00:59
> It didn't uqe the one you built. How did you build and run?

Are you asking me? 

`#!/bin/bash
sudo archlinux-java set java-11-openjdk
yay -G scrcpy-git
cd scrcpy-git
makepkg --nobuild
cd src/scrcpy
git checkout dev
meson x --buildtype=release --strip -Db_lto=true
ninja -Cx
cp x/server/scrcpy-server ../../scrcpy-server-v1.22
cd ../../
makepkg --noextract --install
`
And then run `scrcpy -m1920`

**Comment by rom1v** [comment] 2022-02-20 06:24
```
git checkout dev
```

On which commit SHA1 are you after that?

I don't really know how arch packages work, but the fact that it does not retry with a lower definition suggests you don't have the change from #2990.

**Comment by rom1v** [comment] 2022-02-20 06:47
Could you please test the following commands:

```bash
git clone https://github.com/Genymobile/scrcpy
cd scrcpy
git checkout dev
meson d -Db_sanitize=address
ninja -Cd
./run d
```

**Comment by scresante** [comment] 2022-02-20 22:19
> On which commit SHA1 are you after that?

That was from c4ab65eb

> Could you please test the following commands:

Done. Still the same error with latest dev 36c75e15

```scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
DEBUG: ADB device found:
DEBUG:     -->   (usb)  ***                      device  moto_g_stylus_5G
DEBUG: Device serial: ***
DEBUG: Using SCRCPY_SERVER_PATH: d/server/scrcpy-server
d/server/scrcpy-server: 1 file pushed, 0 skipped. 437.5 MB/s (60911 bytes in 0.000s)
[server] INFO: Device: motorola moto g stylus 5G (Android 11)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.3.6
INFO: Trilinear filtering enabled
DEBUG: Using SCRCPY_ICON_PATH: data/icon.png
ERROR: Could not open image codec: data/icon.png
WARN: Could not load icon
INFO: Initial texture: 1080x2400
DEBUG: Starting demuxer thread
[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'
DEBUG: Receiver stopped
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
DEBUG: End of frames
WARN: Device disconnected
DEBUG: quit...
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:282)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:97)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:102)
        at com.genymobile.scrcpy.Server.main(Server.java:332)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
DEBUG: Server disconnected
DEBUG: Server terminated
```

`./run d -m1920` works fine

**Comment by rom1v** [comment] 2022-02-20 22:32
What was your meson command?

(or post the result of `meson configure d`)

**Comment by scresante** [comment] 2022-02-20 22:34
[meson.configure.txt](https://github.com/Genymobile/scrcpy/files/8105065/meson.configure.txt)

**Comment by rom1v** [comment] 2022-02-20 22:35
Thanks!

> java.lang.IllegalArgumentException

Oh ok, it's not IllegalStateException. I will catch this one for retry too, thank you.

**Comment by rom1v** [comment] 2022-02-20 22:40
Please test #3043.

**Comment by scresante** [comment] 2022-02-21 17:43
> Please test #3043.

Yes, I can confirm that the new change in the illegalargumentexception branch fixes this error by automatically retrying at a smaller video size.

**Comment by rom1v** [comment] 2022-02-22 09:28
Thank you, merged :+1:

**Closed by rom1v** 2022-02-22 09:28 UTC

**Comment by rom1v** [comment] 2023-01-27 22:24
Please test this version to make sure that it does not break this bugfix: https://github.com/Genymobile/scrcpy/issues/3693#issuecomment-1407135509
