### ISSUE TITLE
Preview Quality

### ISSUE THREAD

**Issue by MrTeeXD** [Genymobile/scrcpy#501] opened 2019-04-16 09:50 UTC
Hello, it seems like the preview is a little bit of low quality, for example, theres not enough sharpness any way of improving this?

**Comment by rom1v** [comment] 2019-04-17 08:13
Could you post a screenshot, please?

**Comment by rom1v** [comment] 2019-04-17 08:20
Similar to https://github.com/Genymobile/scrcpy/issues/40?

**Comment by MrTeeXD** [comment] 2019-04-17 11:44
Here is the screenshot in scrcpy :
![Scrappy](https://user-images.githubusercontent.com/37266538/56285133-c98ac380-6116-11e9-9f53-6c3a1624a5e0.PNG)

**Comment by rom1v** [comment] 2019-04-17 11:48
Please also send a capture of the device:

    adb exec-out screencap -p > image.png

What if you press Ctrl+G ("pixel perfect") in scrcpy?

**Comment by MrTeeXD** [comment] 2019-04-17 11:58
![image](https://user-images.githubusercontent.com/37266538/56285857-816ca080-6118-11e9-8b78-53c3949e047d.png)

**Comment by MrTeeXD** [comment] 2019-04-17 12:01
It seems like when i try to open the image, the photo viewer says its unsupported

**Comment by rom1v** [comment] 2020-04-11 23:06
Probably duplicate of #40.

**Closed by rom1v** 2020-04-11 23:06 UTC
Labels: quality
