### ISSUE TITLE
Make an option to keep audio play on the phone while forwarding to pc (mirror, not forwarding)

### ISSUE THREAD

**Issue by Bobesmj** [Genymobile/scrcpy#4108] opened 2023-06-23 15:38 UTC
I'm using scrcpy to record my gameplay but I had an issue: when scrcpy captures audio, my phone mutes immediately so I can't hear anything with my Bluetooth headphone, I can't connect headphones to PC because even it just delays around 50 - 100ms but with fps games, I can't hear the enemy exactly
Please make an option to keep audio playing on the phone while audio forwarding to pc (mirror, not forwarding) to use headphones while audio still mirroring to pc

**Comment by rom1v** [comment] 2023-06-23 15:51
Duplicate of #3875.

**Closed by rom1v** 2023-06-23 15:51 UTC
