### ISSUE TITLE
Fail to share screen on v2.3

### ISSUE THREAD

**Issue by FaisalBudiono** [Genymobile/scrcpy#4471] opened 2023-11-27 10:21 UTC
**Environment**
 - OS: Windows 10 Home Edition
 - scrcpy version: v2.3
 - installation method: Windows Release
 - device model: Samsung S23 Ultra (SM-S918B)
 - Android version: 14

**Describe the bug**
If using audio only still works but when trying to share screen it will show an error and stop working. When using the v2.2 the problem dissapear.

**Error Log**
```
[server] INFO: Device: [samsung] samsung SM-S918B (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1440x3088
ERRO[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
        at com.genymobile.scrcpy.ScreenCapture.createDisplay(ScreenCapture.java:77)
        at com.genymobile.scrcpy.ScreenCapture.start(ScreenCapture.java:38)
        at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:72)
        at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
        at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        ... 6 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ConfigurationController.getConfiguration()' on a null object reference
        at android.app.ActivityThread.getConfiguration(ActivityThread.java:3899)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfoLocked(DisplayManagerGlobal.java:260)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:234)
        at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:364)
        at android.hardware.display.DisplayManagerGlobal.getRealDisplay(DisplayManagerGlobal.java:397)
        at android.hardware.display.DisplayManagerGlobal.createVirtualDisplayWrapper(DisplayManagerGlobal.java:779)
        at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:2088)
R       at android.view.SurfaceControl.createDisplay(SurfaceControl.java:2480)
        ... 8 more
: Demuxer 'audio': stream disabled due to connection error
WARN: Device disconnected
Press any key to continue . . .
```

**Comment by rom1v** [comment] 2023-11-27 10:23
Thank you for your report. Duplicate of #4467/

Please test https://github.com/Genymobile/scrcpy/issues/4467#issuecomment-1827364205

**Closed by rom1v** 2023-11-27 10:23 UTC
