### ISSUE TITLE
[Not Working with Android mobile]

### ISSUE THREAD

**Issue by coolcup74** [Genymobile/scrcpy#2976] opened 2022-01-27 07:07 UTC
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows10
 - scrcpy version: scrcpy v.1.21
 - installation method: download from github directly
 - device model: Android mobile moto g60 (and other android mobiles have the same issue) 
 - Android version: 11

**Describe the bug**
v.1.20 is working fine but,
v.1.21 is not working with the below message.

ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by rom1v** [comment] 2022-01-27 07:16
Please try the binary provided in #2840.

**Comment by coolcup74** [comment] 2022-01-27 08:14
Unfortunately, still not working with #2840.

**Comment by rom1v** [comment] 2022-01-27 08:41
You replaced the executable in your v1.21 release?

From a terminal in the scrcpy folder (see [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows)), what is the result of:
```
adb devices
```

Then:

```
scrcpy
```

**Comment by coolcup74** [comment] 2022-01-27 09:49
Yes. I replcaed it with the executable in v1.21 release.
As I told you, adb connection with my mobile have no problem and no issue with v.1.20.

**Comment by rom1v** [comment] 2022-01-27 10:03
What is the result of the commands requested in the previous comment?

**Comment by coolcup74** [comment] 2022-01-27 10:10
C:\Users\user>adb devices
List of devices attached
LMV600EAc4e2316a        device

C:\Users\user\Downloads\scrcpy-win64-v1.21>scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by rom1v** [comment] 2022-01-27 10:24
OK. What is the result of:

```
adb-getserialno
```
and
```
certUtil -hashfile scrcpy.exe SHA256
```
?

**Comment by coolcup74** [comment] 2022-01-27 10:40
C:\Users\user\Downloads\scrcpy-win64-v1.21>adb get-serialno
LMV600EAc4e2316a

C:\Users\user\Downloads\scrcpy-win64-v1.21>certUtil -hashfile scrcpy.exe SHA256
SHA256의 scrcpy.exe 해시:
8c41744d76ba9003d4a5e5ac7c0e4d42bc136349076b4db099888fdc06f0bb5a
CertUtil: -hashfile 명령이 성공적으로 완료되었습니다.

C:\Users\user\Downloads\scrcpy-win64-v1.21>scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Could not get device serial
ERROR: Server connection failed

C:\Users\user\Downloads\scrcpy-win64-v1.21>

**Comment by rom1v** [comment] 2022-01-27 10:49
Thank you. That's bad, because I have no idea why :/

For all users until now ([even on Windows 10](https://github.com/Genymobile/scrcpy/issues/2838#issuecomment-987413493)), this problem in v1.21 is fixed by #2840, but it's definitely not the case for you.

What if you copy `scrcpy.exe` and `scrcpy-server` (not the other files) from v1.20 into your v1.21 release? Does it still fail?

Are you comfortable with building the app manually ([BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md))?

**Comment by rom1v** [comment] 2022-01-27 10:53
Ah, one more test:

```cmd
adb get-serialno
" then immediately after
echo %errorlevel%
```

**Comment by coolcup74** [comment] 2022-01-27 11:01
v1.21 with copy of scrcpy.exe and scrcpy-server in v1.20 --> No issue!

C:\Users\user\Downloads\scrcpy-win64-v1.21>adb get-serialno
LMV600EAc4e2316a

C:\Users\user\Downloads\scrcpy-win64-v1.21>echo %errorlevel%
0

Refering to build guide, I will try to build manually.

Very Appreciated for your great support.
Hope sort out this after building and debugging. ^^

**Comment by rom1v** [comment] 2022-01-27 11:50
Could you please retry with this version (it's basically #2840 with more logs) and post the output, please:

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2976/1/scrcpy.exe) _sha256:3fc001ebdaee699ad0acf73693dda7482f41a8daae69533b2012a90d03047374_

Also, could you test with the current development branch (+ some other pending work):

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2976/2/scrcpy.exe) _sha256:172007406c89f4fb2a193b69e0ec61fbdf35301247bfebbe8cdc1276c148dee3_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2976/2/scrcpy-server) _sha256:c90ac7684be81ced7b5b9d0be770952894585d2eaabf836ad60ef51f28507781_

(you need to replace both files, and you'll need to restore `scrcpy-server` from v1.21 after that).

**Comment by coolcup74** [comment] 2022-01-28 02:22
**Case 1.**
C:\Users\user\Downloads\scrcpy-win64-v1.21>scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
INFO: === execution success
INFO: === get-serialno: read -1 bytes
INFO: === process check #1
INFO: === process check #2
INFO: === process check #3
INFO: === process ok? 1
ERROR: Could not get device serial
ERROR: Server connection failed

**Case 2.**
error popup with 'avutil-57.dll not exists'

**Comment by rom1v** [comment] 2022-01-28 07:17
> **Case 1.**

Could you try with even more logs, please:

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2976/3/scrcpy.exe) _sha256:b04a645dacbc748f33fcdb6640a1f042f2d10ed436c63e5b633081ae59e7b232_

> **Case 2.**
>
> error popup with 'avutil-57.dll not exists'

Here is a full archive (like a release):

 - [`scrcpy-win64-2976.zip`](https://tmp.rom1v.com/scrcpy/2976/4/scrcpy-win64-2976.zip) _sh&256:babfbbf8e352f97ceecd509348b1b3ea1154322e40e2aca35343517cc3a5e002_

**Comment by coolcup74** [comment] 2022-01-28 13:07
Case 1.
PS C:\Users\user\Downloads\scrcpy-win64-v1.21> .\scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
INFO: === execution success
ReadFile: [109] 파이프가 끝났습니다.
INFO: === get-serialno: read -1 bytes
INFO: === process check #1
INFO: === process check #2
INFO: === process check #3
INFO: === process ok? 1
ERROR: Could not get device serial
ERROR: Server connection failed

Case 2.
PS C:\Users\user\Downloads\scrcpy-win64-2976> .\scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Could not get device serial
ERROR: Server connection failed

**Comment by rom1v** [comment] 2022-01-28 13:54
Thank you for your tests.

I really don't know why reading the output of `adb get-serialno` from scrcpy fails, while if you execute it from `cmd` you get an output.

Just to confirm the stdout and stderr content:

```
adb get-serialno >stdout.txt 2>stderr.txt
more stdout.txt
more stderr.txt
```

I could not reproduce, so it's difficult to investigate. :/

FYI, I will release a new version (v1.22) soon, I wanted to fix this issue beforehand, but I have no clue for now :disappointed: 
If I can't, I'll release then attempt to fix it later.

**Comment by coolcup74** [comment] 2022-01-28 14:24
Myself also feel very sorry for not helping you fixing... but,
I think that the below could be the clue for fixing this issue.

1. runtime output is fine with adb get-serialno only.
2. txt file have nothing even runtime command succeed.

Hope it could be helpful for v1.22.

Thank you.

**Comment by rom1v** [comment] 2022-01-28 14:32
> txt file have nothing even runtime command succeed.

You mean that if you execute:
```
adb get-serialno >stdout.txt 2>stderr.txt
```

Then both `stdout.txt` and `stderr.txt` are empty?

It that's the case, then the problem is not from scrpcy (since getting empty files for this command is unexpected, and scrcpy is not involved).

Something is messing up with process redirection on your system (or `adb.exe`, but since it comes from the scrcpy release, it's the official one and the same as I use in my tests on Windows).

Do you have some antivirus/firewall?

If you execute:
```
echo hello > stdout.txt
more stdout.txt
```

Does the file contain `hello`?

**Comment by coolcup74** [comment] 2022-01-28 14:41
Yes. Even logcat can be captured....
But,,, get-serialno can not be captured...
Myself also can not understand why this happen..

**Comment by coolcup74** [comment] 2022-02-04 00:21
It was by crash of fire-wall program.
It is fixed.
Thank you for great support!!!

**Comment by 3Dbarath** [comment] 2022-04-03 15:35
In my case **USB debugging** settings in my android device is automatically **dis-enabled** in 10 mins  and I just enabled that, now everything working fine.

**Closed** 2022-04-03 15:39 UTC
