### ISSUE TITLE
Fisheye Correction

### ISSUE THREAD

**Issue by Romanthefrog10** [Genymobile/scrcpy#1006] opened 2019-12-13 10:57 UTC
Hello, not sure where I could have asked this question so I'm asking here.
Is there a way to remove or the Fisheye? I want to Stream my Oculus Quest on OBS Studio but I cannot figure out a way to fix the fisheye live so that I can stream it on for example Twitch?

I saw this post [https://github.com/Genymobile/scrcpy/issues/649](https://github.com/Genymobile/scrcpy/issues/649) posted here, 18th of July and was marked as a Feature Request. Will it become a feature or is it already? 

Thanks

**Comment by rom1v** [comment] 2019-12-13 11:05
> I cannot figure out a way to fix the fisheye live

For now you can't in scrcpy (and there are currently no plan to implement it). _scrcpy_ just displays the video as provided by the device. The state is the same as https://github.com/Genymobile/scrcpy/issues/649#issuecomment-512716552.

(I'm closing since it's a duplicate of #649)

**Closed by rom1v** 2019-12-13 11:05 UTC
