### ISSUE TITLE
Add start or stop record shortcut

### ISSUE THREAD

**Issue by playbyan1453** [Genymobile/scrcpy#1829] opened 2020-10-12 14:20 UTC
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
A shortcut to start record and stop the recording because recording is started when the screen mirrored

**Describe the solution you'd like**
Create a shortcut like <kbd>MOD</kbd>+<kbd>z</kbd>, So when you mirror the screen you did not need start record with a command, so you record the screen with your wish so the recording not start same as application runs, and the interrupt shortcut still same.

**Comment by rom1v** [comment] 2020-10-12 14:27
Duplicate of #475

**Closed by rom1v** 2020-10-12 14:27 UTC
