### ISSUE TITLE
ADB failing to execute on Windows despite being in path

### ISSUE THREAD

**Issue by hex7c** [Genymobile/scrcpy#2981] opened 2022-01-28 18:51 UTC
- (YES) I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - (YES) I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 7 Professional x64]
 - scrcpy version: [1.21 win64]
 - installation method: [Windows release]
 - device model: [Motorola "moto g fast"]
 - Android version: [10]

**Describe the bug**
Whenever I attempt to run scrcpy on Windows 7 64-bit via the pre-built release, It fails to execute ADB every time. I read the RAQ and tried setting the environment variable %ADB% and I included it in my %PATH% as well. I am able to execute ADB standalone as you can see below, when I run `adb get-serialno`. A screenshot attached will display the directory contents. I also verified the SHA-256 hash via the built-in Windows CertUtil and it appears to be correct:

SHA-256 according to README.MD: `fdab0c1421353b592a9bbcebd6e252675eadccca65cca8105686feaa9c1ded53`

SHA-256 according to Windows 7:
```
D:\Installers>certUtil -hashfile .\scrcpy-win64-v1.21.zip SHA256
SHA256 hash of file .\scrcpy-win64-v1.21.zip:
fd ab 0c 14 21 35 3b 59 2a 9b bc eb d6 e2 52 67 5e ad cc ca 65 cc a8 10 56 86 fe
 aa 9c 1d ed 53
CertUtil: -hashfile command completed successfully.
```

On errors, please provide the output of the console (and `adb logcat` if relevant).

ERROR OUTPUT (with proof I tried the steps in the FAQ):
```
D:\Programs\scrcpy-win64-v1.21>scrcpy.exe
scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
ERROR: Failed to execute: [D:\Programs\scrcpy-win64-v1.21\adb.exe], [get-serialno]
ERROR: Could not execute "adb get-serialno"
ERROR: Could not get device serial
ERROR: Server connection failed

D:\Programs\scrcpy-win64-v1.21>adb get-serialno
ZY227Q6JLR

D:\Programs\scrcpy-win64-v1.21>echo %ADB%
D:\Programs\scrcpy-win64-v1.21\adb.exe
```

And the device is authorized and detected according to ADB:
```
D:\>adb devices
List of devices attached
ZY227Q6JLR      device
```

And ADB is in the same directory as scrcpy:
```
D:\Programs\scrcpy-win64-v1.21>dir
 Volume in drive D is MDMA
 Volume Serial Number is 00AD-7F13

 Directory of D:\Programs\scrcpy-win64-v1.21

01/28/2022  12:59 PM    <DIR>          .
01/28/2022  12:59 PM    <DIR>          ..
11/29/2021  04:17 PM         5,941,760 adb.exe
11/29/2021  04:17 PM            97,792 AdbWinApi.dll
11/29/2021  04:17 PM            62,976 AdbWinUsbApi.dll
11/29/2021  04:17 PM        50,103,296 avcodec-58.dll
11/29/2021  04:17 PM        11,094,016 avformat-58.dll
11/29/2021  04:17 PM           866,304 avutil-56.dll
11/29/2021  04:17 PM             6,530 icon.png
11/29/2021  04:17 PM                90 scrcpy-console.bat
11/29/2021  04:17 PM               212 scrcpy-noconsole.vbs
11/29/2021  04:17 PM            40,067 scrcpy-server
11/29/2021  04:17 PM           670,308 scrcpy.exe
11/29/2021  04:17 PM         1,609,728 SDL2.dll
11/29/2021  04:17 PM           433,664 swresample-3.dll
11/29/2021  04:17 PM           552,960 swscale-5.dll
              14 File(s)     71,479,703 bytes
               2 Dir(s)  422,572,474,368 bytes free
```

Please do not post screenshots of your terminal, just post the content as text instead.

Looking into this issue will be greatly appreciated. I will try to respond as fast as possible.

**Comment by rom1v** [comment] 2022-01-28 19:02
Yes, there is a bug in v1.21 for Windows 7. There is a hotfix here: https://github.com/Genymobile/scrcpy/pull/2840 (it is also referenced from the [release](https://github.com/Genymobile/scrcpy/releases/tag/v1.21) page, but I understand that it can be missed easily).

Btw, I will release a new version very soon (probably this week end).

This binary also includes the fix for win7, and also the other changes that will be in v1.22: https://github.com/Genymobile/scrcpy/issues/2976#issuecomment-1023948529
Please use this one and report any problem/regression if you can :wink:

 - [`scrcpy-win64-2976.zip`](https://tmp.rom1v.com/scrcpy/2976/4/scrcpy-win64-2976.zip) _sh&256:babfbbf8e352f97ceecd509348b1b3ea1154322e40e2aca35343517cc3a5e002_

**Comment by hex7c** [comment] 2022-01-28 19:40
Hi there! Thank you for such a quick response. The ZIP you gave me does work but also does NOT. 
When I attempt to run the ADB.EXE in the new ZIP, it immediately crashes with the error in the screenshot (no CMD output at all). 

However, if i go to the original ZIP (the one that did not work) and take the original `adb.exe`, `AdbWinApi.dll`, and `AdbWinUsbApi.dll`, and replace the new files in the new zip with them, it works fine.

Two screenshots will be attached, one of the new ADB breaking, and the working scrcpy.

SHA256 of broken (new) ADB & DLLs:
```
D:\Programs>certutil -hashfile adb.exe SHA256 && certutil -hashfile AdbWinApi.dl
l SHA256 && certutil -hashfile AdbWinUsbApi.dll SHA256
SHA256 hash of file adb.exe:
e7 9d c8 fc 3c 63 85 19 2b dc cd 7f f7 ea be 3d 5c 1e c2 92 47 5a 06 b0 4d 82 75
 9f 07 65 59 82
CertUtil: -hashfile command completed successfully.
SHA256 hash of file AdbWinApi.dll:
d6 01 03 a5 e9 9b c9 88 8f 78 6e e9 16 f5 d6 e4 54 93 c3 24 79 72 cb 05 38 33 80
 3d e7 e9 5c f9
CertUtil: -hashfile command completed successfully.
SHA256 hash of file AdbWinUsbApi.dll:
25 20 7c 50 6d 29 c4 e8 dc eb 61 b4 bd 50 e8 66 9b a2 60 12 98 8a 43 fb f2 6a 89
 0b 1e 60 fc 97
CertUtil: -hashfile command completed successfully.
```
SHA256 of working (old) ADB & DLLs: 
```
D:\Programs\scrcpy-win64-2976>certutil -hashfile adb.exe SHA256 && certutil -has
hfile AdbWinApi.dll SHA256 && certutil -hashfile AdbWinUsbApi.dll SHA256
SHA256 hash of file adb.exe:
fd 48 8a 4e 13 d4 c7 1a cc e6 9e 20 91 64 39 8a 05 6f ba 5a 55 9b 7f 00 c1 35 13
 90 60 4e 5b 98
CertUtil: -hashfile command completed successfully.
SHA256 hash of file AdbWinApi.dll:
d6 01 03 a5 e9 9b c9 88 8f 78 6e e9 16 f5 d6 e4 54 93 c3 24 79 72 cb 05 38 33 80
 3d e7 e9 5c f9
CertUtil: -hashfile command completed successfully.
SHA256 hash of file AdbWinUsbApi.dll:
25 20 7c 50 6d 29 c4 e8 dc eb 61 b4 bd 50 e8 66 9b a2 60 12 98 8a 43 fb f2 6a 89
 0b 1e 60 fc 97
CertUtil: -hashfile command completed successfully.
```

I hope this helps. My original issue has been resolved but I am unsure of whether or not you would like to keep this issue open because of this new bug with the build. I will leave the issue up to you to close. Mention me if I am needed for more details.

![image](https://user-images.githubusercontent.com/80992054/151610863-1cbe6004-090e-473b-bafb-f7da67e60dd5.png)
![image](https://user-images.githubusercontent.com/80992054/151610913-af231272-a0a5-4c71-80f5-61f8dd27df26.png)

**Comment by hex7c** [comment] 2022-01-28 19:43
I forgot to mention: ignore the preceding directories in the CMD prompt. The `scrcpy-win64-2976` folder has had the old ADB files moved to it after the initial test and extraction. Do not take the working directory into account

**Comment by rom1v** [comment] 2022-01-28 20:26
Thank you for the feedback on this version :+1:

> When I attempt to run the ADB.EXE in the new ZIP, it immediately crashes with the error in the screenshot (no CMD output at all).

Does it also happen if you execute `adb devices` or `adb shell`?

What if you execute `adb kill-server` with the latest version of adb (from `scrcpy-win64-2976.zip`) before running scrcpy? Does it still crash?
Do you still have the `ADB` environment variable set in your path?
Is the adb crash always reproducible? If you use the `scrcpy-win64-2976.zip` release after a reboot for example, does it crash?

I could not reproduce the crash on my Windows 7 virtual machine :/

(note that only `adb.exe` has changed, the `dll` are exactly the same, they have the same hash)

If there's a problem, it is probably related to the new adb version: c0de365f672110959cec8fca936bd6aeaa01b59d
I will revert if it's confirmed.

**Comment by hex7c** [comment] 2022-01-28 23:21
It appears that under the new ADB, it is only when I run it without passing any command line arguments. I can run `adb devices` just fine. This still happens when I kill the ADB daemon via task manager.

**Comment by rom1v** [comment] 2022-01-29 06:24
This is weird, because the changelog of the new version says:

> - Fixed adb without args SEGV crash.

https://developer.android.com/studio/releases/platform-tools

If it happens only on the version which claims to fix it, it's unexpected 😄.

But anyway, scrcpy never calls `adb` without args, so I don't understand why it crashes.

**Comment by rom1v** [comment] 2022-01-29 10:48
I can reproduce the crash without args (just running `adb`). I revert to restore the previous version eaba6136334e5fb50d3276ca7405b77e48c8f29e.

**Closed by rom1v** 2022-01-29 10:48 UTC

**Comment by rom1v** [comment] 2022-04-23 13:13
@hex7c Could you please test #3206?
