### ISSUE TITLE
Swedish letters aren't showing up properly while writing

### ISSUE THREAD

**Issue by Dyras** [Genymobile/scrcpy#557] opened 2019-05-26 15:32 UTC
Greetings! I've just started using scrcpy and it's a gift from God, honest! Thanks so much for making it!

However, ÅÄÖ/åäö aren't showing up properly while writing.

"Ä/ä" and "Ö/ö" come out as "A/a" and "O/o", respectively
"Å/å" isn't showing at all

Swedish keyboard
Windows 10 Pro N on Windows Insider

Copy pasting a sentence containing ä and ö results in the copied text having a and o instead.  å seems to block the copying entirely.

Example messages:

Jag bor i Åkersberga
Vad äter vi ikväll?
Övriga utvecklare är inte lika bra som dig

**Comment by Plandercozeron** [comment] 2019-05-27 06:08
Ubuntu 18.10 with `en_DK ` region (Denmark - English)
Pasted "Ä/ä" and "Ö/ö" correctly on:
Samsung Galaxy A5 (SM-A500F) Android 6.0.1
Samsung Galaxy A6 (SM-A600FN) Android 8.0.0

But couldn't paste "Å/å" too

**Comment by rom1v** [comment] 2019-05-27 19:10
> However, ÅÄÖ/åäö aren't showing up properly while writing.

Unfortunately, that's expected. Android only supports injecting ASCII chars: https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-text-input

> "Ä/ä" and "Ö/ö" come out as "A/a" and "O/o", respectively

Some accents are managed via combining diacritical dead key characters. But this does not work correctly with all keyboards: https://blog.rom1v.com/2018/03/introducing-scrcpy/#handle-accented-characters

> å seems to block the copying entirely.

Since #542, it will ignore unsupported characters instead of blocking the remaining.

**Comment by boype** [comment] 2019-06-13 13:58
I have the same problem with the German special characters öäüÖÄÜ. The appear as ¨o¨a¨u and so on.

**Comment by boype** [comment] 2019-06-16 06:56
> You can refer to [ADBKeyBoard](https://github.com/senzhk/ADBKeyBoard) or [SocketIME](https://github.com/npes87184/SocketIME).
This works like a charm, thanks!

**Comment by pabloab** [comment] 2019-09-25 23:29
Probably duplicate of #214

**Comment by niikoo** [comment] 2019-12-18 11:30
Same issue with Norwegian

**Comment by rom1v** [comment] 2020-04-09 19:36
Closing as duplicate of #37.

**Closed by rom1v** 2020-04-09 19:36 UTC
Labels: input events, keyboard, unicode

**Comment by rom1v** [comment] 2020-05-25 01:39
Please test #1426 (works on Android >= 7).
