### ISSUE TITLE
Android 14: NoSuchMethodException turning off phone display

### ISSUE THREAD

**Issue by drothenberger** [Genymobile/scrcpy#4330] opened 2023-10-04 20:46 UTC
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11 Pro
 - scrcpy version: 2.1.1
 - installation method: Windows release
 - device model: Pixel 7
 - Android version: 14

**Describe the bug**
Pressing Alt-O to turn off the phone's display no longer works. It produces a NoSuchMethodException.

```
[server] ERROR: Could not get physical display ids
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by stanleylhs** [comment] 2023-10-04 21:20
Ran into the same issue.

OS: macOS 14
scrcpy version: 2.1.1
installation method: Homebrew
Device model: Pixel 6
Android version: 14

**Comment by rom1v** [comment] 2023-10-05 06:03
Refs #3784

**Comment by Waz999** [comment] 2023-10-05 22:24
After updating to Android 14 yesterday my Google Pixel 7 no longer responds to any keyboard or mouse interactions. It starts fine and displays my phone screen. I just cant do anything.

**Comment by rom1v** [comment] 2023-10-06 05:08
@Waz999 Which scrcpy version? Use the latest (currently 2.1.1)

**Comment by vidoardes** [comment] 2023-10-06 07:28
I can confirm I have this issue on Scrcpy 2.1.1

Pixel 6
Android 14
Windows 11

`[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids`

**Comment by rom1v** [comment] 2023-10-07 10:32
Closing as duplicate of #3927.

**Closed by rom1v** 2023-10-07 10:32 UTC

**Comment by Tamer8383** [comment] 2024-08-07 10:30
.
